export default {
  "last7Days": "最近七天",
  "fullyDiluted": "完全稀释的市值",
  "liquidityProvider": "流动资金提供者费用",
  "averagePrice": "平均价格",
  "priceImpact": "价格影响",
  "minutes": "分钟",
  "gasSetting": "Gas设定",
  "searchNotFound": "找不到搜索",
  "noWalletFound": "无钱包",
  "tradeSuccess": "订购成功",
  "confirmApprove": "批准确认",
  "claimSwap": "索偿确认",
  "confirmSwap": "交换确认",
  "txsFee": "费用: {{amount}} ~ {{amountUSD}}",
  "pleaseWaitOrder": "请稍等一下以完成订单",
  "pleaseWaitApprove": "请稍等一下",
  "approveSuccess": "批准成功",
  "pair": "代币对",
  "confirm": "确认?",
  "terminal": "工具",
  "explorers": "探险家",
  "community": "社区",
  "d1": "一天",
  "m1": "一月",
  "w1": "一周",
  "y1": "一年",
  "full": "所有",
  "coin98Wallet": "Coin98钱包",
  "exchange": "交换",
  "invest": "投资",
  "dashboard": "仪表盘",
  "markets": "交易市场",
  "confirmation": "确认",
  "passphrase": "密码短语",
  "success": "成功!",
  "category": "类别",
  "platform": "平台",
  "createNewWalletSuccessful": "创建新钱包成功！",
  "successfully": "成功",
  "ok": "好的",
  "error": "出问题了！\n   请稍后再试",
  "create": "创建",
  "restore": "恢复",
  "cancel": "取消",
  "receiveAddress": "收货地址",
  "sending": "发送中",
  "manage": "管理",
  "rankMarket": "#排名 {{rank}}",
  "max": "MAX",
  "edited": "已编辑",
  "Error": "错误!",
  "search": "搜索",
  "goBack": "回去",
  "searchCurrency": "搜索货币",
  "lendingBorrowing": "贷款/借",
  "walletNotFound": "找不到钱包",
  "addRestoreWallet": "请先添加或还原钱包",
  "wrongPass": "无效的密码",
  "yieldFarming": "流动性挖矿",
  "defiStation": "DeFi 站",
  "analytics": "分析",
  "nft": "NFT",
  "governance": "管治",
  "coin98WalletMess": "数字资产商店",
  "terminalMess": "多合一工具箱",
  "daapMess": "DeFi 大门",
  "exchangeMess": "交易平台",
  "crossChainMess": "在多个链之间交换资产",
  "dashboardMess": "一切尽在您的掌控之中",
  "marketMess": "关注最新趋势",
  "lendingBorrowingMess": "赢取资产利息",
  "yieldFarmingMess": "资产收益最大化",
  "defiStationMess": "躺着赚钱",
  "portfolioMess": "追踪资产表现",
  "stankingMess": "锁定资产以获得奖励",
  "governanceMess": "对提案进行投票",
  "lunaDex": "基于Solana和Serum的去中心化交易所",
  "connectWallet": "连接钱包",
  "login": "登录",
  "en": " 英文",
  "vi": " 越语",
  "email": "电子邮件",
  "enterEmail": "请输入您的电子邮件",
  "emailInvalid": "无效的邮件地址",
  "userName": "用户名",
  "yourUsername": "您的用户名",
  "displayName": "显示名称",
  "yourDisplayName": "您的显示名称",
  "swaps": "交换",
  "swap": "交换",
  "totalValue": "总价值",
  "totalVolume": "总金量",
  "tokenAmount": "代币数量",
  "account": "帐户",
  "time": "时间",
  "infoAlert": "这是您的信息",
  "infoSuccess": "创造成功",
  "infoError": "由于...发生错误",
  "approveToken": "批准 {{nameTokenBuy}}",
  "buyToken": "买入 {{nameTokenBuy}}",
  "loginSuccess": "登录成功",
  "password": "密码",
  "passInvalid": "密码必须至少包含6位数字，包括数字和字母",
  "confirmPassword": "确认密码",
  "passNotMatch": "密码不匹配",
  "yourPassword": "您的密码",
  "inputPassword": "请输入密码",
  "passRequired": "请输入您的密码",
  "emailVerificationsCode": "您的电子邮件验证码",
  "referralCode": "推荐码",
  "referExistError": "ID不存在",
  "nameBeenTaken": "您的用户名已被使用",
  "nameAlreadyTaken": "此用户名已被使用",
  "resetPass": "重设新密码",
  "usernameRequired": "用户名为必填项",
  "displaynameRequired": "显示名称为必填项",
  "confirmPass": "确认密码为必填项",
  "confirmPassNotMatch": "确认密码不匹配",
  "youHaveBanned": "您已经被禁止",
  "fraudBehaviorDevice": "您不允许访问设备信息\n  或您的手机不符合我们的安全标准",
  "emailRequired": "电子邮件为必填项",
  "manageWallet": "管理钱包",
  "addWallet": "添加钱包",
  "restoreWallet": "恢复钱包",
  "connectOtherWallet": "连接其他钱包",
  "send": "发送",
  "receive": "收到",
  "website": "网站",
  "smartContract": "智能合约",
  "allTimeLow": "历来最低",
  "allTimeHigh": "历来最高",
  "high24h": "24小时高点",
  "low24h": "24小时低点",
  "circulatingSupply": "流通量",
  "maxSupply": "总供给",
  "marketCap": "市值",
  "col24h": "24小时成交量",
  "feeErr": "您的余额或燃料费不足",
  "allWallet": "所有钱包",
  "multiChain": "多链",
  "ether": "Ether",
  "solana": "Solana",
  "binanceSmart": "Binance Smart",
  "polkadot": "Polkadot",
  "kusama": "Kusama",
  "heco": "Heco",
  "mustAtLeastDot": "您必须至少剩余1个DOT才能发送",
  "enterAmountToStartTransaction": "输入金额以开始交易",
  "amountErr": "必须小于或等于可支出金额",
  "walletName": "钱包名称",
  "walletKey": "钱包钥匙",
  "walletKeyPhrase": "助记密码",
  "walletNameExist": "钱包名称已存在",
  "copyDone": "地址{{value}}已复制",
  "onlySend": "仅将发送{{symbol}}到该地址。 将任何其他资产发送到此地址可能会导致您的收款丢失",
  "amount": "数量",
  "recipient": "接受者",
  "walletAddress": "钱包地址",
  "confirmInfo": "确认信息",
  "noData": "没有数据",
  "message": "信息",
  "messageIsOptional": "消息是可选的",
  "inputRequired": "请填写此字段",
  "verifyEmail": "验证邮件",
  "comfirmation": "确认",
  "confirmDelete": "您确定要删除此钱包吗？",
  "passphraseOrPrivateKey": "密码或私钥",
  "verySlow": "非常慢",
  "slow": "慢的",
  "fast": "快速地",
  "superFast": "超级快",
  "standard": "标准",
  "gasWar": "Gas War",
  "starWar": "Star War",
  "tryAgain": "请过几分钟再试",
  "txsFail": "交易失败",
  "whitePaper": "Whitepaper",
  "timeOutTxs": "交易超时或未确认，请稍等一下然后再试.",
  "minimum1Polkadot": "收件人地址必须具有1个以上的DOT",
  "invalidAddr": "无效的收件人地址",
  "createAccount": "创建帐号",
  "createAccountSuccess": "创建帐号成功",
  "areYouSureToCreateANewWallet": "您确定要创建一个新的钱包吗？",
  "createWallet": "创建钱包",
  "phoneRegister": "电话号码仅用于注册帐户",
  "clickContinue": "点击“继续”即表示，您同意",
  "teamService": "Coin98的服务条款",
  "scanToLogin": "扫描登录",
  "forgotPass": "忘记密码？",
  "reset": "重启",
  "continue": "继续",
  "dintRecive": "没有收到验证码?",
  "resend": "重发",
  "restoreWalletSuccess": "恢复钱包成功！",
  "enjoy": "享受",
  "register": "登记",
  "sureNewWallet": "您确定要创建一个新的钱包吗？",
  "myWallet": "我的钱包",
  "understandChoose": "我了解，如果我丢失了恢复密钥，将无法使用我的钱包",
  "done": "完成",
  "manageContact": "管理联络人",
  "hiddenToken": "隐藏的代币列表",
  "setActive": "设为有效",
  "copyAddress": "复制地址",
  "showQr": "显示二维码",
  "showKey": "显示钥匙信息",
  "connectToWallet": "连接钱包",
  "chooseWallet": "选择您的钱包",
  "whatIsWallet": "什么是钱包？",
  "totalBalance": "总余额",
  "otpWrong": "无效的OTP码",
  "asset": "资产",
  "symbol": "象征",
  "price": "价格",
  "balance": "资产",
  "value": "价值",
  "market24": "市场24小时",
  "address": "地址",
  "maxSlippage": "最大滑点",
  "termsOfService": "服务条款",
  "volume": "金量",
  "volume24": "24小时交易金量",
  "selectWallet": "选择钱包",
  "selectedWallet": "选择钱包",
  "addressIsCopy": "地址已复制",
  "orderFunding": "订单的资金",
  "orderVolume": "订单量",
  "youSend": "你发送",
  "youReceive": "您收到",
  "all": "所有",
  "high": "高的",
  "createContact": "建立联络人",
  "recommend": "推荐",
  "comingSoon": "即将推出",
  "connected": "已连接",
  "installCoin98Wallet": "安装用于管理钱包的Coin98钱包",
  "coin98WalletNotInstalled": "未安装Coin98钱包",
  "connectCoin98Wallet": "连接Coin98钱包",
  "BTCDominace": "BTC Dominance",
  "ETHDominace": "ETH Dominance",
  "rank": "排名",
  "onWatchList": "在{{num}}的监视列表中",
  "token": "代币",
  "day": "日",
  "month": "月",
  "week": "星期",
  "year": "年",
  "custom": "风俗",
  "uniswapPrice": "Uniswap 价格",
  "low": "低的",
  "hight": "高的",
  "fullDiluted": "完全稀释后市值",
  "volume24h": "24小时交易量",
  "totalSupply": "总供给",
  "viewDetail": "查看详细",
  "from": "从",
  "to": "到",
  "willReceive": "您会收到 ~ ",
  "fee": "费用",
  "balanceTotal": "余额总计",
  "route": "路线",
  "step": "步",
  "finish": "完成",
  "swapHistory": "交换记录",
  "coins": "硬币",
  "watchList": "监视清单",
  "contract": "合同",
  "priceChange": "变动价格",
  "tradingVolume": "交易量",
  "marketCapRank": "市值排名",
  "atHight": "市值排名",
  "atLow": "历来最低",
  "sushiPrice": " 价格统计",
  "showRows": "显示行",
  "filters": "筛选器",
  "overview": "概述",
  "chart": "图表",
  "cryptoAsset": "加密货币",
  "historicalData": "数据历史",
  "tradingView": "交易视图",
  "uniswapChart": "Uniswap图表",
  "name": "名字",
  "liquidity": "流动资金",
  "Volume": "金量",
  "fees": "费用",
  "topPairs": "顶级对",
  "searchPairToken": "搜索对和代币",
  "invalidPassPhrase": "请再次检查您的密码或钥匙！",
  "needCreate": "请先创建或导入Solana钱包",
  "areYouCreate": "您确定要创建一个新的钱包吗？",
  "willBeStored": "将存储在{{nameChainWallet}}钱包中",
  "feeTransactionMust": "费用交易必须至少为 {{num}} {{symbol}}",
  "chainNotSupported": "尚不支持区块链",
  "nameChart": "{{symbol}} 图表",
  "areYouLogout": "您确定要注销吗?",
  "vol24h": "24小时成交量",
  "volumeMarket": "交易量 / 市值",
  "resetFilters": "Reset Filter",
  "sureToSend": "您确定要发送吗 {{num}} {{symbol}} 到 {{address}}地址吗?",
  "sumAddress": "{{num}} 地址",
  "amountCannotZero": "金额不能为零",
  "multiSend": "Multi Send",
  "totalAddress": "总地址",
  "addressEmpty": "地址不能为空",
  "amountEmpty": "金额不能为空",
  "inputNotRequirements": "信息不符合要求",
  "gwei": "Gwei",
  "hi": "您好",
  "forTransaction": "进行交易",
  "approveConversion": "批准转换",
  "sendFound": "汇款",
  "waitForConfirm": "等待确认",
  "rename": "改名",
  "questionRename": "您确定要重命名钱包吗？",
  "questionImport": "您确定要导入地址和金额吗?",
  "alreadySend": "已发送",
  "resendOTP": "重新发送OTP成功",
  "fortmatic": "Fortmatic",
  "coinbaseWallet": "Coinbase Wallet",
  "walletConnect": "钱包连接",
  "metaMask": "MetaMask",
  "dapper": "Dapper",
  "lattice": "Lattice",
  "private": "私人的",
  "activeMultiChain": "活性式多链钱包",
  "activeChain": "活性式{{chain}}钱包",
  "removeWallet": "去掉{{name}}钱包",
  "noMatchingResult": "没有匹配结果",
  "areYouSureSend": "发送{{num}} {{symbol}} <br/> {{address}}",
  "addressAmount": "address?amount,address?amount",
  "import": "恢复",
  "addressAndAmount": "地址和金额",
  "gasPrice": "GAS PRICE",
  "transactionData": "交易数据",
  "gasLimit": "GAS LIMIT",
  "nonce": "NONCE",
  "change24h": "% 变化",
  "rankTop": "排名前100-200",
  "nameRank": "名字",
  "hour24Trading": "24小时交易量",
  "lowHight24h": "24小时低 / 高",
  "allTimeLowHigh": "历来最低点 / 最高点",
  "unlimitedApproval": "无限批准",
  "estimateFee": "预估费用",
  "searchCoinOrPasteAnyToken": "搜索币或粘贴任何代币",
  "transactionDeadline": "交易截止日期",
  "owners": "业主",
  "votingRate": "投票率",
  "withdraw": "提取",
  "update": "更新",
  "approved": "得到正式认可的",
  "waiting": "正在等待",
  "totalFound": "总发现",
  "totalOwner": "总所有者",
  "awaitingApprove": "等待批准",
  "voteRate": "投票率",
  "owner": "业主",
  "change": "改变",
  "ownersAddress": "业主地址",
  "votingPower": "投票权",
  "type": "类型",
  "date": "日期",
  "status": "地位",
  "process": "过程",
  "transactionId": "交易ID",
  "creator": "创作业主",
  "wellcome": "欢迎来到",
  "multisig": "Multisig钱包",
  "createNew": "创建新的",
  "addOwner": "添加业主",
  "addVoteRate": "增加投票率",
  "multisigWalletName": "Multisignature钱包名称",
  "c98Private": "C98私募基金",
  "successSent": "发送成功",
  "removeOwner": "移除业主",
  "newVoteRate": "新投票率",
  "newVotePower": "新投票权",
  "poweredByCoin98": "Powered by Coin98 Wallet Engine",
  "lessThan": "少于",
  "noSpace": "没有空间",
  "characters": "特征",
  "createTokenError": "创建代币发行者错误",
  "createTokenSuccess": "创建代币发行者成功",
  "confirmCreateTokenIssue": "您确定要确认这个代币吗 ?",
  "pleaseInput": "请输入",
  "invalidAddrWallet": "无效地址",
  "wallet": "钱包",
  "tokenName": "代币名称",
  "tokenSymbol": "代币符号",
  "decimalPoint": "小数点",
  "ownerAddress": "所有者地址",
  "tokenLogo": "代币徽标",
  "selectChain": "选择链",
  "tokenMint": "TOKEN MINT",
  "tokenBurn": "TOKEN BURN",
  "powerByCoin98": "Powered by Coin98 Labs"
}