export default {
  "last7Days": "LAST 7 DAYS",
  "fullyDiluted": "Fully Diluted Market Cap",
  "liquidityProvider": "Liquidity Provider Fee",
  "averagePrice": "Average Price",
  "priceImpact": "Price Impact",
  "minutes": "minutes",
  "gasSetting": "Gas Setting",
  "searchNotFound": "Search Not Found",
  "noWalletFound": "No Wallet",
  "tradeSuccess": "Order Successfully",
  "confirmApprove": "Approval Confirmation",
  "claimSwap": "Claim Confirmation",
  "confirmSwap": "Swap Confirmation",
  "txsFee": "Fee: {{amount}} ~ {{amountUSD}}",
  "pleaseWaitOrder": "Please wait a moment for order to be completed",
  "pleaseWaitApprove": "Please wait a moment for approval",
  "approveSuccess": "Approve Successfully",
  "pair": "Pair",
  "confirm": "Confirm",
  "terminal": "Terminal",
  "explorers": "Explorers",
  "community": "Community",
  "d1": "1D",
  "m1": "1M",
  "w1": "1W",
  "y1": "1Y",
  "full": "Full",
  "coin98Wallet": "Coin98 Wallet",
  "exchange": "Exchange",
  "invest": "Invest",
  "dashboard": "Dashboard",
  "markets": "Markets",
  "confirmation": "Confirmation",
  "passphrase": "Passphrase",
  "success": "Success!",
  "category": "category",
  "platform": "Platform",
  "createNewWalletSuccessful": "Create a new wallet successfully!",
  "successfully": "Successfully",
  "ok": "Ok",
  "error": "Something went wrong!\n  Please try again later",
  "create": "Create",
  "restore": "Restore",
  "cancel": "Cancel",
  "receiveAddress": "Receive Address",
  "sending": "Sending",
  "manage": "Manage",
  "rankMarket": "#Rank {{rank}}",
  "max": "MAX",
  "edited": "Edited",
  "Error": "Error!",
  "search": "Search",
  "goBack": "Go Back",
  "searchCurrency": "Search Currency",
  "lendingBorrowing": "Lend/Borrow",
  "walletNotFound": "Wallet Not Found",
  "addRestoreWallet": "Please add or restore a wallet first",
  "wrongPass": "Invalid password",
  "yieldFarming": "Yield Farming",
  "defiStation": "DeFi Station",
  "analytics": "Analytics",
  "nft": "NFT",
  "governance": "Governance",
  "coin98WalletMess": "Store Digital Assets",
  "terminalMess": "All-In-One Toolbox",
  "daapMess": "DeFi Gateway",
  "exchangeMess": "Trading Platform",
  "crossChainMess": "Swap assets across multiple chains",
  "dashboardMess": "Everything under your control",
  "marketMess": "Follow latest trends",
  "lendingBorrowingMess": "Earn interest on assets",
  "yieldFarmingMess": "Maximize yields on your assets",
  "defiStationMess": "Earn money while you sleep",
  "portfolioMess": "Track assets performance",
  "stankingMess": "Lock assets to receive rewards",
  "governanceMess": "Vote on proposals",
  "lunaDex": "DEX built on Solana and Serum",
  "connectWallet": "Connect Wallet",
  "login": "Login",
  "en": "English",
  "vi": "Vietnamese",
  "email": "Email",
  "enterEmail": "Please enter your email",
  "emailInvalid": "Invalid email address",
  "userName": "Username",
  "yourUsername": "Your Username",
  "displayName": "Display Name",
  "yourDisplayName": "Your Display Name",
  "swaps": "Swaps",
  "swap": "Swap",
  "totalValue": "Total Value",
  "totalVolume": "Total Volume",
  "tokenAmount": "Token Amount",
  "account": "Account",
  "time": "Time",
  "infoAlert": "This is your Info",
  "infoSuccess": "Create something successfully",
  "infoError": "Error due to ...",
  "approveToken": "Approve {{nameTokenBuy}}",
  "buyToken": "Buy {{nameTokenBuy}}",
  "loginSuccess": "Login Successfully",
  "password": "Password",
  "passInvalid": "Password must have at least 6 digits with number and letter",
  "confirmPassword": "Confirm Password",
  "passNotMatch": "Password doesn't match",
  "yourPassword": "Your Password",
  "inputPassword": "Please input password",
  "passRequired": "Please enter your password",
  "emailVerificationsCode": "Your email verification code",
  "referralCode": "Referral code",
  "referExistError": "ID does not exist",
  "nameBeenTaken": "Your username has been taken",
  "nameAlreadyTaken": "This name has been already taken",
  "resetPass": "Reset New Password",
  "usernameRequired": "Username is required",
  "displaynameRequired": "Display name is required",
  "confirmPass": "Confirm password is required",
  "confirmPassNotMatch": "Confirm password doesn't match",
  "youHaveBanned": "You have been banned!",
  "fraudBehaviorDevice": "You have not allowed access to device information\nOr your phone does not meet our safety standards",
  "emailRequired": "Email is required",
  "manageWallet": "Manage Wallets",
  "addWallet": "Add Wallet",
  "restoreWallet": "Restore Wallet",
  "connectOtherWallet": "Connect Other Wallet",
  "send": "Send",
  "receive": "Receive",
  "website": "Website",
  "smartContract": "Smart Contract",
  "allTimeLow": "All Time Low",
  "allTimeHigh": "All Time High",
  "high24h": "24H High",
  "low24h": "24H Low",
  "circulatingSupply": "Circulating Supply",
  "maxSupply": "Max Supply",
  "marketCap": "Market Cap",
  "col24h": "24H Vol",
  "feeErr": "Your balance or gas fee is not enough",
  "allWallet": "All Wallets",
  "multiChain": "Multi-Chain",
  "ether": "Ether",
  "solana": "Solana",
  "binanceSmart": "Binance Smart",
  "polkadot": "Polkadot",
  "kusama": "Kusama",
  "heco": "Heco",
  "mustAtLeastDot": "You must have at least 1 DOT remain to send",
  "enterAmountToStartTransaction": "Enter amount to start transaction",
  "amountErr": "Must be less than or equal to spendable amount",
  "walletName": "Wallet name",
  "walletKey": "Wallet key",
  "walletKeyPhrase": "Mnenmonic Passphrase",
  "walletNameExist": "Wallet name already exists",
  "copyDone": "Address {{value}} is copied",
  "onlySend": "Only send {{symbol}} to this address. Sending any other asset to this address will result in asset loss",
  "amount": "Amount",
  "recipient": "Recipient",
  "walletAddress": "Wallet Address",
  "confirmInfo": "Confirm Info",
  "noData": "No Data",
  "message": "Message",
  "messageIsOptional": "Message Is Optional",
  "inputRequired": "Please fill in this field",
  "verifyEmail": "Verify Email",
  "comfirmation": "Confirmation",
  "confirmDelete": "Are you sure to remove this wallet?",
  "passphraseOrPrivateKey": "Passphrase or Private Key",
  "verySlow": "Very Slow",
  "slow": "Slow",
  "fast": "Fast",
  "superFast": "Super Fast",
  "standard": "Standard",
  "gasWar": "Gas War",
  "starWar": "Star War",
  "tryAgain": "Please try again in a few minutes",
  "txsFail": "Transaction failed",
  "whitePaper": "Whitepaper",
  "timeOutTxs": "Transaction timed out or unconfirmed, please wait a moment and try again.",
  "minimum1Polkadot": "Recipient address needs to have more than 1 DOT",
  "invalidAddr": "Invalid recipient address",
  "createAccount": "Create Account",
  "createAccountSuccess": "Create account successfully",
  "areYouSureToCreateANewWallet": "Are you sure to create a new wallet?",
  "createWallet": "Create Wallet",
  "phoneRegister": "Phone number is only used for a registered account",
  "clickContinue": "By clicking \"Continue\", you agree to",
  "teamService": "Coin98 Wallet Terms of Service",
  "scanToLogin": "Scan to login",
  "forgotPass": "Forgot your password?",
  "reset": "Reset",
  "continue": "Continue",
  "dintRecive": "Didn't receive verification code?",
  "resend": "Resend",
  "restoreWalletSuccess": "Restore wallet successfully!",
  "enjoy": "Enjoy",
  "register": "Register",
  "sureNewWallet": "Are you sure to create a new wallet?",
  "myWallet": "My Wallet",
  "understandChoose": "I understand that if I lose my recovery key, I will not be able to access my wallet",
  "done": "Done",
  "manageContact": "Manage Contacts",
  "hiddenToken": "Hidden Token List",
  "setActive": "Set Active",
  "copyAddress": "Copy Address",
  "showQr": "Show QR Code",
  "showKey": "Show Key Info",
  "connectToWallet": "Connect To A Wallet",
  "chooseWallet": "Choose your wallet",
  "whatIsWallet": "What is a wallet?",
  "totalBalance": "Total Balance",
  "otpWrong": "Invalid OTP code",
  "asset": "Asset",
  "symbol": "Symbol",
  "price": "Price",
  "balance": "Balance",
  "value": "Value",
  "market24": "24h",
  "address": "Address",
  "maxSlippage": "Max Slippage",
  "termsOfService": "Terms Of Service",
  "volume": "Volume",
  "volume24": "24H Volume",
  "selectWallet": "Select Wallet",
  "selectedWallet": "Select Wallet",
  "addressIsCopy": "Address is copied",
  "orderFunding": "Order Funding",
  "orderVolume": "Order Volume",
  "youSend": "YOU SEND",
  "youReceive": "YOU RECEIVE",
  "all": "All",
  "high": "High",
  "createContact": "Create Contact",
  "recommend": "Recommend",
  "comingSoon": "Coming Soon",
  "connected": "Connected",
  "installCoin98Wallet": "Install Coin98 Wallet for management wallet",
  "coin98WalletNotInstalled": "Coin98 Wallet has not been installed",
  "connectCoin98Wallet": "Connect to Coin98 Wallet",
  "BTCDominace": "BTC Dominance",
  "ETHDominace": "ETH Dominance",
  "rank": "Rank",
  "onWatchList": "On {{num}} Watchlist",
  "token": "Token",
  "day": "day",
  "month": "month",
  "week": "week",
  "year": "year",
  "custom": "custom",
  "uniswapPrice": "Uniswap Price",
  "low": "Low",
  "hight": "Hight",
  "fullDiluted": "Fully Diluted Market Cap",
  "volume24h": "Volume 24h",
  "totalSupply": "Total Supply",
  "viewDetail": "View Details",
  "from": "From",
  "to": "to",
  "willReceive": "You will receive ~ ",
  "fee": "Fee",
  "balanceTotal": "Balance total",
  "route": "Route",
  "step": "Step",
  "finish": "Finish",
  "swapHistory": "Swap History",
  "coins": "Coins",
  "watchList": "Watchlist",
  "contract": "Contract",
  "priceChange": "Price Change",
  "tradingVolume": "Trading Volume",
  "marketCapRank": "Market Cap Rank",
  "atHight": "All Time High",
  "atLow": "All Time Low",
  "sushiPrice": "Price Statistics",
  "showRows": "Show rows",
  "filters": "Filter",
  "overview": "Overview",
  "chart": "Chart",
  "cryptoAsset": "Cryptos",
  "historicalData": "Historical Data",
  "tradingView": "Trading View",
  "uniswapChart": "Uniswap Chart",
  "name": "name",
  "liquidity": "Liquidity",
  "Volume": "Volume",
  "fees": "fees",
  "topPairs": "Top Pairs",
  "searchPairToken": "Search pair and token",
  "invalidPassPhrase": "Please check your Passphrase or Private Key again!",
  "needCreate": "Need to create or import a Solana wallet first",
  "areYouCreate": "Are you sure to create a new wallet?",
  "willBeStored": "Will be stored in {{nameChainWallet}} Wallet",
  "feeTransactionMust": "Transaction fee must be at least {{num}} {{symbol}}",
  "chainNotSupported": "Chain has not yet been supported",
  "nameChart": "{{symbol}} chart",
  "areYouLogout": "Are you sure to log out?",
  "vol24h": "24H Vol",
  "volumeMarket": "Volume / Market Cap",
  "resetFilters": "Reset Filter",
  "sureToSend": "Are you sure to send {{num}} {{symbol}} to {{address}} address?",
  "sumAddress": "{{num}} Address",
  "amountCannotZero": "Amount cannot be zero",
  "multiSend": "Multi-Send",
  "totalAddress": "Total Address",
  "addressEmpty": "Address cannot be empty",
  "amountEmpty": "Amount cannot be empty",
  "inputNotRequirements": "Input does not meet requirements",
  "gwei": "Gwei",
  "hi": "Hi",
  "forTransaction": "For Transaction",
  "approveConversion": "Approve Conversion",
  "sendFound": "Send Fund",
  "waitForConfirm": "Wait for Confirmations",
  "rename": "Rename",
  "questionRename": "Are you sure to rename wallet?",
  "questionImport": "Are you sure to import address and amount?",
  "alreadySend": "Already sent",
  "resendOTP": "Resend OTP Successfully",
  "fortmatic": "Fortmatic",
  "coinbaseWallet": "Coinbase Wallet",
  "walletConnect": "Wallet Connect",
  "metaMask": "MetaMask",
  "dapper": "Dapper",
  "lattice": "Lattice",
  "private": "Private",
  "activeMultiChain": "Activate Multi-Chain Wallet",
  "activeChain": "Activate {{chain}} Wallet",
  "removeWallet": "Remove {{name}} Wallet",
  "noMatchingResult": "No matching result",
  "areYouSureSend": "Send {{num}} {{symbol}} <br/> {{address}}",
  "addressAmount": "address?amount,address?amount",
  "import": "Import",
  "addressAndAmount": "Address and amount",
  "gasPrice": "GAS PRICE",
  "transactionData": "TRANSACTION DATA",
  "gasLimit": "GAS LIMIT",
  "nonce": "NONCE",
  "change24h": "% Change",
  "rankTop": "Rank Top 100-200",
  "nameRank": "Name",
  "hour24Trading": "24 Hour Trading Vol",
  "lowHight24h": "24H Low / High",
  "allTimeLowHigh": "All Time Low / High",
  "unlimitedApproval": "Unlimited Approval",
  "estimateFee": "Estimate Fee",
  "searchCoinOrPasteAnyToken": "Search coin or paste any token",
  "transactionDeadline": "Transaction Deadline",
  "owners": "Owners",
  "votingRate": "Voting Rate",
  "withdraw": "Withdraw",
  "update": "Update",
  "approved": "Approved",
  "waiting": "Waiting",
  "totalFound": "Total Found",
  "totalOwner": "Total Owners",
  "awaitingApprove": "Awaiting Approval",
  "voteRate": "Voting Rate",
  "owner": "Owner",
  "change": "Change",
  "ownersAddress": "Owners Address",
  "votingPower": "Voting Power",
  "type": "Type",
  "date": "Date",
  "status": "Status",
  "process": "Process",
  "transactionId": "transaction ID",
  "creator": "Creator",
  "wellcome": "Welcome to",
  "multisig": "Multisig Wallet",
  "createNew": "Create New",
  "addOwner": "Add Owner",
  "addVoteRate": "Add Voting Rate",
  "multisigWalletName": "Multisignature Wallet name",
  "c98Private": "C98 Private Fund",
  "successSent": "Sent Succesfully",
  "removeOwner": "Remove Owner",
  "newVoteRate": "New Voting Rate",
  "newVotePower": "New Voting Power",
  "poweredByCoin98": "Powered by Coin98 Wallet Engine",
  "lessThan": "Less than",
  "noSpace": "No space",
  "characters": "characters",
  "createTokenError": "Create Token Issuer Error",
  "createTokenSuccess": "Create Token Issuer Successfully",
  "confirmCreateTokenIssue": "Are you sure to confirm Token Issuer?",
  "pleaseInput": "Please Input",
  "invalidAddrWallet": "Invalid Address",
  "wallet": "Wallet",
  "tokenName": "TOKEN NAME",
  "tokenSymbol": "TOKEN SYMBOL",
  "decimalPoint": "DECIMAL POINTS",
  "ownerAddress": "OWNER ADDRESS",
  "tokenLogo": "TOKEN LOGO",
  "selectChain": "select chain",
  "tokenMint": "TOKEN MINT",
  "tokenBurn": "TOKEN BURN",
  "powerByCoin98": "Powered by Coin98 Labs"
}