export default {
  "last7Days": "ÚLTIMOS 7 DÍAS",
  "fullyDiluted": "Capitalización bursátil totalmente diluida",
  "liquidityProvider": "Comisión del proveedor de liquidez",
  "averagePrice": "Precio promedio",
  "priceImpact": "Impacto del precio",
  "minutes": "minutos",
  "gasSetting": "Ajuste de gas",
  "searchNotFound": "Búsqueda no encontrada",
  "noWalletFound": "No hay monederos",
  "tradeSuccess": "Ordenado exitosamente",
  "confirmApprove": "Confirmación de aprobación",
  "claimSwap": "Confirmación de la reclamación",
  "confirmSwap": "Confirmación de intercambio",
  "txsFee": "Tarifa: {{amount}} ~ {{amountUSD}}",
  "pleaseWaitOrder": "Por favor espera un momento a que se complete la orden",
  "pleaseWaitApprove": "Por favor espera un momento para su aprobación",
  "approveSuccess": "Aprobado con éxito",
  "pair": "Par",
  "confirm": "Confirmar",
  "terminal": "Terminal",
  "explorers": "Exploradores",
  "community": "Comunidad",
  "d1": "1d",
  "m1": "1m",
  "w1": "1s",
  "y1": "1a",
  "full": "Completo",
  "coin98Wallet": "Monedero Coin98",
  "exchange": "Intercambiar",
  "invest": "Invertir",
  "dashboard": "Tablero",
  "markets": "Mercados",
  "confirmation": "Confirmación",
  "passphrase": "Frase de paso",
  "success": "¡Éxito!",
  "category": "categoría",
  "platform": "Plataforma",
  "createNewWalletSuccessful": "¡Nuevo monedero creado con éxito!",
  "successfully": "Exitosamente",
  "ok": "Ok",
  "error": "¡Algo salió mal!\n  Intenta de nuevo más tarde",
  "create": "Crear",
  "restore": "Restaurar",
  "cancel": "Cancelar",
  "receiveAddress": "Recibir dirección",
  "sending": "Enviando",
  "manage": "Administrar",
  "rankMarket": "#Rango {{rank}}",
  "max": "MÁX",
  "edited": "Editado",
  "Error": "¡Error!",
  "search": "Buscar",
  "goBack": "Volver",
  "searchCurrency": "Buscar divisa",
  "lendingBorrowing": "Prestar/tomar",
  "walletNotFound": "Monedero no encontrado",
  "addRestoreWallet": "Por favor agrega o restaura primero un monedero",
  "wrongPass": "Contraseña incorrecta",
  "yieldFarming": "Agricultura de rendimiento",
  "defiStation": "DeFi Station",
  "analytics": "Análisis",
  "nft": "NFT",
  "governance": "Gobernanza",
  "coin98WalletMess": "Almacenar activos digitales",
  "terminalMess": "All-In-One Toolbox",
  "daapMess": "DeFi Gateway",
  "exchangeMess": "Plataforma de intercambio",
  "crossChainMess": "Intercambiar activos mediante cadenas múltiples",
  "dashboardMess": "Todo está bajo control",
  "marketMess": "Seguir las últimas tendencias",
  "lendingBorrowingMess": "Gana intereses sobre los activos",
  "yieldFarmingMess": "Maximiza el rendimiento de tus activos",
  "defiStationMess": "Gana dinero mientras duermes",
  "portfolioMess": "Sigue el rendimiento de tus activos",
  "stankingMess": "Bloquea los activos para recibir recompensas",
  "governanceMess": "Vota en las propuestas",
  "lunaDex": "Intercambio descentralizado creado en Solana y Serum",
  "connectWallet": "Conectar monedero",
  "login": "Iniciar sesión",
  "en": "Inglés",
  "vi": "Vietnamita",
  "email": "Correo electrónico",
  "enterEmail": "Por favor introduce tu correo electrónico",
  "emailInvalid": "Dirección de correo electrónico inválida",
  "userName": "Nombre de usuario",
  "yourUsername": "Tu nombre de usuario",
  "displayName": "Mostrar nombre",
  "yourDisplayName": "Tu nombre para mostrar",
  "swaps": "Intercambios",
  "swap": "Intercambio",
  "totalValue": "Valor total",
  "totalVolume": "Volumen total",
  "tokenAmount": "Cantidad de tokens",
  "account": "Cuenta",
  "time": "Hora",
  "infoAlert": "Ésta es tu información",
  "infoSuccess": "Algo creado con éxito",
  "infoError": "Error debido a.…",
  "approveToken": "Aprobar {{nameTokenBuy}}",
  "buyToken": "Comprar {{nameTokenBuy}}",
  "loginSuccess": "Inicio de sesión exitoso",
  "password": "Contraseña",
  "passInvalid": "La contraseña debe tener al menos 6 dígitos con números y letras",
  "confirmPassword": "Confirmar contraseña",
  "passNotMatch": "La contraseña no coincide",
  "yourPassword": "Tu contraseña",
  "inputPassword": "Por favor introduce la contraseña",
  "passRequired": "Por favor introduce tu contraseña",
  "emailVerificationsCode": "Tu código de verificación de correo electrónico",
  "referralCode": "Código de remisión",
  "referExistError": "El ID no existe",
  "nameBeenTaken": "Tu nombre de usuario ha sido tomado",
  "nameAlreadyTaken": "Este nombre ya ha sido tomado",
  "resetPass": "Restablecer nueva contraseña",
  "usernameRequired": "Se requiere un nombre de usuario",
  "displaynameRequired": "Se requiere mostrar el nombre",
  "confirmPass": "Se requiere confirmar la contraseña",
  "confirmPassNotMatch": "La contraseña no coincide",
  "youHaveBanned": "¡Has sido baneado!",
  "fraudBehaviorDevice": "No tienes permitido el acceso a la información del dispositivo\n  O tu teléfono no cumple los estándares de seguridad",
  "emailRequired": "Se requiere un correo electrónico",
  "manageWallet": "Gestionar monederos",
  "addWallet": "Agregar monedero",
  "restoreWallet": "Restaurar monedero",
  "connectOtherWallet": "Conectar otro monedero",
  "send": "Enviar",
  "receive": "Recibir",
  "website": "Sitio web",
  "smartContract": "Contrato inteligente",
  "allTimeLow": "Mínimo histórico",
  "allTimeHigh": "Máximo histórico",
  "high24h": "Máximo en las últimas 24h",
  "low24h": "Mínimo en las últimas 24h",
  "circulatingSupply": "Suministro en circulación",
  "maxSupply": "Suministro Max",
  "marketCap": "Capitalización de mercado",
  "col24h": "Vol. en las últimas 24h",
  "feeErr": "Tu balance o la tarifa de gas no son suficiente",
  "allWallet": "Todos los monederos",
  "multiChain": "Multi-Chain",
  "ether": "Ether",
  "solana": "Solana",
  "binanceSmart": "Binance Smart",
  "polkadot": "Polkadot",
  "kusama": "Kusama",
  "heco": "Heco",
  "mustAtLeastDot": "Debes tener al menos 1 DOT restante para enviar",
  "enterAmountToStartTransaction": "Introduce la cantidad para iniciar la transacción",
  "amountErr": "Debe ser menor o igual a la cantidad gastable",
  "walletName": "Nombre del monedero",
  "walletKey": "Clave del monedero",
  "walletKeyPhrase": "Frase mnemotécnica",
  "walletNameExist": "Ya existe una cartera con ese nombre",
  "copyDone": "Se ha copiado la dirección {{value}}",
  "onlySend": "Solo envía {{symbol}} a esta dirección. Enviar cualquier otro activo resultará en la pérdida de éste",
  "amount": "Cantidad",
  "recipient": "Destinatario",
  "walletAddress": "Dirección del monedero",
  "confirmInfo": "Confirmar información",
  "noData": "Sin datos",
  "message": "Mensaje",
  "messageIsOptional": "El mensaje es opcional",
  "inputRequired": "Por favor llena este campo",
  "verifyEmail": "Verificar correo electrónico",
  "comfirmation": "Confirmación",
  "confirmDelete": "¿Seguro que deseas remover este monedero?",
  "passphraseOrPrivateKey": "Frase de paso o clave privada",
  "verySlow": "Muy lento",
  "slow": "Lento",
  "fast": "Rápido",
  "superFast": "Súper rápido",
  "standard": "Estándar",
  "gasWar": "Gas War",
  "starWar": "Star War",
  "tryAgain": "Por favor intenta de nuevo en unos minutos",
  "txsFail": "Transacción fallida",
  "whitePaper": "Libro blanco",
  "timeOutTxs": "Se ha acabado el tiempo de la transacción o no se ha confirmado, espera e intenta de nuevo.",
  "minimum1Polkadot": "La dirección del destinatario necesita tener más de 1 DOT",
  "invalidAddr": "Dirección de destinatario inválida",
  "createAccount": "Crear una cuenta",
  "createAccountSuccess": "Cuenta creada exitosamente",
  "areYouSureToCreateANewWallet": "¿Seguro que deseas crear un nuevo monedero?",
  "createWallet": "Crear monedero",
  "phoneRegister": "El número de teléfono es utilizado solo para una cuenta registrada",
  "clickContinue": "Al hacer clic en \"Continuar\", aceptas",
  "teamService": "Términos de servicio de Coin98 Wallet",
  "scanToLogin": "Escanea para iniciar sesión",
  "forgotPass": "¿Olvidaste tu contraseña?",
  "reset": "Reiniciar",
  "continue": "Continuar",
  "dintRecive": "¿No recibiste el código de verificación?",
  "resend": "Reenviar",
  "restoreWalletSuccess": "¡Monedero reestablecido exitosamente!",
  "enjoy": "Disfruta",
  "register": "Registrar",
  "sureNewWallet": "¿Seguro que deseas crear un nuevo monedero?",
  "myWallet": "Mi monedero",
  "understandChoose": "Entiendo que, si pierdo mi clave de recuperación, no podré acceder a mi monedero",
  "done": "Hecho",
  "manageContact": "Administrar contactos",
  "hiddenToken": "Lista de tokens ocultos",
  "setActive": "Establecer activo",
  "copyAddress": "Copiar dirección",
  "showQr": "Mostrar código QR",
  "showKey": "Mostrar información de la clave",
  "connectToWallet": "Conectar a un monedero",
  "chooseWallet": "Escoge tu monedero",
  "whatIsWallet": "¿Qué es un monedero?",
  "totalBalance": "Balance total",
  "otpWrong": "Código OTP inválido",
  "asset": "Activo",
  "symbol": "Símbolo",
  "price": "Precio",
  "balance": "Balance",
  "value": "Valor",
  "market24": "24h",
  "address": "Dirección",
  "maxSlippage": "Deslizamiento máximo",
  "termsOfService": "Términos del servicio",
  "volume": "Volumen",
  "volume24": "Volumen de las últimas 24h",
  "selectWallet": "Seleccionar monedero",
  "selectedWallet": "Seleccionar monedero",
  "addressIsCopy": "Se ha copiado la dirección",
  "orderFunding": "Ordenar la financiación",
  "orderVolume": "Ordenar el volumen",
  "youSend": "LOS QUE ENVIAS",
  "youReceive": "LOS QUE RECIBES",
  "all": "Todo",
  "high": "Alto",
  "createContact": "Crear contacto",
  "recommend": "Recomendar",
  "comingSoon": "Próximamente",
  "connected": "Conectado",
  "installCoin98Wallet": "Instala Coin98 Wallet para gestionar monederos",
  "coin98WalletNotInstalled": "No se ha instalado Coin98 Wallet",
  "connectCoin98Wallet": "Conectar a Coin98 Wallet",
  "BTCDominace": "Dominio de BTC",
  "ETHDominace": "Dominio de ETH",
  "rank": "Rango",
  "onWatchList": "En la lista de vigilancia {{num}}",
  "token": "Token",
  "day": "día",
  "month": "mes",
  "week": "semana",
  "year": "año",
  "custom": "personalizado",
  "uniswapPrice": "Precio de Uniswap",
  "low": "Bajo",
  "hight": "Alto",
  "fullDiluted": "Capitalización bursátil totalmente diluida",
  "volume24h": "Volumen de las últimas 24h",
  "totalSupply": "Suministro total",
  "viewDetail": "Ver detalles",
  "from": "Desde",
  "to": "a",
  "willReceive": "Recibirás ~",
  "fee": "Tarifa",
  "balanceTotal": "Balance total",
  "route": "Ruta",
  "step": "Paso",
  "finish": "Terminar",
  "swapHistory": "Historial de intercambios",
  "coins": "Monedas",
  "watchList": "Lista de vigilancia",
  "contract": "Contrato",
  "priceChange": "Cambio de precio",
  "tradingVolume": "Volumen de intercambios",
  "marketCapRank": "Rango de la capitalización de mercado",
  "atHight": "Máximo histórico",
  "atLow": "Mínimo histórico",
  "sushiPrice": "Estadísticas de precio",
  "showRows": "Mostrar renglones",
  "filters": "Filtrar",
  "overview": "Vista general",
  "chart": "Gráfico",
  "cryptoAsset": "Criptos",
  "historicalData": "Datos históricos",
  "tradingView": "Vista comercial",
  "uniswapChart": "Gráfico de uniswap",
  "name": "nombre",
  "liquidity": "Liquidez",
  "Volume": "Volumen",
  "fees": "tarifas",
  "topPairs": "Pares superiores",
  "searchPairToken": "Buscar par y token",
  "invalidPassPhrase": "¡Por favor revisa tu frase de paso o clave privada e intenta de nuevo!",
  "needCreate": "Necesitas primero crear o importar un monedero de Solana",
  "areYouCreate": "¿Seguro que deseas crear un nuevo monedero?",
  "willBeStored": "Será almacenado en el monedero {{nameChainWallet}}",
  "feeTransactionMust": "La tarifa de transacción debe ser de al menos {{num}} {{symbol}}",
  "chainNotSupported": "Chain aún no es soportada",
  "nameChart": "Gráfico de {{symbol}}",
  "areYouLogout": "¿Seguro que deseas cerrar sesión?",
  "vol24h": "Vol. de las últimas 24h",
  "volumeMarket": "Volumen / Capitalización del mercado",
  "resetFilters": "Restablecer filtros",
  "sureToSend": "¿Seguro que deseas enviar {{num}} {{symbol}} a {{address}}?",
  "sumAddress": "Dirección {{num}}",
  "amountCannotZero": "La cantidad no puede ser cero",
  "multiSend": "Multienvío",
  "totalAddress": "Dirección total",
  "addressEmpty": "La dirección no puede estar vacía",
  "amountEmpty": "La cantidad no puede estar vacía",
  "inputNotRequirements": "La entrada no cumple los requisitos",
  "gwei": "Gwei",
  "hi": "Hola",
  "forTransaction": "Para transacción",
  "approveConversion": "Aprobar conversión",
  "sendFound": "Enviar fondos",
  "waitForConfirm": "Espera la confirmación",
  "rename": "Renombrar",
  "questionRename": "¿Seguro que deseas renombrar el monedero?",
  "questionImport": "¿Seguro que deseas importar la dirección y la cantidad?",
  "alreadySend": "Ya enviados",
  "resendOTP": "OTP reenviado con éxito",
  "fortmatic": "Fortmatic",
  "coinbaseWallet": "Coinbase Wallet",
  "walletConnect": "Wallet Connect",
  "metaMask": "MetaMask",
  "dapper": "Dapper",
  "lattice": "Lattice",
  "private": "Privado",
  "activeMultiChain": "Activar monedero multi-cadena",
  "activeChain": "Activar monedero {{chain}}",
  "removeWallet": "Remover monedero {{chain}}",
  "noMatchingResult": "No coinciden los resultados",
  "areYouSureSend": "Enviar {{num}} {{symbol}} <br/> {{address}}",
  "addressAmount": "¿Dirección? Cantidad, ¿dirección? Cantidad",
  "import": "Importar",
  "addressAndAmount": "Dirección y cantidad",
  "gasPrice": "PRECIO DEL GAS",
  "transactionData": "INFORMACIÓN DE TRANSACCIÓN",
  "gasLimit": "LÍMITE DEL GAS",
  "nonce": "NONCE",
  "change24h": "% de cambio",
  "rankTop": "Clasificación 100-200",
  "nameRank": "Nombre",
  "hour24Trading": "Vol. de intercambio las últimas 24h",
  "lowHight24h": "Mín / Máx de las última 24h",
  "allTimeLowHigh": "Mín / Máx histórico",
  "unlimitedApproval": "Aprobación ilimitada",
  "estimateFee": "Tarifa estimada",
  "searchCoinOrPasteAnyToken": "Buscar moneda o pegar cualquier token",
  "transactionDeadline": "Plazo de la transacción",
  "owners": "Propietarios",
  "votingRate": "Porcentaje de votos",
  "withdraw": "Retirar",
  "update": "Actualizar",
  "approved": "Aprobado",
  "waiting": "Esperando",
  "totalFound": "Total de los encontrados",
  "totalOwner": "Total de los propietarios",
  "awaitingApprove": "Esperando aprobación",
  "voteRate": "Porcentaje de votos",
  "owner": "Propietario",
  "change": "Cambiar",
  "ownersAddress": "Direcciones de los propietarios",
  "votingPower": "Poder del voto",
  "type": "Tipo",
  "date": "Fecha",
  "status": "Estatus",
  "process": "Proceso",
  "transactionId": "ID de la transacción",
  "creator": "Creador",
  "wellcome": "Bienvenido a",
  "multisig": "Multisig Wallet",
  "createNew": "Crear nuevo",
  "addOwner": "Agregar propietario",
  "addVoteRate": "Agregar porcentaje de votos",
  "multisigWalletName": "Nombre del monedero de Multisignature",
  "c98Private": "Fondo privado de C98",
  "successSent": "Enviado exitosamente",
  "removeOwner": "Remover propietario",
  "newVoteRate": "Nuevo porcentaje de votos",
  "newVotePower": "Nuevo poder del voto",
  "poweredByCoin98": "Con la ayuda de Coin98 Wallet Engine",
  "lessThan": "Menos que",
  "noSpace": "No hay espacio",
  "characters": "caracteres",
  "createTokenError": "Fallo en la creación del emisor de tokens",
  "createTokenSuccess": "Emisor de tokens creado exitosamente",
  "confirmCreateTokenIssue": "¿Seguro que deseas confirmar al emisor de tokens?",
  "pleaseInput": "Por favor introduce",
  "invalidAddrWallet": "Dirección inválida",
  "wallet": "Monedero",
  "tokenName": "NOMBRE DEL TOKEN",
  "tokenSymbol": "SÍMBOLO DEL TOKEN",
  "decimalPoint": "PUNTOS DÉCIMALES",
  "ownerAddress": "DIRECCIÓN DEL PROPIETARIO",
  "tokenLogo": "LOGO DEL TOKEN",
  "selectChain": "seleccionar cadena",
  "tokenMint": "TOKEN MINT",
  "tokenBurn": "TOKEN BURN",
  "powerByCoin98": "Con la ayuda de Coin98 Labs"
}