export default {
  "last7Days": "7 DERNIERS JOURS",
  "fullyDiluted": "Market cap entièrement dilué",
  "liquidityProvider": "Frais des fournisseurs de liquidité",
  "averagePrice": "Prix moyen",
  "priceImpact": "Impact sur le prix",
  "minutes": "minutes",
  "gasSetting": "Paramètre des frais de gas",
  "searchNotFound": "Recherche non trouvée",
  "noWalletFound": "Aucun wallet",
  "tradeSuccess": "Ordre placé avec succès",
  "confirmApprove": "Confirmation d'approbation",
  "claimSwap": "Confirmation de demande",
  "confirmSwap": "Confirmation d'échange",
  "txsFee": "Frais : {{amount}} ~ {{amountUSD}}",
  "pleaseWaitOrder": "Veuillez attendre un moment pour que l'ordre soit effectué",
  "pleaseWaitApprove": "Veuillez attendre un moment pour approbation",
  "approveSuccess": "Approbation effectuée avec succès",
  "pair": "Paire",
  "confirm": "Confirmer",
  "terminal": "Terminal",
  "explorers": "Explorateurs",
  "community": "Communauté",
  "d1": "1D",
  "m1": "1M",
  "w1": "1W",
  "y1": "1Y",
  "full": "Complet",
  "coin98Wallet": "Coin98 Wallet",
  "exchange": "Exchange",
  "invest": "Investir",
  "dashboard": "Tableau de bord",
  "markets": "Marchés",
  "confirmation": "Confirmation",
  "passphrase": "Passphrase",
  "success": "Succès !",
  "category": "catégorie",
  "platform": "Plateforme",
  "createNewWalletSuccessful": "Nouveau wallet créé avec succès !",
  "successfully": "Avec succès",
  "ok": "Ok",
  "error": "Une erreur s'est produite !\nVeuillez réessayer plus tard",
  "create": "Créer",
  "restore": "Restaurer",
  "cancel": "Annuler",
  "receiveAddress": "Adresse de réception",
  "sending": "Envoi",
  "manage": "Gérer",
  "rankMarket": "#Classement {{rank}}",
  "max": "MAX",
  "edited": "Modifié",
  "Error": "Une erreur s'est produite !\nVeuillez réessayer plus tard",
  "search": "Rechercher",
  "goBack": "Retour",
  "searchCurrency": "Rechercher une devise",
  "lendingBorrowing": "Prêter/Emprunter",
  "walletNotFound": "Wallet non trouvé",
  "addRestoreWallet": "Veuillez d'abord ajouter ou restaurer un wallet",
  "wrongPass": "Mot de passe non valide",
  "yieldFarming": "Yield Farming",
  "defiStation": "Station DeFi",
  "analytics": "Analytique",
  "nft": "NFT",
  "governance": "Gouvernance",
  "coin98WalletMess": "Stocker des actifs numériques",
  "terminalMess": "Boîte à outil tout en un",
  "daapMess": "Passerelle DeFi",
  "exchangeMess": "Plateforme de trading",
  "crossChainMess": "Échangez des actifs entre différentes chaines",
  "dashboardMess": "Tout est sous votre contrôle",
  "marketMess": "Suivez les dernières tendances",
  "lendingBorrowingMess": "Recevez des intérêts sur vos actifs",
  "yieldFarmingMess": "Maximisez le rendement sur vos actifs",
  "defiStationMess": "Gagnez de l'argent pendant que vous dormez",
  "portfolioMess": "Suivez la performance de différents actifs",
  "stankingMess": "Verrouillez des actifs pour recevoir des récompenses",
  "governanceMess": "Votez sur les propositions",
  "lunaDex": "Exchange décentralisé développé sur Solana et Serum",
  "connectWallet": "Connecter un wallet",
  "login": "Connexion",
  "en": "Anglais",
  "vi": "Vietnamien",
  "email": "Email",
  "enterEmail": "Veuillez saisir votre adresse email",
  "emailInvalid": "Adresse email non valide",
  "userName": "Nom d'utilisateur",
  "yourUsername": "Votre nom d'utilisateur",
  "displayName": "Nom d'affichage",
  "yourDisplayName": "Votre nom d'affichage",
  "swaps": "Échanges",
  "swap": "Échange",
  "totalValue": "Valeur totale",
  "totalVolume": "Volume total",
  "tokenAmount": "Nombre de tokens",
  "account": "Compte",
  "time": "Délai",
  "infoAlert": "Voici vos informations",
  "infoSuccess": "Création effectuée avec succès",
  "infoError": "Erreur due à ...",
  "approveToken": "Approuver {{nameTokenBuy}}",
  "buyToken": "Acheter {{nameTokenBuy}}",
  "loginSuccess": "Connexion effectuée avec succès",
  "password": "Mot de passe",
  "passInvalid": "Le mot de passe doit contenir au moins 6 caractères avec des chiffres et des lettres",
  "confirmPassword": "Confirmer le mot de passe",
  "passNotMatch": "Le mot de passe ne correspond pas",
  "yourPassword": "Votre mot de passe",
  "inputPassword": "Veuillez saisir un mot de passe",
  "passRequired": "Veuillez saisir votre mot de passe",
  "emailVerificationsCode": "Votre code de vérification email",
  "referralCode": "Code de parrainage",
  "referExistError": "L'identifiant n'existe pas",
  "nameBeenTaken": "Ce nom d'utilisateur est déjà pris",
  "nameAlreadyTaken": "Ce nom est déjà pris",
  "resetPass": "Réinitialiser le mot de passe",
  "usernameRequired": "Le nom d'utilisateur est obligatoire",
  "displaynameRequired": "Le nom d'affichage est obligatoire",
  "confirmPass": "Vous devez confirmer le mot de passe",
  "confirmPassNotMatch": "Le mot de passe confirmé ne correspond pas",
  "youHaveBanned": "Vous avez été banni !",
  "fraudBehaviorDevice": "Vous n'avez pas autorisé l'accès aux informations de l'appareil\nou votre téléphone ne répond pas à nos normes de sécurité",
  "emailRequired": "Email obligatoire",
  "manageWallet": "Gérer les wallets",
  "addWallet": "Ajouter un wallet",
  "restoreWallet": "Restaurer un wallet",
  "connectOtherWallet": "Connecter un autre wallet",
  "send": "Envoyer",
  "receive": "Recevoir",
  "website": "Site web",
  "smartContract": "Smart contract",
  "allTimeLow": "Niveau le plus bas",
  "allTimeHigh": "Niveau le plus haut",
  "high24h": "Prix le plus haut 24H",
  "low24h": "Prix le plus bas 24H",
  "circulatingSupply": "Offre en circulation",
  "maxSupply": "Offre max",
  "marketCap": "Market cap",
  "col24h": "Volume 24H",
  "feeErr": "Votre solde ou les frais de gas ne sont pas suffisants",
  "allWallet": "Tous les wallets",
  "multiChain": "Multi-Chain",
  "ether": "Ether",
  "solana": "Solana",
  "binanceSmart": "Binance Smart Chain",
  "polkadot": "Polkadot",
  "kusama": "Kusama",
  "heco": "Heco",
  "mustAtLeastDot": "Il doit vous rester au moins 1 DOT pour l'envoi",
  "enterAmountToStartTransaction": "Saisissez le montant pour commencer la transaction",
  "amountErr": "Doit être inférieur ou égal au montant disponible",
  "walletName": "Nom du wallet",
  "walletKey": "Clé de wallet",
  "walletKeyPhrase": "Passphrase mnémonique",
  "walletNameExist": "Ce nom de wallet existe déjà",
  "copyDone": "L'adresse {{value}} est copiée",
  "onlySend": "Envoyez uniquement {{symbol}} à cette adresse. Envoyer un autre actif à cette adresse entraînera sa perte",
  "amount": "Montant",
  "recipient": "Destinataire",
  "walletAddress": "Adresse de wallet",
  "confirmInfo": "Confirmer les informations",
  "noData": "Aucune donnée",
  "message": "Message",
  "messageIsOptional": "Le message est facultatif",
  "inputRequired": "Veuillez remplir ce champ",
  "verifyEmail": "Vérifier l'email",
  "comfirmation": "Confirmation",
  "confirmDelete": "Êtes-vous sûr de vouloir supprimer ce wallet ?",
  "passphraseOrPrivateKey": "Passphrase ou clé privée",
  "verySlow": "Très lent",
  "slow": "Lent",
  "fast": "Rapide",
  "superFast": "Très rapide",
  "standard": "Standard",
  "gasWar": "Gas War",
  "starWar": "Star War",
  "tryAgain": "Veuillez réessayer dans quelques minutes",
  "txsFail": "La transaction a échoué",
  "whitePaper": "Livre blanc",
  "timeOutTxs": "Délai de transaction expiré ou non confirmé, veuillez attendre un peu et réessayer.",
  "minimum1Polkadot": "L'adresse du destinataire doit contenir au moins 1 DOT",
  "invalidAddr": "Adresse de destinataire non valide",
  "createAccount": "Créer un compte",
  "createAccountSuccess": "Compte créé avec succès",
  "areYouSureToCreateANewWallet": "Êtes-vous sûr de vouloir créer un nouveau wallet ?",
  "createWallet": "Créer un wallet",
  "phoneRegister": "Le numéro de téléphone n'est utilisé que pour un compte enregistré",
  "clickContinue": "En cliquant sur « Continuer », vous acceptez",
  "teamService": "les conditions de service de Coin98 Wallet",
  "scanToLogin": "Scannez pour vous connecter",
  "forgotPass": "Mot de passe oublié ?",
  "reset": "Réinitialiser",
  "continue": "Continuer",
  "dintRecive": "Vous n'avez pas reçu de code de vérification ?",
  "resend": "Renvoyer",
  "restoreWalletSuccess": "Restore Wallet successfully!",
  "enjoy": "Profitez bien",
  "register": "Enregistrer",
  "sureNewWallet": "Êtes-vous sûr de vouloir créer un nouveau wallet ?",
  "myWallet": "Mon wallet",
  "understandChoose": "J'ai conscience que si je perds ma clé de récupération, je ne serai pas en mesure d'accéder à mon wallet",
  "done": "Terminé",
  "manageContact": "Gérer les contacts",
  "hiddenToken": "Masquer la liste des tokens",
  "setActive": "Définir comme actif",
  "copyAddress": "Copier l'adresse",
  "showQr": "Afficher le code QR",
  "showKey": "Afficher la clé",
  "connectToWallet": "Se connecter à un wallet",
  "chooseWallet": "Choisissez votre wallet",
  "whatIsWallet": "Qu'est-ce qu'un wallet ?",
  "totalBalance": "Solde total",
  "otpWrong": "Code OTP non valide",
  "asset": "Actif",
  "symbol": "Symbole",
  "price": "Prix",
  "balance": "Solde",
  "value": "Valeur",
  "market24": "24h",
  "address": "Adresse",
  "maxSlippage": "Slippage max",
  "termsOfService": "Conditions de service",
  "volume": "Volume",
  "volume24": "Volume 24H",
  "selectWallet": "Sélectionner un wallet",
  "selectedWallet": "Sélectionner un wallet",
  "addressIsCopy": "L'adresse est copiée",
  "orderFunding": "Financement de l'ordre",
  "orderVolume": "Volume des ordres",
  "youSend": "VOUS ENVOYEZ",
  "youReceive": "VOUS RECEVEZ",
  "all": "Tout",
  "high": "Haut",
  "createContact": "Créer un contact",
  "recommend": "Recommander",
  "comingSoon": "Bientôt disponible",
  "connected": "Connecté",
  "installCoin98Wallet": "Installez Coin98 Wallet pour l'utiliser comme wallet de gestion",
  "coin98WalletNotInstalled": "Coin98 Wallet n'a pas été installé",
  "connectCoin98Wallet": "Se connecter à Coin98 Wallet",
  "BTCDominace": "Dominance BTC",
  "ETHDominace": "Dominance ETH",
  "rank": "Classement",
  "onWatchList": "Sur la watchlist {{num}}",
  "token": "Token",
  "day": "jour",
  "month": "mois",
  "week": "semaine",
  "year": "année",
  "custom": "personnalisé",
  "uniswapPrice": "Prix Uniswap",
  "low": "Prix bas",
  "hight": "Prix haut",
  "fullDiluted": "Market cap entièrement dilué",
  "volume24h": "Volume 24h",
  "totalSupply": "Offre totale",
  "viewDetail": "Afficher les détails",
  "from": "De",
  "to": "À",
  "willReceive": "Vous recevrez ~ ",
  "fee": "Frais",
  "balanceTotal": "Solde total",
  "route": "Itinéraire",
  "step": "Étape",
  "finish": "Terminer",
  "swapHistory": "Historique des échanges",
  "coins": "Coins",
  "watchList": "Watchlist",
  "contract": "Contrat",
  "priceChange": "Changement du prix",
  "tradingVolume": "Volume de trading",
  "marketCapRank": "Classement market cap",
  "atHight": "Niveau le plus élevé",
  "atLow": "Niveau le plus bas",
  "sushiPrice": "Statistiques des prix",
  "showRows": "Afficher les rangées",
  "filters": "Filtre",
  "overview": "Aperçu",
  "chart": "Diagramme",
  "cryptoAsset": "Cryptos",
  "historicalData": "Données historiques",
  "tradingView": "Trading View",
  "uniswapChart": "Diagramme Uniswap",
  "name": "Nom",
  "liquidity": "Liquidité",
  "Volume": "Volume",
  "fees": "Frais",
  "topPairs": "Meilleures paires",
  "searchPairToken": "Rechercher paire et token",
  "invalidPassPhrase": "Veuillez vérifier à nouveau votre passphrase ou votre clé privée",
  "needCreate": "Vous devez d'abord créer ou importer un wallet Solana",
  "areYouCreate": "Êtes-vous sûr de vouloir créer un nouveau wallet ?",
  "willBeStored": "Sera stocké sur le wallet {{nameChainWallet}}",
  "feeTransactionMust": "Les frais de transaction doivent être d'au moins {{num}} {{symbol}}",
  "chainNotSupported": "Cette chaine n'est pas encore prise en charge",
  "nameChart": "Diagramme {{symbol}}",
  "areYouLogout": "Êtes-vous sûr de vouloir vous déconnecter ?",
  "vol24h": "Volume 24H",
  "volumeMarket": "Volume / Market cap",
  "resetFilters": "Réinitialiser le filtre",
  "sureToSend": "Êtes-vous sûr de vouloir envoyer {{num}} {{symbol}} vers l'adresse {{address}} ?",
  "sumAddress": "Adresse {{num}}",
  "amountCannotZero": "Le montant ne peut être égal à zéro",
  "multiSend": "Envoi multiple",
  "totalAddress": "Adresse totale",
  "addressEmpty": "L'adresse ne peut rester vide",
  "amountEmpty": "Le montant ne peut rester vide",
  "inputNotRequirements": "La saisie ne répond pas aux exigences",
  "gwei": "Gwei",
  "hi": "Salut",
  "forTransaction": "Pour la transaction",
  "approveConversion": "Approuver la conversion",
  "sendFound": "Envoyer les fonds",
  "waitForConfirm": "En attente des confirmations",
  "rename": "Renommer",
  "questionRename": "Êtes-vous sûr de vouloir renommer le wallet",
  "questionImport": "Êtes-vous sûr de vouloir importer l'adresse et le montant ?",
  "alreadySend": "Déjà envoyé",
  "resendOTP": "OTP renvoyé avec succès",
  "fortmatic": "Fortmatic",
  "coinbaseWallet": "Coinbase Wallet",
  "walletConnect": "Wallet Connect",
  "metaMask": "MetaMask",
  "dapper": "Dapper",
  "lattice": "Lattice",
  "private": "Privé",
  "activeMultiChain": "Activer le wallet multi-chain",
  "activeChain": "Activer le wallet {{chain}}",
  "removeWallet": "Supprimer le wallet {{name}}",
  "noMatchingResult": "Aucun résultat ne correspond",
  "areYouSureSend": "Envoyer {{num}} {{symbol}} <br/> {{address}}",
  "addressAmount": "adresse?montant,adresse?montant",
  "import": "Importer",
  "addressAndAmount": "Adresse et montant",
  "gasPrice": "FRAIS DE GAS",
  "transactionData": "DONNÉES DE LA TRANSACTION",
  "gasLimit": "LIMITE DE GAS",
  "nonce": "NONCE",
  "change24h": "Changement en %",
  "rankTop": "Classement top 100-200",
  "nameRank": "Nom",
  "hour24Trading": "Volume de trading en 24h",
  "lowHight24h": "Prix haut / Prix bas 24H",
  "allTimeLowHigh": "Niveau le plus bas / le plus élevé",
  "unlimitedApproval": "Approbation illimitée",
  "estimateFee": "Estimation des frais",
  "searchCoinOrPasteAnyToken": "Rechercher un coin ou copier/coller un token",
  "transactionDeadline": "Délai de transaction",
  "owners": "Propriétaires",
  "votingRate": "Taux de vote",
  "withdraw": "Retirer",
  "update": "Actualiser",
  "approved": "Approuvé",
  "waiting": "En attente",
  "totalFound": "Total des fonds",
  "totalOwner": "Total des propriétaires",
  "awaitingApprove": "Approbation en attente",
  "voteRate": "Taux de vote",
  "owner": "Propriétaire",
  "change": "Changement",
  "ownersAddress": "Adresse des propriétaires",
  "votingPower": "Pouvoir du vote",
  "type": "Type",
  "date": "Date",
  "status": "Statut",
  "process": "Processus",
  "transactionId": "ID de la transaction",
  "creator": "Créateur",
  "wellcome": "Bienvenue sur",
  "multisig": "Multisig Wallet",
  "createNew": "Créer nouveau",
  "addOwner": "Ajouter un propriétaire",
  "addVoteRate": "Ajouter un taux de vote",
  "multisigWalletName": "Nom du wallet multisignature",
  "c98Private": "Fonds privé C98",
  "successSent": "Envoyé avec succès",
  "removeOwner": "Supprimer le propriétaire",
  "newVoteRate": "Nouveau taux de vote",
  "newVotePower": "Nouveau pouvoir de vote",
  "poweredByCoin98": "Alimenté par Coin98 Wallet Engine",
  "lessThan": "Moins de",
  "noSpace": "Sans espace",
  "characters": "caractères",
  "createTokenError": "Erreur d'émetteur lors de la création du token",
  "createTokenSuccess": "Token créé avec succès",
  "confirmCreateTokenIssue": "Êtes-vous sûr de vouloir confirmer l'émetteur du token ?",
  "pleaseInput": "Veuillez saisir",
  "invalidAddrWallet": "Adresse non valide",
  "wallet": "Wallet",
  "tokenName": "NOM DU TOKEN",
  "tokenSymbol": "SYMBOLE DU TOKEN",
  "decimalPoint": "POINTS DE DÉCIMALE",
  "ownerAddress": "ADRESSE DU PROPRIÉTAIRE",
  "tokenLogo": "LOGO DU TOKEN",
  "selectChain": "sélectionner la chaine",
  "tokenMint": "TOKEN MINT",
  "tokenBurn": "TOKEN BURN",
  "powerByCoin98": "Alimenté par Coin98 Labs"
}