export default {
  "last7Days": "7 HARI TERAKHIR",
  "fullyDiluted": "Kap Pasar Fully Diluted",
  "liquidityProvider": "Biaya Penyedia Likuiditas",
  "averagePrice": "Harga Rata-Rata",
  "priceImpact": "Impak Harga",
  "minutes": "menit",
  "gasSetting": "Pengaturan Gas",
  "searchNotFound": "Pencarian Tidak Ditemukan",
  "noWalletFound": "Tidak ada Dompet",
  "tradeSuccess": "Order berhasil",
  "confirmApprove": "Konfirmasi persetujuan",
  "claimSwap": "Konfirmasi Klaim",
  "confirmSwap": "Konfirmasi Tukar",
  "txsFee": "Biaya: {{amount}} ~ {{amountUSD}}",
  "pleaseWaitOrder": "Harap tunggu sebentar untuk penyelesaian order",
  "pleaseWaitApprove": "Harap tunggu sebentar untuk persetujuan",
  "approveSuccess": "Persetujuan berhasil",
  "pair": "Pasangan",
  "confirm": "Konfirmasi",
  "terminal": "Terminal",
  "explorers": "Penjelajah",
  "community": "Komunitas",
  "d1": "1 Hari",
  "m1": "1 Bulan",
  "w1": "1 Minggu",
  "y1": "1 Tahun",
  "full": "Penuh",
  "coin98Wallet": "Dompet Coin98",
  "exchange": "Penukaran",
  "invest": "Investasi",
  "dashboard": "Dasbor",
  "markets": "Pasar",
  "confirmation": "Konfirmasi",
  "passphrase": "Frasa Sandi",
  "success": "Berhasil!",
  "category": "kategori",
  "platform": "Platform",
  "createNewWalletSuccessful": "Pembuatan dompet baru berhasil!",
  "successfully": "Berhasil",
  "ok": "Oke",
  "error": "Ada yang salah!\nCoba lagi nanti",
  "create": "Buat",
  "restore": "Pulihkan",
  "cancel": "Batal",
  "receiveAddress": "Terima Alamat",
  "sending": "Mengirim",
  "manage": "Kelola",
  "rankMarket": "#Peringkat {{rank}}",
  "max": "MAKS",
  "edited": "Diedit",
  "Error": "Eror!",
  "search": "Cari",
  "goBack": "Kembali",
  "searchCurrency": "Cari Mata Uang",
  "lendingBorrowing": "Pinjamkan/Pinjam",
  "walletNotFound": "Dompet Tidak Ditemukan",
  "addRestoreWallet": "Tambah atau pulihkan dompet lebih dulu",
  "wrongPass": "Kata sandi tidak valid",
  "yieldFarming": "Yield Farming",
  "defiStation": "DeFi Station",
  "analytics": "Analitik",
  "nft": "NFT",
  "governance": "Pimpinan",
  "coin98WalletMess": "Simpan Aset Digital",
  "terminalMess": "Kotak Segala Ada",
  "daapMess": "Gerbang DeFi",
  "exchangeMess": "Platform Perdagangan",
  "crossChainMess": "Tukar aset di berbagai chain",
  "dashboardMess": "Semua di bawah kendali Anda",
  "marketMess": "Ikuti tren terbaru",
  "lendingBorrowingMess": "Dapatkan bunga atas aset",
  "yieldFarmingMess": "Maksimalkan yield atas aset",
  "defiStationMess": "Dapatkan uang sambil tidur",
  "portfolioMess": "Lacak performa aset",
  "stankingMess": "Kunci aset untuk menerima hadiah",
  "governanceMess": "Vote pada proposal",
  "lunaDex": "Penukaran desentralisasi yang dibangun pada Solana dan Serum",
  "connectWallet": "Hubungkan Dompet",
  "login": "Login",
  "en": "Inggris",
  "vi": "Vietnam",
  "email": "Email",
  "enterEmail": "Masukkan email Anda",
  "emailInvalid": "Alamat email tidak valid",
  "userName": "Nama Pengguna",
  "yourUsername": "Nama Pengguna Anda",
  "displayName": "Nama Displai",
  "yourDisplayName": "Nama Displai Anda",
  "swaps": "Tukar",
  "swap": "Tukar",
  "totalValue": "Nilai Total",
  "totalVolume": "Volume Total",
  "tokenAmount": "Jumlah Token",
  "account": "Akun",
  "time": "Waktu",
  "infoAlert": "Ini Info Anda",
  "infoSuccess": "Pembuatan sesuatu berhasil",
  "infoError": "Eror karena ...",
  "approveToken": "Setujui {{nameTokenBuy}}",
  "buyToken": "Beli {{nameTokenBuy}}",
  "loginSuccess": "Login Berhasil",
  "password": "Kata Sandi",
  "passInvalid": "Kata sandi minimal harus 6 karakter dengan angka dan huruf",
  "confirmPassword": "Konfirmasi Kata Sandi",
  "passNotMatch": "Kata sandi tidak sesuai",
  "yourPassword": "Kata Sandi Anda",
  "inputPassword": "Masukkan kata sandi",
  "passRequired": "masukkan kata sandi Anda",
  "emailVerificationsCode": "Kode verifikasi email Anda",
  "referralCode": "Kode referensi",
  "referExistError": "ID tidak ada",
  "nameBeenTaken": "Nama pengguna Anda sudah dipakai",
  "nameAlreadyTaken": "Nama ini sudah dipakai",
  "resetPass": "Reset Kata Sandi Baru",
  "usernameRequired": "Nama pengguna diperlukan",
  "displaynameRequired": "Nama displai diperlukan",
  "confirmPass": "Konfirmasi kata sandi diperlukan",
  "confirmPassNotMatch": "Konfirmasi kata sandi tidak sesuai",
  "youHaveBanned": "Anda sudah dilarang!",
  "fraudBehaviorDevice": "Anda tidak mengizinkan akses ke informasi peranti\n  Atau telepon Anda tidak memenuhi standar keamanan kami",
  "emailRequired": "Email diperlukan",
  "manageWallet": "Kelola Dompet",
  "addWallet": "Tambah Dompet",
  "restoreWallet": "Pulihkan Dompet",
  "connectOtherWallet": "Hubungkan Dompet lain",
  "send": "Kirim",
  "receive": "Terima",
  "website": "Situs Web",
  "smartContract": "Kontrak Cerdas",
  "allTimeLow": "Rendah Sepanjang Masa",
  "allTimeHigh": "Tinggi Sepanjang Masa",
  "high24h": "Tinggi 24 Jam",
  "low24h": "Rendah 24 Jam",
  "circulatingSupply": "Pasokan Beredar",
  "maxSupply": "Pasokan Maks",
  "marketCap": "Kap Pasar",
  "col24h": "Vol 24 Jam",
  "feeErr": "Saldo atau biaya gas tidak cukup",
  "allWallet": "Semua Dompet",
  "multiChain": "Multi-Chain",
  "ether": "Ether",
  "solana": "Solana",
  "binanceSmart": "Binance Smart",
  "polkadot": "Polkadot",
  "kusama": "Kusama",
  "heco": "Heco",
  "mustAtLeastDot": "Anda harus memiliki minimal 1 DOT untuk mengirim",
  "enterAmountToStartTransaction": "Masukkan jumlah untuk memulai transaksi",
  "amountErr": "Harus kurang dari atau setara dengan jumlah yang bisa dikeluarkan",
  "walletName": "Nama Dompet",
  "walletKey": "Kunci Dompet",
  "walletKeyPhrase": "Frasa Sandi Mnemonik",
  "walletNameExist": "Nama Dompet sudah ada",
  "copyDone": "Alamat {{value}} disalin",
  "onlySend": "Kirim {{symbol}} saja ke alamat ini. Mengirim aset lain ke alamat ini akan mengakibatkan hilangnya aset",
  "amount": "Jumlah",
  "recipient": "Penerima",
  "walletAddress": "Alamat Dompet",
  "confirmInfo": "Konfirmasi Info",
  "noData": "Tak Ada Data",
  "message": "Pesan",
  "messageIsOptional": "Pesan Opsional",
  "inputRequired": "Harap isi bidang ini",
  "verifyEmail": "Verifikasi Email",
  "comfirmation": "Konfirmasi",
  "confirmDelete": "Anda yakin ingin menghapus dompet ini?",
  "passphraseOrPrivateKey": "Frasa Sandi atau Kunci Privat?",
  "verySlow": "Sangat Lambat",
  "slow": "Lambat",
  "fast": "Cepat",
  "superFast": "Super Cepat",
  "standard": "Standar",
  "gasWar": "Gas War",
  "starWar": "Star War",
  "tryAgain": "Coba lagi dalam beberapa menit",
  "txsFail": "Transaksi gagal",
  "whitePaper": "Laporan",
  "timeOutTxs": "Waktu transaksi habis atau tidak dikonfirmasi, tunggu sebentar dan coba lagi.",
  "minimum1Polkadot": "Alamat penerima harus memiliki lebih dari 1 DOT",
  "invalidAddr": "Alamat penerima tidak valid",
  "createAccount": "Buat Akun",
  "createAccountSuccess": "Pembuatan akun berhasil",
  "areYouSureToCreateANewWallet": "Anda yakin ingin membuat dompet baru?",
  "createWallet": "Buat Dompet",
  "phoneRegister": "Nomor telepon hanya digunakan untuk akun terdaftar",
  "clickContinue": "Dengan mengeklik \"Lanjut\", Anda menyetujui",
  "teamService": "Ketentuan Layanan Dompet Coin98",
  "scanToLogin": "Pindai untuk login",
  "forgotPass": "Lupa kata sandi?",
  "reset": "Reset",
  "continue": "Lanjut",
  "dintRecive": "Tidak menerima kode verifikasi?",
  "resend": "Kirim Ulang",
  "restoreWalletSuccess": "Pemulihan Dompet berhasil!",
  "enjoy": "Nikmati",
  "register": "Daftar",
  "sureNewWallet": "Anda yakin ingin membuat dompet baru?",
  "myWallet": "Dompetku",
  "understandChoose": "Saya mengerti jika saya kehilangan kunci, saya tidak akan bisa mengakses dompet",
  "done": "Selesai",
  "manageContact": "Kelola Kontak",
  "hiddenToken": "Daftar Token Tersembunyi",
  "setActive": "Set Aktif",
  "copyAddress": "Salin Alamat",
  "showQr": "Tampilkan Kode QR",
  "showKey": "Tampilkan Info Kunci",
  "connectToWallet": "Hubungkan ke Dompet",
  "chooseWallet": "Pilih dompet Anda",
  "whatIsWallet": "Apa yang dimaksud dompet?",
  "totalBalance": "Saldo Total",
  "otpWrong": "Kode OTP tidak valid",
  "asset": "Aset",
  "symbol": "Simbol",
  "price": "Harga",
  "balance": "Saldo",
  "value": "Nilai",
  "market24": "24 Jam",
  "address": "Alamat",
  "maxSlippage": "Selip Maks",
  "termsOfService": "Ketentuan Layanan",
  "volume": "Volume",
  "volume24": "Volume 24 Jam",
  "selectWallet": "Pilih Dompet",
  "selectedWallet": "Pilih Dompet",
  "addressIsCopy": "Alamat disalin",
  "orderFunding": "Pendanaan Order",
  "orderVolume": "Volume Order",
  "youSend": "ANDA MENGIRIM",
  "youReceive": "ANDA MENERIMA",
  "all": "Semua",
  "high": "Tinggi",
  "createContact": "Buat Kontak",
  "recommend": "Rekomendasi",
  "comingSoon": "Segera",
  "connected": "Terhubung",
  "installCoin98Wallet": "Instal Coin98 untuk pengelolaan dompet",
  "coin98WalletNotInstalled": "Dompet Coin98 belum diinstal",
  "connectCoin98Wallet": "Hubungkan ke Dompet Coin98",
  "BTCDominace": "Dominansi BTC",
  "ETHDominace": "Dominansi ETH",
  "rank": "Peringkat",
  "onWatchList": "Pada {{num}} Daftar Pantauan",
  "token": "Token",
  "day": "hari",
  "month": "bulan",
  "week": "minggu",
  "year": "tahun",
  "custom": "kustom",
  "uniswapPrice": "Harga Uniswap",
  "low": "Rendah",
  "hight": "Tinggi",
  "fullDiluted": "Volume 24 Jam",
  "volume24h": "Volume 24 Jam",
  "totalSupply": "Pasokan Total",
  "viewDetail": "Lihat Detail",
  "from": "Dari",
  "to": "sampai",
  "willReceive": "Anda akan menerima ~",
  "fee": "Biaya",
  "balanceTotal": "Saldo total",
  "route": "Rute",
  "step": "Langkah",
  "finish": "Selesai",
  "swapHistory": "Riwayat Tukar",
  "coins": "Koin",
  "watchList": "Daftar Pantauan",
  "contract": "Kontrak",
  "priceChange": "Perubahan Harga",
  "tradingVolume": "Volume Perdagangan",
  "marketCapRank": "Peringkat Kap Pasar",
  "atHight": "Semua - Waktu Tinggi",
  "atLow": "Semua - Waktu Rendah",
  "sushiPrice": " Statistik Harga",
  "showRows": "Tampilkan baris",
  "filters": "Filter",
  "overview": "Ringkasan",
  "chart": "Bagan",
  "cryptoAsset": "Crypto",
  "historicalData": "Data Historis",
  "tradingView": "Tampilan Perdagangan",
  "uniswapChart": "Bagan Uniswap",
  "name": "nama",
  "liquidity": "Likuiditas",
  "Volume": "Volume",
  "fees": "biaya",
  "topPairs": "Pasangan Top",
  "searchPairToken": "Cari pasangan dan token",
  "invalidPassPhrase": "Periksa lagi Frasa Sandi atau Kunci Privat Anda",
  "needCreate": "Harus membuat atau mengimpor Dompet Solana lebih dulu",
  "areYouCreate": "Anda yakin ingin membuat dompet baru?",
  "willBeStored": "Akan disimpan di Dompet {{nameChainWallet}}",
  "feeTransactionMust": "Biaya transaksi setidaknya harus {{num}} {{symbol}}",
  "chainNotSupported": "Chain belum didukung",
  "nameChart": "Bagan {{symbol}}",
  "areYouLogout": "Anda yakin mau keluar?",
  "vol24h": "Vol 24 Jam",
  "volumeMarket": "Volume / Kap Pasar",
  "resetFilters": "Reset Filter",
  "sureToSend": "Anda yakin ingin mengirim {{num}} {{symbol}} ke alamat {{address}} ?",
  "sumAddress": "{{num}} Alamat",
  "amountCannotZero": "Jumlah tidak boleh nol",
  "multiSend": "Kirim beberapa",
  "totalAddress": "Alamat Total",
  "addressEmpty": "Alamat tidak boleh kosong",
  "amountEmpty": "Jumlah tidak boleh kosong",
  "inputNotRequirements": "Input tidak memenuhi syarat",
  "gwei": "Gwei",
  "hi": "Hai",
  "forTransaction": "Untuk Transaksi",
  "approveConversion": "Setujui Konversi",
  "sendFound": "Kirim Dana",
  "waitForConfirm": "Tunggu Konfirmasi",
  "rename": "Ganti Nama",
  "questionRename": "Apa Anda yakin ingin mengganti nama dompet",
  "questionImport": "Apa Anda yakin ingin mengimpor alamat dan jumlah",
  "alreadySend": "Sudah dikirim",
  "resendOTP": "Pengiriman Ulang OTP berhasil",
  "fortmatic": "Fortmatic",
  "coinbaseWallet": "Dompet Coinbase",
  "walletConnect": "Wallet Connect",
  "metaMask": "MetaMask",
  "dapper": "Dapper",
  "lattice": "Lattice",
  "private": "Privat",
  "activeMultiChain": "Aktifkan Dompet Multi-Chain",
  "activeChain": "Aktifkan Dompet {{chain}}",
  "removeWallet": "Hapus Dompet {{name}}",
  "noMatchingResult": "Tidak ada hasil yang sesuai",
  "areYouSureSend": "Kirim {{num}} {{symbol}} <br/> {{address}}",
  "addressAmount": "alamat?jumlah,alamat?jumlah",
  "import": "Impor",
  "addressAndAmount": "Alamat dan jumlah",
  "gasPrice": "HARGA GAS",
  "transactionData": "DATA TRANSAKSI",
  "gasLimit": "BATAS GAS",
  "nonce": "NONCE",
  "change24h": "% Perubahan",
  "rankTop": "Peringkat Top 100-200",
  "nameRank": "Nama",
  "hour24Trading": "Vol Perdagangan 24 Jam",
  "lowHight24h": "Rendah / Tinggi 24 Jam",
  "allTimeLowHigh": "Rendah / Tinggi Sepanjang Masa",
  "unlimitedApproval": "Persetujuan Tanpa Batas",
  "estimateFee": "Estimasi Biaya",
  "searchCoinOrPasteAnyToken": "Cari koin atau rekatkan token",
  "transactionDeadline": "Tenggat Transaksi",
  "owners": "Pemilik",
  "votingRate": "Nilai Voting",
  "withdraw": "Tarik",
  "update": "Perbarui",
  "approved": "Disetujui",
  "waiting": "Menunggu",
  "totalFound": "Temuan Total",
  "totalOwner": "Pemilik Total",
  "awaitingApprove": "Menunggu Persetujuan",
  "voteRate": "Nilai Voting",
  "owner": "Pemilik",
  "change": "Ganti",
  "ownersAddress": "Alamat Pemilik",
  "votingPower": "Kekuatan Voting",
  "type": "Tipe",
  "date": "Tanggal",
  "status": "Status",
  "process": "Proses",
  "transactionId": "ID transaksi",
  "creator": "Kreator",
  "wellcome": "Selamat datang di",
  "multisig": "Dompet Multisig",
  "createNew": "Buat Baru",
  "addOwner": "Tambah Pemilik",
  "addVoteRate": "Tambah Nilai Voting",
  "multisigWalletName": "Nama Dompet Multisignature",
  "c98Private": "Dana Pribadi C98",
  "successSent": "Berhasil Dikirim",
  "removeOwner": "Hapus Pemilik",
  "newVoteRate": "Nilai Voting Baru",
  "newVotePower": "Kekuatan Voting Baru",
  "poweredByCoin98": "Didukung oleh Coin98 Wallet Engine",
  "lessThan": "Kurang dari",
  "noSpace": "Tanpa spasi",
  "characters": "karakter",
  "createTokenError": "Buat Penerbit Token Eror",
  "createTokenSuccess": "Buat Penerbit Token Berhasil",
  "confirmCreateTokenIssue": "Anda yakin ingin mengonfirmasi Penerbit Token?",
  "pleaseInput": "Silakan Masukkan",
  "invalidAddrWallet": "Alamat tidak valid",
  "wallet": "Dompet",
  "tokenName": "NAMA TOKEN",
  "tokenSymbol": "SIMBOL TOKEN",
  "decimalPoint": "TITIK DESIMAL",
  "ownerAddress": "ALAMAT PEMILIK",
  "tokenLogo": "LOGO TOKEN",
  "selectChain": "pilih chain",
  "tokenMint": "TOKEN MINT",
  "tokenBurn": "TOKEN BURN",
  "powerByCoin98": "Didukung oleh Coin98 Labs"
}