export default {
  "last7Days": "７日",
  "fullyDiluted": "完全希薄化の時価総額",
  "liquidityProvider": "流動性供給の手数料",
  "averagePrice": "平均価格",
  "priceImpact": "Price Impact",
  "minutes": "分",
  "gasSetting": "ガス設定",
  "searchNotFound": "見つかりませんでした",
  "noWalletFound": "ウォレットをまだ接続していません",
  "tradeSuccess": "注文が成功しました",
  "confirmApprove": "取引承認",
  "claimSwap": "スワップ確認",
  "confirmSwap": "スワップ確認",
  "txsFee": "手数料: {{amount}} ~ {{amountUSD}}",
  "pleaseWaitOrder": "注文が完了するまでしばらくお待ちください",
  "pleaseWaitApprove": "承認されるまでしばらくお待ちください",
  "approveSuccess": "承認が成功しました",
  "pair": "ペア",
  "confirm": "確認",
  "terminal": "ターミナル",
  "explorers": "エクスプローラー",
  "community": "コミュニティ",
  "d1": "1D",
  "m1": "1M",
  "w1": "1W",
  "y1": "1Y",
  "full": "フル",
  "coin98Wallet": "Coin98ウォレット",
  "exchange": "取引",
  "invest": "投資",
  "dashboard": "ダッシュボード",
  "markets": "市場",
  "confirmation": "確認",
  "passphrase": "パスフレーズ",
  "success": "成功！",
  "category": "項目",
  "platform": "プラットフォーム",
  "createNewWalletSuccessful": "新しいウォレット作成が成功しました！",
  "successfully": "成功",
  "ok": "Ok",
  "error": "エラーが発生しました!\n  あとでやり直してください",
  "create": "新作",
  "restore": "復元",
  "cancel": "キャンセル",
  "receiveAddress": "受取アドレス",
  "sending": "送信中",
  "manage": "管理",
  "rankMarket": "#ランク {{rank}}",
  "max": "MAX",
  "edited": "編集済",
  "Error": "エラー！",
  "search": "検索",
  "goBack": "戻り",
  "searchCurrency": "暗号通貨捜索",
  "lendingBorrowing": "借り/貸し",
  "walletNotFound": "ウォレットが見つかりません",
  "addRestoreWallet": "最初にウォレットを追加または復元してください",
  "wrongPass": "パスワードが無効です",
  "yieldFarming": "Yield Farming",
  "defiStation": "DeFi Station",
  "analytics": "分析",
  "nft": "NFT",
  "governance": "統治",
  "coin98WalletMess": "デジタル資産を保持します",
  "terminalMess": "全能ツールボックス",
  "daapMess": "DeFi Gateway",
  "exchangeMess": "取引プラットフォーム",
  "crossChainMess": "異なるブロックチェーン間でトークンをスワップします",
  "dashboardMess": "心配御無用",
  "marketMess": "最新のトレンドをフォローします",
  "lendingBorrowingMess": "デジタル資産から利息を獲得します",
  "yieldFarmingMess": "デジタル資産から収益を最大化します",
  "defiStationMess": "寝ながら稼ぎます",
  "portfolioMess": "デジタル資産のパフォーマンスを追跡する",
  "stankingMess": "リワードをもらうためにデジタル資産をロックします",
  "governanceMess": "提案に投票します",
  "lunaDex": "分散型取引所がソラナとセラムの上に構築されます",
  "connectWallet": "ウォレットを接続します",
  "login": "ログイン",
  "en": "　英語",
  "vi": " ベトナム語",
  "email": "メール",
  "enterEmail": "お客様のメールアドレスを入力してください",
  "emailInvalid": "メールアドレスは無効です",
  "userName": "ユーザー名",
  "yourUsername": "お客様のユーザー名",
  "displayName": "表示名",
  "yourDisplayName": "お客様の表示名",
  "swaps": "スワップ",
  "swap": "スワップ",
  "totalValue": "総価値",
  "totalVolume": "総出来高",
  "tokenAmount": "トークン数",
  "account": "アカウント",
  "time": "時間",
  "infoAlert": "こちらはお客様の情報です",
  "infoSuccess": "作成が成功しました",
  "infoError": "エラー原因は...",
  "approveToken": "{{nameTokenBuy}}承認",
  "buyToken": "{{nameTokenBuy}}購入",
  "loginSuccess": "ログインが成功しました",
  "password": "パスワード",
  "passInvalid": "パスワードは6文字以上で、数字と文字を含む必要があります",
  "confirmPassword": "パスワード確認",
  "passNotMatch": "パスワードが一致しません",
  "yourPassword": "お客様のパスワード",
  "inputPassword": "パスワードを入力してください",
  "passRequired": "パスワードを入力してください",
  "emailVerificationsCode": "メール確認コード",
  "referralCode": "紹介コード",
  "referExistError": "ID は存在しません",
  "nameBeenTaken": "このユーザー名は既に使われました",
  "nameAlreadyTaken": "この名前は既に使われました",
  "resetPass": "新しいパスワードを設定します",
  "usernameRequired": "ユーザー名が必要です",
  "displaynameRequired": "表示名が必要です",
  "confirmPass": "パスワード確認が必要です",
  "confirmPassNotMatch": "パスワードが一致しません",
  "youHaveBanned": "お客様は禁止されました！",
  "fraudBehaviorDevice": "デバイス情報へのアクセスを許可していません\n又は、お客様の携帯電話が当社の安全基準を満たしていません",
  "emailRequired": "メールアドレスが必要です",
  "manageWallet": "ウォレット管理",
  "addWallet": "ウォレット追加",
  "restoreWallet": "ウォレット復元",
  "connectOtherWallet": "他のウォレットを接続します",
  "send": "送信",
  "receive": "受取",
  "website": "ウェブサイト",
  "smartContract": "スマートコントラクト",
  "allTimeLow": "史上最低",
  "allTimeHigh": "史上最高",
  "high24h": "24時間最高",
  "low24h": "24時間最低",
  "circulatingSupply": "循環供給",
  "maxSupply": "最大供給",
  "marketCap": "時価総額",
  "col24h": "24時間取引高",
  "feeErr": "残高又はガス代が不足です",
  "allWallet": "全部のウォレット",
  "multiChain": "Multi-Chain",
  "ether": "Ether",
  "solana": "Solana",
  "binanceSmart": "Binance Smart",
  "polkadot": "Polkadot",
  "kusama": "Kusama",
  "heco": "Heco",
  "mustAtLeastDot": "送付のため、最低残高が1 DOT必要です",
  "enterAmountToStartTransaction": "取引のために数量を入力してください",
  "amountErr": "使用可能な金額以下である必要があります",
  "walletName": "ウォレット名",
  "walletKey": "ウォレットキー",
  "walletKeyPhrase": " ニーモニックフレーズ",
  "walletNameExist": "このウォレット名が既に使われていました",
  "copyDone": "{{value}} アドレスはコピーされました",
  "onlySend": "このアドレスは{{symbol}}のみをもらいます。トークンを間違って、送ったら、無くなります",
  "amount": "数量",
  "recipient": "受取ウォレット",
  "walletAddress": "ウォレットアドレス",
  "confirmInfo": "情報確認",
  "noData": "データなし",
  "message": "メッセージ",
  "messageIsOptional": "メッセージは任意入力です",
  "inputRequired": "ご記入ください",
  "verifyEmail": "メール検証",
  "comfirmation": "確認",
  "confirmDelete": "このウォレットを削除してもよろしいですか？",
  "passphraseOrPrivateKey": "パスフレーズと秘密鍵",
  "verySlow": "とても遅い",
  "slow": "遅い",
  "fast": "速い",
  "superFast": "非常速い",
  "standard": "普通",
  "gasWar": "ガス代戦争",
  "starWar": "スター・ウォー",
  "tryAgain": "あとでやり直してください",
  "txsFail": "取引が失敗しました",
  "whitePaper": "ホワイトペーパー",
  "timeOutTxs": "取引待ち時間がもう終わります。又は確認されていません。しばらく待ってから、もう一度試してください",
  "minimum1Polkadot": "受取アドレスは1 DOT以上要ります",
  "invalidAddr": "受取アドレスが無効です",
  "createAccount": "アカウント作成",
  "createAccountSuccess": "アカウント作成が成功しました",
  "areYouSureToCreateANewWallet": "新しいウォレットを作成してもよろしいですか？",
  "createWallet": "ウォレット作成",
  "phoneRegister": "電話番号は登録済みのアカウントにのみ使用されます",
  "clickContinue": "「継続」をクリックしたら、同意します",
  "teamService": "Coin98ウォレットの利用契約",
  "scanToLogin": "スキャンしたらログインします",
  "forgotPass": "パスワードを忘れますか？",
  "reset": "リセット",
  "continue": "継続",
  "dintRecive": "確認コードをまだもらっていませんか？",
  "resend": "再送",
  "restoreWalletSuccess": "ウオレット復元が成功しました！",
  "enjoy": "楽しみます",
  "register": "登録",
  "sureNewWallet": "新しいウォレットを作成してもよろしいですか？",
  "myWallet": "私のウォレット",
  "understandChoose": "リカバリキーを紛失すると、ウォレットにアクセスできなくなることを理解しました",
  "done": "完了",
  "manageContact": "連絡先管理",
  "hiddenToken": "非表示トークンリスト",
  "setActive": "アクティブ化します",
  "copyAddress": "アドレスをコピーします",
  "showQr": "QRコードを表示します",
  "showKey": "キーを表示します",
  "connectToWallet": "ウォレットを接続します",
  "chooseWallet": "ウォレットを選びます",
  "whatIsWallet": "何のウォレットですか？",
  "totalBalance": "残高合計",
  "otpWrong": "OTPコードが無効です",
  "asset": "資産",
  "symbol": "信号",
  "price": "価格",
  "balance": "残高",
  "value": "価値",
  "market24": "24時間",
  "address": "アドレス",
  "maxSlippage": "スリッページMax",
  "termsOfService": "利用契約",
  "volume": "出来高",
  "volume24": "24時間取引高",
  "selectWallet": "ウォレット選択",
  "selectedWallet": "選んだウォレット",
  "addressIsCopy": "アドレスをコピーしました",
  "orderFunding": "Order Funding",
  "orderVolume": "注文出来高",
  "youSend": "送付",
  "youReceive": "お客様はもらいます",
  "all": "全部",
  "high": "高い",
  "createContact": "連絡先作成",
  "recommend": "ススメ",
  "comingSoon": "近日公開",
  "connected": "連絡先",
  "installCoin98Wallet": "管理のため、 Coin98ウォレットをインストールします",
  "coin98WalletNotInstalled": "Coin98ウォレットをまだインストールしていません",
  "connectCoin98Wallet": "Coin98ウォレット",
  "BTCDominace": "BTC ドミナンス",
  "ETHDominace": "ETH ドミナンス",
  "rank": "ラック",
  "onWatchList": "ウォッチリストの{{num}}",
  "token": "トークン",
  "day": "日",
  "month": "月",
  "week": "週",
  "year": "年",
  "custom": "任意",
  "uniswapPrice": "Uniswap価格",
  "low": "低",
  "hight": "高",
  "fullDiluted": "完全希薄化の時価総額",
  "volume24h": "24時間取引高",
  "totalSupply": "総供給",
  "viewDetail": "詳細",
  "from": "から",
  "to": "まで",
  "willReceive": "獲得は～",
  "fee": "手数料",
  "balanceTotal": "残高合計",
  "route": "Route",
  "step": "ステップ",
  "finish": "終わり",
  "swapHistory": "スワップ来歴",
  "coins": "コイン",
  "watchList": "ウォッチリスト",
  "contract": "コントラクト",
  "priceChange": "価格変更",
  "tradingVolume": "取引高",
  "marketCapRank": "時価総額ランク",
  "atHight": "史上最高",
  "atLow": "史上最低",
  "sushiPrice": " 価格統計",
  "showRows": "行表示",
  "filters": "フィルタ",
  "overview": "概要",
  "chart": "チャート",
  "cryptoAsset": "クリップト",
  "historicalData": "来歴データ",
  "tradingView": "Trading View",
  "uniswapChart": "Uniswapチャート",
  "name": "名前",
  "liquidity": "流動性",
  "Volume": "出来高",
  "fees": "手数料",
  "topPairs": "ペアトップ",
  "searchPairToken": "ペアとトークンを検索します",
  "invalidPassPhrase": "パスフレーズと秘密鍵を再度確認してください！",
  "needCreate": "最初にソラナウォレットを追加または復元してください",
  "areYouCreate": "新しいウォレットを作成してもよろしいですか？",
  "willBeStored": "{{nameChainWallet}} ウォレットに保持します",
  "feeTransactionMust": "取引手数料は最低{{num}} {{symbol}}必要です",
  "chainNotSupported": "チェーンはまだサポートされていません",
  "nameChart": "{{symbol}} チャート",
  "areYouLogout": "ログアウトしてもよろしいですか？",
  "vol24h": "24時間取引高",
  "volumeMarket": "出来高 / 時価総額",
  "resetFilters": "フィルタリセット",
  "sureToSend": " {{address}} アドレスに {{num}} {{symbol}} 送ってもよろしいですか？",
  "sumAddress": "{{num}} アドレス",
  "amountCannotZero": "数量は0にしてはいけません",
  "multiSend": "Multi-Send",
  "totalAddress": "ウォレット合計",
  "addressEmpty": "アドレスを空けてはいけません",
  "amountEmpty": "数量を空けてはいけません",
  "inputNotRequirements": "入力内容は要求を満たしません",
  "gwei": "Gwei",
  "hi": "こんにちは",
  "forTransaction": "取引用",
  "approveConversion": "転換承認",
  "sendFound": "送付",
  "waitForConfirm": "確認待ち",
  "rename": "名前変更",
  "questionRename": "ウォレット名を変更してもよろしいですか？",
  "questionImport": "アドレスと数量をもう一度確認してください",
  "alreadySend": "送付済み",
  "resendOTP": "OTPコード再送が成功しました",
  "fortmatic": "Fortmatic",
  "coinbaseWallet": "Coinbaseウォレット ",
  "walletConnect": "Wallet Connect",
  "metaMask": "MetaMask",
  "dapper": "Dapper",
  "lattice": "Lattice",
  "private": "Private",
  "activeMultiChain": "マルチチェーンウォレットをアクティブ化します",
  "activeChain": "{{chain}} ウォレットをアクティブ化します",
  "removeWallet": "{{name}} ウォレットを削除します",
  "noMatchingResult": "見つけません",
  "areYouSureSend": "送付{{num}} {{symbol}} <br/> {{address}}",
  "addressAmount": "アドレス？数量,アドレス？数量",
  "import": "Import",
  "addressAndAmount": "アドレスと数量",
  "gasPrice": "ガス代",
  "transactionData": "取引データ",
  "gasLimit": "ガス限界",
  "nonce": "NONCE",
  "change24h": "% 変動",
  "rankTop": "ランクトップ100-200",
  "nameRank": "名前",
  "hour24Trading": "24時間取引高",
  "lowHight24h": "24時間 低 / 高",
  "allTimeLowHigh": "史上最低　/ 最高",
  "unlimitedApproval": "無制限承認",
  "estimateFee": "予算手数料",
  "searchCoinOrPasteAnyToken": "コインを検索します。又はトークンを貼り付けます",
  "transactionDeadline": "取引締め切り",
  "owners": "オーナー",
  "votingRate": "投票率",
  "withdraw": "出金",
  "update": "更新",
  "approved": "承認済",
  "waiting": "待っています",
  "totalFound": "検索結果",
  "totalOwner": "すべてのオーナー",
  "awaitingApprove": "承認待ち",
  "voteRate": "投票率",
  "owner": "オーナー",
  "change": "変更",
  "ownersAddress": "オーナーアドレス",
  "votingPower": "投票権",
  "type": "タイプ",
  "date": "日付",
  "status": "ステータス",
  "process": "プロセス",
  "transactionId": "取引ID",
  "creator": "作成者",
  "wellcome": "ようこそ",
  "multisig": "マルチシグウォレット",
  "createNew": "新作",
  "addOwner": "オーナー追加",
  "addVoteRate": "投票率追加",
  "multisigWalletName": "マルチシグニチャーウォレット名",
  "c98Private": "C98個人基金",
  "successSent": "送付が成功しました",
  "removeOwner": "オーナー削除",
  "newVoteRate": "新投票率",
  "newVotePower": "新投票権",
  "poweredByCoin98": "Coin98 Wallet Engineにサポートしてもらいます",
  "lessThan": "未満",
  "noSpace": "スペース無し",
  "characters": "文字",
  "createTokenError": "トークン発行者の作成エラー",
  "createTokenSuccess": "トークン発行者の作成が成功しました",
  "confirmCreateTokenIssue": "トークン発行者が正しいですか？",
  "pleaseInput": "ご記入ください",
  "invalidAddrWallet": "アドレスが無効です",
  "wallet": "ウォレット",
  "tokenName": "トークン名",
  "tokenSymbol": "トークン信号",
  "decimalPoint": "小数ポイント",
  "ownerAddress": "オーナーアドレス",
  "tokenLogo": "トークンロゴ",
  "selectChain": "チェーン選択",
  "tokenMint": "TOKEN MINT",
  "tokenBurn": "TOKEN BURN",
  "powerByCoin98": "Coin98 Labsにサポートしてもらいます"
}