export default {
  "last7Days": "지난 7 일",
  "fullyDiluted": "완전히 줄어든 시가 총액",
  "liquidityProvider": "유동성 공급자 수수료",
  "averagePrice": "평균 가격",
  "priceImpact": "가격 영향",
  "minutes": "몇 분",
  "gasSetting": "가스 설정",
  "searchNotFound": "검색을 찾을 수 없음",
  "noWalletFound": "지갑 없음",
  "tradeSuccess": "주문 완료",
  "confirmApprove": "승인 확인",
  "claimSwap": "청구 확인",
  "confirmSwap": "스왑 확인",
  "txsFee": "수수료: {{amount}} ~ {{amountUSD}}",
  "pleaseWaitOrder": "주문이 완료될 때까지 잠시 기다려주십시오",
  "pleaseWaitApprove": "승인을 위해 잠시 기다려주십시오",
  "approveSuccess": "승인 완료",
  "pair": "쌍",
  "confirm": "확인",
  "terminal": "터미널",
  "explorers": "탐험가",
  "community": "커뮤니티",
  "d1": "1D",
  "m1": "1M",
  "w1": "1W",
  "y1": "1Y",
  "full": "전체",
  "coin98Wallet": "Coin98 지갑",
  "exchange": "거래소",
  "invest": "투자",
  "dashboard": "대시보드",
  "markets": "시장",
  "confirmation": "확인",
  "passphrase": "암호",
  "success": "성공!",
  "category": "카테고리",
  "platform": "플랫폼",
  "createNewWalletSuccessful": "새 지갑을 성공적으로 생성하십시오!",
  "successfully": "성공적으로",
  "ok": "확인",
  "error": "문제가 발생했습니다!\n  나중에 다시 시도 해주십시오",
  "create": "생성",
  "restore": "복원",
  "cancel": "취소",
  "receiveAddress": "수신 주소",
  "sending": "보내는 중",
  "manage": "관리",
  "rankMarket": "#순위 {{rank}}",
  "max": "최대",
  "edited": "수정 됨",
  "Error": "오류!",
  "search": "검색",
  "goBack": "돌아 가기",
  "searchCurrency": "통화 검색",
  "lendingBorrowing": "대출/차입",
  "walletNotFound": "지갑을 찾을 수 없음",
  "addRestoreWallet": "먼저 지갑을 추가하거나 복원하십시오",
  "wrongPass": "잘못된 비밀번호",
  "yieldFarming": "이자농사",
  "defiStation": "DeFi 스테이션",
  "analytics": "분석",
  "nft": "NFT",
  "governance": "거버넌스",
  "coin98WalletMess": "디지털 자산 저장",
  "terminalMess": "올인원 도구 상자",
  "daapMess": "DeFi 게이트웨이",
  "exchangeMess": "거래 플랫폼",
  "crossChainMess": "여러 체인에서 자산 교환",
  "dashboardMess": "귀하의 통제하에 있는 모든 것",
  "marketMess": "최신 트렌드 따르기",
  "lendingBorrowingMess": "자산에 대한 이자 획득",
  "yieldFarmingMess": "자산 수익 극대화",
  "defiStationMess": "자는 동안 돈을 버세요",
  "portfolioMess": "자산 성과 추적",
  "stankingMess": "보상을 받으려면 자산을 잠금 하세요",
  "governanceMess": "제안에 투표",
  "lunaDex": "Solana 및 Serum에 구축 된 분산형 거래소",
  "connectWallet": "지갑 연결",
  "login": "로그인",
  "en": "영어",
  "vi": "베트남어",
  "email": "이메일",
  "enterEmail": "이메일을 입력하세요",
  "emailInvalid": "잘못된 이메일 주소",
  "userName": "사용자 이름",
  "yourUsername": "귀하의 사용자 이름",
  "displayName": "이름 표시하기",
  "yourDisplayName": "귀하의 표시 이름",
  "swaps": "스왑",
  "swap": "스왑",
  "totalValue": "총 가치",
  "totalVolume": "총 거래량",
  "tokenAmount": "토큰 금액",
  "account": "계정",
  "time": "시각",
  "infoAlert": "이것은 귀하의 정보입니다",
  "infoSuccess": "성공적으로 무언가 생성",
  "infoError": "다음으로 인한 오류 ...",
  "approveToken": "{{nameTokenBuy}} 승인",
  "buyToken": "{{nameTokenBuy}} 구매",
  "loginSuccess": "성공적으로 로그인",
  "password": "암호",
  "passInvalid": "비밀번호는 숫자와 문자가 포함 된 6 자리 이상 이어야합니다",
  "confirmPassword": "비밀번호 확인",
  "passNotMatch": "비밀번호가 일치하지 않습니다",
  "yourPassword": "귀하의 비밀번호",
  "inputPassword": "비밀번호를 입력하세요",
  "passRequired": "비밀번호를 입력하세요",
  "emailVerificationsCode": "이메일 확인 코드",
  "referralCode": "추천 코드",
  "referExistError": "ID가 존재하지 않습니다",
  "nameBeenTaken": "귀하의 사용자 이름이 사용되었습니다",
  "nameAlreadyTaken": "이 이름은 이미 사용되었습니다",
  "resetPass": "새 비밀번호 재설정",
  "usernameRequired": "사용자 이름이 필요합니다",
  "displaynameRequired": "표시 이름이 필요합니다.",
  "confirmPass": "비밀번호 확인이 필요합니다",
  "confirmPassNotMatch": "비밀번호가 일치하지 않음 확인",
  "youHaveBanned": "귀하께서는 차단됬습니다!",
  "fraudBehaviorDevice": "기기 정보에 대한 액세스를 허용하지 않았습니다\n  또는 휴대 전화가 안전 기준을 충족하지 않습니다",
  "emailRequired": "이메일이 필요합니다",
  "manageWallet": "지갑 관리",
  "addWallet": "지갑 추가",
  "restoreWallet": "지갑 복원",
  "connectOtherWallet": "다른 지갑 연결",
  "send": "보내기",
  "receive": "받기",
  "website": "웹사이트",
  "smartContract": "스마트 계약",
  "allTimeLow": "최저치",
  "allTimeHigh": "최고치",
  "high24h": "24 시간 최고",
  "low24h": "24 시간 최저",
  "circulatingSupply": "유통량",
  "maxSupply": "전체 코인 수",
  "marketCap": "시가 총액",
  "col24h": "24H 거래량",
  "feeErr": "잔액 또는 가스비가 충분하지 않습니다",
  "allWallet": "모든 지갑",
  "multiChain": "멀티 체인",
  "ether": "Ether(이더)",
  "solana": "Solana(솔라나)",
  "binanceSmart": "바이낸스 스마트",
  "polkadot": "폴카닷(Polkadot)",
  "kusama": "쿠사마(Kusama)",
  "heco": "헤코(Heco)",
  "mustAtLeastDot": "보내려면 DOT가 1 개 이상 남아 있어야합니다",
  "enterAmountToStartTransaction": "거래 시작 금액 입력",
  "amountErr": "지출 가능한 금액보다 적거나 같아야합니다",
  "walletName": "지갑 이름",
  "walletKey": "지갑 키",
  "walletKeyPhrase": "니모닉 암호",
  "walletNameExist": "지갑 이름이 이미 존재합니다",
  "copyDone": "주소 {{value}}이 복사되었습니다",
  "onlySend": "이 주소로만 {{symbol}}을 보냅니다. 이 주소로 다른 자산을 보내면 자산 손실이 발생합니다.",
  "amount": "금액",
  "recipient": "받는 사람",
  "walletAddress": "지갑 주소",
  "confirmInfo": "정보 확인",
  "noData": "데이터 없음",
  "message": "메시지",
  "messageIsOptional": "메시지는 선택 사항입니다",
  "inputRequired": "이 필드를 입력하십시오",
  "verifyEmail": "이메일 확인",
  "comfirmation": "확인",
  "confirmDelete": "이 지갑을 제거 하시겠습니까?",
  "passphraseOrPrivateKey": "암호 또는 개인 키",
  "verySlow": "아주 느린",
  "slow": "느린",
  "fast": "빠른",
  "superFast": "초고속",
  "standard": "표준",
  "gasWar": "가스 전쟁",
  "starWar": "스타 전쟁",
  "tryAgain": "몇 분 후에 다시 시도하십시오",
  "txsFail": "거래 실패",
  "whitePaper": "정식 보고서",
  "timeOutTxs": "거래 시간이 초과되었거나 확인되지 않았습니다, 잠시 기다렸다가 다시 시도하세요",
  "minimum1Polkadot": "받는 사람 주소에는 2 개 이상의 DOT가 있어야합니다",
  "invalidAddr": "잘못된 수신자 주소",
  "createAccount": "계정 생성",
  "createAccountSuccess": "성공적으로 계정 생성",
  "areYouSureToCreateANewWallet": "새 지갑을 만드시겠습니까?",
  "createWallet": "지갑 생성",
  "phoneRegister": "전화 번호는 등록된 계정에만 사용됩니다",
  "clickContinue": "계속을 클릭하면 다음에 동의하는 것입니다",
  "teamService": "Coin98 지갑의 서비스 약관",
  "scanToLogin": "로그인하려면 스캔",
  "forgotPass": "비밀번호를 잊어 버렸습니까?",
  "reset": "초기화",
  "continue": "계속하다",
  "dintRecive": "인증 코드를받지 못하셨습니까?",
  "resend": "재전송",
  "restoreWalletSuccess": "지갑을 성공적으로 복원하십시오!",
  "enjoy": "즐겨",
  "register": "등록",
  "sureNewWallet": "새 지갑을 만드시겠습니까?",
  "myWallet": "내 지갑",
  "understandChoose": "복구 키를 분실하면 지갑에 액세스 할 수 없음을 이해합니다",
  "done": "완료",
  "manageContact": "연락처 관리",
  "hiddenToken": "숨겨진 토큰 목록",
  "setActive": "활성으로 설정",
  "copyAddress": "주소 복사",
  "showQr": "QR 코드 표시",
  "showKey": "주요 정보 표시",
  "connectToWallet": "지갑에 연결",
  "chooseWallet": "지갑을 선택하세요",
  "whatIsWallet": "지갑이란?",
  "totalBalance": "전체 균형",
  "otpWrong": "잘못된 OTP 코드",
  "asset": "자산",
  "symbol": "상징",
  "price": "가격",
  "balance": "잔액",
  "value": "가치",
  "market24": "24 시간",
  "address": "주소",
  "maxSlippage": "최대 슬리피지",
  "termsOfService": "서비스 약관",
  "volume": "거래량",
  "volume24": "24 시간 거래량",
  "selectWallet": "지갑 선택",
  "selectedWallet": "지갑 선택",
  "addressIsCopy": "주소가 복사되었습니다",
  "orderFunding": "주문 자금",
  "orderVolume": "주문량",
  "youSend": "보내기",
  "youReceive": "받기",
  "all": "모두",
  "high": "높은",
  "createContact": "연락처 생성",
  "recommend": "추천",
  "comingSoon": "곧 출시",
  "connected": "연결됨",
  "installCoin98Wallet": "관리 지갑용 Coin98 지갑 설치",
  "coin98WalletNotInstalled": "Coin98 지갑이 설치되지 않았습니다",
  "connectCoin98Wallet": "Coin98 지갑에 연결",
  "BTCDominace": "BTC 도미넌스",
  "ETHDominace": "ETH 도미넌스",
  "rank": "계급",
  "onWatchList": "{{num}} 관심 목록",
  "token": "토큰",
  "day": "일",
  "month": "달",
  "week": "주",
  "year": "년",
  "custom": "사용자 지정",
  "uniswapPrice": "유니스왑 시세",
  "low": "낮은",
  "hight": "높은",
  "fullDiluted": "완전히 줄어든 시가 총액",
  "volume24h": "24h 거래량",
  "totalSupply": "총 코인 수",
  "viewDetail": "세부 정보 보기",
  "from": "에서",
  "to": "에",
  "willReceive": "받게됩니다 ~",
  "fee": "수수료",
  "balanceTotal": "금액 합계",
  "route": "루트",
  "step": "단계",
  "finish": "끝",
  "swapHistory": "스왑 내역",
  "coins": "코인",
  "watchList": "관심 목록",
  "contract": "계약",
  "priceChange": "가격 변경",
  "tradingVolume": "거래량",
  "marketCapRank": "시가 총액 순위",
  "atHight": "최고치",
  "atLow": "최저치",
  "sushiPrice": "가격 통계",
  "showRows": "행 표시",
  "filters": "필터",
  "overview": "개요",
  "chart": "차트",
  "cryptoAsset": "암호 화폐",
  "historicalData": "역사적 자료",
  "tradingView": "트레이딩 뷰",
  "uniswapChart": "유니스왑 차트",
  "name": "이름",
  "liquidity": "유동성",
  "Volume": "거래량",
  "fees": "수수료",
  "topPairs": "상위 페어",
  "searchPairToken": "쌍 및 토큰 검색",
  "invalidPassPhrase": "암호 또는 개인 키를 다시 확인하십시오!",
  "needCreate": "먼저 Solana 지갑을 생성하거나 가져와야합니다",
  "areYouCreate": "새 지갑을 만드시겠습니까?",
  "willBeStored": "{{nameChainWallet}} 지갑에 저장됩니다.",
  "feeTransactionMust": "수수료 거래는 {{num}} {{symbol}} 이상이어야합니다",
  "chainNotSupported": "체인은 아직 지원되지 않았습니다",
  "nameChart": "{{symbol}} 차트",
  "areYouLogout": "로그아웃 하시겠습니까?",
  "vol24h": "24H 거래량",
  "volumeMarket": "거래량 / 시가 총액",
  "resetFilters": "필터 재설정",
  "sureToSend": "{{num}} {{symbol}}을 {{address}} 주소로 보내시겠습니까?",
  "sumAddress": "{{num}} 주소",
  "amountCannotZero": "금액은 0 일 수 없습니다",
  "multiSend": "다중 전송",
  "totalAddress": "총 주소",
  "addressEmpty": "주소는 비워 둘 수 없습니다",
  "amountEmpty": "금액은 비워 둘 수 없습니다",
  "inputNotRequirements": "입력이 요구 사항을 충족하지 않습니다",
  "gwei": "Gwei",
  "hi": "안녕하세요",
  "forTransaction": "거래용",
  "approveConversion": "전환 승인",
  "sendFound": "자금 보내기",
  "waitForConfirm": "확인을 기다립니다",
  "rename": "이름 바꾸기",
  "questionRename": "지갑 이름을 바꾸시겠습니까?",
  "questionImport": "주소와 금액을 가져 오시겠습니까?",
  "alreadySend": "이미 보냈습니다",
  "resendOTP": "OTP를 성공적으로 재전송",
  "fortmatic": "Fortmatic",
  "coinbaseWallet": "Coinbase 지갑",
  "walletConnect": "지갑 연결",
  "metaMask": "MetaMask",
  "dapper": "Dapper",
  "lattice": "Lattice",
  "private": "개인 정보",
  "activeMultiChain": "멀티 체인 지갑 활성화",
  "activeChain": "{{chain}} 지갑 활성화",
  "removeWallet": "{{name}} 지갑 제거",
  "noMatchingResult": "일치하는 결과가 없습니다",
  "areYouSureSend": "{{num}} {{symbol}} <br/> {{address}} 보내기",
  "addressAmount": "주소? 금액, 주소? 금액",
  "import": "가져오기",
  "addressAndAmount": "주소 및 금액",
  "gasPrice": "가스 가격",
  "transactionData": "거래 데이터",
  "gasLimit": "가스 제한",
  "nonce": "임시",
  "change24h": "% 변화",
  "rankTop": "상위 100-200 위",
  "nameRank": "이름",
  "hour24Trading": "24 시간 거래량",
  "lowHight24h": "24 시간 낮음 / 높음",
  "allTimeLowHigh": "최저치 / 최고치",
  "unlimitedApproval": "무제한 승인",
  "estimateFee": "예상 수수료",
  "searchCoinOrPasteAnyToken": "코인 검색 또는 토큰 붙여 넣기",
  "transactionDeadline": "거래 마감 시간",
  "owners": "소유자",
  "votingRate": "투표율",
  "withdraw": "인출",
  "update": "최신 정보",
  "approved": "승인됨",
  "waiting": "대기 중",
  "totalFound": "총 발견",
  "totalOwner": "총 소유자",
  "awaitingApprove": "승인 대기 중",
  "voteRate": "투표율",
  "owner": "소유자",
  "change": "변화",
  "ownersAddress": "소유자 주소",
  "votingPower": "투표권",
  "type": "유형",
  "date": "일자",
  "status": "상태",
  "process": "방법",
  "transactionId": "거래 ID",
  "creator": "크리에이터",
  "wellcome": "여기에 오신 것을 환영합니다",
  "multisig": "Multisig 지갑",
  "createNew": "새 생성",
  "addOwner": "소유자 추가",
  "addVoteRate": "투표율 추가",
  "multisigWalletName": "다중 서명 지갑 이름",
  "c98Private": "C98 사모 펀드",
  "successSent": "성공적으로 전송 됨",
  "removeOwner": "소유자 제거",
  "newVoteRate": "새로운 투표율",
  "newVotePower": "새로운 투표권",
  "poweredByCoin98": "Coin98 지갑 엔진에 의해 구동",
  "lessThan": "이하",
  "noSpace": "공간 없음",
  "characters": "문자",
  "createTokenError": "토큰 발행자 오류 생성",
  "createTokenSuccess": "토큰 발급자를 성공적으로 생성",
  "confirmCreateTokenIssue": "토큰 발행자를 확인 하시겠습니까?",
  "pleaseInput": "입력 해주세요",
  "invalidAddrWallet": "잘못된 주소",
  "wallet": "지갑",
  "tokenName": "토큰 이름",
  "tokenSymbol": "토큰 기호",
  "decimalPoint": "소수점",
  "ownerAddress": "소유자 주소",
  "tokenLogo": "토큰 로고",
  "selectChain": "체인 선택",
  "tokenMint": "토큰 민트",
  "tokenBurn": "토큰 소각",
  "powerByCoin98": "Coin98 Labs에서 제공"
}