export default {
  "last7Days": "ÚLTIMOS 7 DIAS",
  "fullyDiluted": "Valor de Mercado Totalmente Diluído",
  "liquidityProvider": "Taxa do provedor de liquidez",
  "averagePrice": "Preço Médio",
  "priceImpact": "Impacto de Preço",
  "minutes": "minutos",
  "gasSetting": "Configuração Gas",
  "searchNotFound": "Pesquisa Não Encontrada",
  "noWalletFound": "Sem Carteira",
  "tradeSuccess": "Pedido Feito Com Sucesso",
  "confirmApprove": "Confirmação de Aprovação",
  "claimSwap": "Confirmação de Reivindicação",
  "confirmSwap": "Confirmação de Troca",
  "txsFee": "Taxa: {{amount}} ~ {{amountUSD}}",
  "pleaseWaitOrder": "Por favor, aguarde um momento para que o pedido seja concluído",
  "pleaseWaitApprove": "Por favor, aguarde um momento para aprovação",
  "approveSuccess": "Aprovado com sucesso",
  "pair": "Par",
  "confirm": "Confirmar",
  "terminal": "Terminal",
  "explorers": "Exploradores",
  "community": "Comunidade",
  "d1": "1D",
  "m1": "1M",
  "w1": "1W",
  "y1": "1Y",
  "full": "Cheio",
  "coin98Wallet": "Carteira Coin98",
  "exchange": "Exchange",
  "invest": "Investir",
  "dashboard": "Painel",
  "markets": "Mercado",
  "confirmation": "Confirmação",
  "passphrase": "Senha",
  "success": "Sucesso!",
  "category": "categoria",
  "platform": "Plataforma",
  "createNewWalletSuccessful": "Crie uma nova carteira com sucesso!",
  "successfully": "Com sucesso",
  "ok": "Ok",
  "error": "Algo deu errado!\n   Por favor, tente novamente mais tarde",
  "create": "Criar",
  "restore": "Restaurar",
  "cancel": "Cancelar",
  "receiveAddress": "Endereço de Recebimento",
  "sending": "Enviando",
  "manage": "Gerenciar",
  "rankMarket": "#Ranquear {{rank}}",
  "max": "MAX",
  "edited": "Editado",
  "Error": "Algo deu errado!\n   Por favor, tente novamente mais tarde",
  "search": "Buscar",
  "goBack": "Voltar",
  "searchCurrency": "Buscar Moeda",
  "lendingBorrowing": "Emprestar/Pedir Emprestado",
  "walletNotFound": "Carteira Não Encontrada",
  "addRestoreWallet": "Por favor, adicionar ou restaurar uma carteira primeira",
  "wrongPass": "Senha inválida",
  "yieldFarming": "Produção Agrícola",
  "defiStation": "Estação DeFi",
  "analytics": "Analytics",
  "nft": "NFT",
  "governance": "Governança",
  "coin98WalletMess": "Armazenar Ativos Digitais",
  "terminalMess": "Caixa de Ferramentas Multifuncional",
  "daapMess": "Porta de Entrada DeFi",
  "exchangeMess": "Plataforma de Negociação",
  "crossChainMess": "Troque ativos em várias cadeias",
  "dashboardMess": "Tudo sob seu controle",
  "marketMess": "Siga as últimas tendências",
  "lendingBorrowingMess": "Ganhe juros sobre ativos",
  "yieldFarmingMess": "Maximize os rendimentos de seus ativos",
  "defiStationMess": "Ganhe dinheiro enquanto dorme",
  "portfolioMess": "Acompanhe o desempenho dos ativos",
  "stankingMess": "Bloqueie ativos para receber recompensas",
  "governanceMess": "Votar em propostas",
  "lunaDex": "Exchange descentralizada baseada em Solana e Serum",
  "connectWallet": "Conectar Carteira",
  "login": "Logar",
  "en": "Inglês",
  "vi": "Vietnamita",
  "email": "Email",
  "enterEmail": "Por favor insira o seu email",
  "emailInvalid": "Endereço de email invalido",
  "userName": "Nome de Usuário",
  "yourUsername": "Seu Nome de Usuário",
  "displayName": "Nome de Exibição",
  "yourDisplayName": "Seu Nome de Exibição",
  "swaps": "Trocas",
  "swap": "Troca",
  "totalValue": "Valor Total",
  "totalVolume": "Volume Total",
  "tokenAmount": "Quantidade Token",
  "account": "Conta",
  "time": "Tempo",
  "infoAlert": "Esta é a sua Info",
  "infoSuccess": "Crie algo com sucesso",
  "infoError": "Erro devido a ...",
  "approveToken": "Aprovar {{nameTokenBuy}}",
  "buyToken": "Comprar {{nameTokenBuy}}",
  "loginSuccess": "Login com sucesso",
  "password": "Senha",
  "passInvalid": "A senha deve ter pelo menos 6 dígitos com número e letra",
  "confirmPassword": "Confirmar Senha",
  "passNotMatch": "Senha não coincide",
  "yourPassword": "Sua Senha",
  "inputPassword": "Por favor insira a senha",
  "passRequired": "Por favor, insira sua senha",
  "emailVerificationsCode": "Seu código de verificação de email",
  "referralCode": "Código de Referência",
  "referExistError": "ID não existe",
  "nameBeenTaken": "Seu nome de usuário foi escolhido",
  "nameAlreadyTaken": "Este nome já foi escolhido",
  "resetPass": "Redefinir Nova Senha",
  "usernameRequired": "Nome de usuário é requerido",
  "displaynameRequired": "O nome de exibição é obrigatório",
  "confirmPass": "É necessário confirmar a senha",
  "confirmPassNotMatch": "Confirmar que a senha não coincide",
  "youHaveBanned": "Você foi banido!",
  "fraudBehaviorDevice": "Você não permitiu o acesso às informações do dispositivo\n   Ou seu telefone não atende aos nossos padrões de segurança",
  "emailRequired": "E-mail é obrigatório",
  "manageWallet": "Gerenciar Carteiras",
  "addWallet": "Adicionar Carteira",
  "restoreWallet": "Restaurar Carteira",
  "connectOtherWallet": "Conectar Outra Carteira",
  "send": "Enviar",
  "receive": "Recebido",
  "website": "Website",
  "smartContract": "Contrato Inteligente",
  "allTimeLow": "Menor de Todos o Tempos",
  "allTimeHigh": "Maior de Todos o Tempos",
  "high24h": "24H Alto",
  "low24h": "24H Baixo",
  "circulatingSupply": "Suprimento Circulante",
  "maxSupply": "Suprimento Max",
  "marketCap": "Valor de Mercado",
  "col24h": "24H Vol",
  "feeErr": "Seu saldo ou taxa de gas não é suficiente",
  "allWallet": "Todas as Carteiras",
  "multiChain": "Multi-Chain",
  "ether": "Ether",
  "solana": "Solana",
  "binanceSmart": "Binance Smart",
  "polkadot": "Polkadot",
  "kusama": "Kusama",
  "heco": "Heco",
  "mustAtLeastDot": "Você deve ter pelo menos 1 PONTO restante para enviar",
  "enterAmountToStartTransaction": "Insira o valor para iniciar a transação",
  "amountErr": "Deve ser menor ou igual ao valor gastável",
  "walletName": "Nome da carteira",
  "walletKey": "Chave da carteira",
  "walletKeyPhrase": "Senha mnemônica",
  "walletNameExist": "O nome da carteira já existe",
  "copyDone": "Endereço {{value}} foi copiado",
  "onlySend": "Envie apenas {{symbol}} para este endereço. O envio de qualquer outro ativo para este endereço resultará na perda de ativos",
  "amount": "Quantidade",
  "recipient": "Recipiente",
  "walletAddress": "Endereço de Carteira",
  "confirmInfo": "Confirmar Info",
  "noData": "Sem Dados",
  "message": "Mensagem",
  "messageIsOptional": "Mensagem é Opcional",
  "inputRequired": "Por favor, preencha este campo",
  "verifyEmail": "Verificar email",
  "comfirmation": "Confirmation",
  "confirmDelete": "Tem certeza de que deseja remover esta carteira?",
  "passphraseOrPrivateKey": "Senha ou Chave Privada",
  "verySlow": "Muito Lento",
  "slow": "Lento",
  "fast": "Rápido",
  "superFast": "Super Rápido",
  "standard": "Padrão",
  "gasWar": "Disputa Gas",
  "starWar": "Disputa Star",
  "tryAgain": "Por favor, tente novamente em alguns minutos",
  "txsFail": "Falha na Transação",
  "whitePaper": "Papel branco",
  "timeOutTxs": "Transação expirou ou não foi confirmada, por favor, aguarde um momento e tente novamente.",
  "minimum1Polkadot": "O endereço do destinatário precisa ter mais de 1 PONTO",
  "invalidAddr": "Endereço de destinatário inválido",
  "createAccount": "Criar Conta",
  "createAccountSuccess": "Criar conta com sucesso",
  "areYouSureToCreateANewWallet": "Tem certeza de que deseja criar uma nova carteira?",
  "createWallet": "Criar Carteira",
  "phoneRegister": "O número de telefone é usado apenas para uma conta registrada",
  "clickContinue": "Ao clicar em \"Continuar\", você concorda com",
  "teamService": "Termos de Serviço da Carteira Coin98",
  "scanToLogin": "Escanear para ",
  "forgotPass": "Esqueceu sua senha?",
  "reset": "Redefinir",
  "continue": "Continuar",
  "dintRecive": "Não recebi o código de verificação?",
  "resend": "Reenviar",
  "restoreWalletSuccess": "Restaurar carteira com sucesso!",
  "enjoy": "Aproveite",
  "register": "Registrar",
  "sureNewWallet": "Tem certeza de que deseja criar uma nova carteira?",
  "myWallet": "Minha Carteira",
  "understandChoose": "Eu entendo que se eu perder minha chave de recuperação, não poderei acessar minha carteira",
  "done": "Feito",
  "manageContact": "Gerenciar Contatos",
  "hiddenToken": "Lista Token Oculta",
  "setActive": "Ativar",
  "copyAddress": "Copiar Endereço",
  "showQr": "Mostrar Código QR",
  "showKey": "Mostrar Info de Chave",
  "connectToWallet": "Conectar A Uma Carteira",
  "chooseWallet": "Escolher A Uma Carteira",
  "whatIsWallet": "Conectar A Uma Carteira?",
  "totalBalance": "Saldo Total",
  "otpWrong": "Código OTP inválido",
  "asset": "Ativo",
  "symbol": "Símbolo",
  "price": "Preço",
  "balance": "Saldo",
  "value": "Valor",
  "market24": "24h",
  "address": "Endereço",
  "maxSlippage": "Deslizamento Máximo",
  "termsOfService": "Termos de Serviço",
  "volume": "Volume",
  "volume24": "Volume 24H",
  "selectWallet": "Selecionar Carteira",
  "selectedWallet": "Carteira Selecionada",
  "addressIsCopy": "Endereço foi copiado",
  "orderFunding": "Pedir Financiamento",
  "orderVolume": "Pedir Volume",
  "youSend": "VOCÊ ENVIOU",
  "youReceive": "VOCÊ RECEBEU",
  "all": "Tudo",
  "high": "Alto",
  "createContact": "Criar Contato",
  "recommend": "Recomendar",
  "comingSoon": "Em breve",
  "connected": "Conectado",
  "installCoin98Wallet": "Instale a carteira Coin98 para gerenciamento da carteira",
  "coin98WalletNotInstalled": "A Carteira Coin98 não foi instalada",
  "connectCoin98Wallet": "Conectar à carteira Coin98",
  "BTCDominace": "Dominância BTC",
  "ETHDominace": "Dominância ETH",
  "rank": "Ranque",
  "onWatchList": "Na {{num}} lista de observação",
  "token": "Token",
  "day": "dia",
  "month": "mês",
  "week": "semana",
  "year": "ano",
  "custom": "personalizado",
  "uniswapPrice": "Preço Uniswap",
  "low": "Baixo",
  "hight": "Alto",
  "fullDiluted": "Valor de Mercado Totalmente Diluído",
  "volume24h": "Volume 24h",
  "totalSupply": "Suprimento Total",
  "viewDetail": "Visualizar Detalhes",
  "from": "De",
  "to": "para",
  "willReceive": "Você receberá ~",
  "fee": "Taxa",
  "balanceTotal": "Saldo total",
  "route": "Rota",
  "step": "Etapa",
  "finish": "Finalizar",
  "swapHistory": "Histórico de Troca",
  "coins": "Moedas",
  "watchList": "Lista de Observação",
  "contract": "Contrato",
  "priceChange": "Mudança de Preço",
  "tradingVolume": "Volume de Negociação",
  "marketCapRank": "Ranque de Valor de Mercado",
  "atHight": "Todo- Tempo Máximo",
  "atLow": "Todo - Tempo Mínimo",
  "sushiPrice": "Estatísticas de Preços",
  "showRows": "Mostrar linhas",
  "filters": "Filtrar",
  "overview": "Visão geral",
  "chart": "Gráfico",
  "cryptoAsset": "Criptos",
  "historicalData": "Dados Históricos",
  "tradingView": "Visão de negociação",
  "uniswapChart": "Gráfico Uniswap",
  "name": "nome",
  "liquidity": "Liquidez",
  "Volume": "Volume",
  "fees": "taxas",
  "topPairs": "Pares Principais",
  "searchPairToken": "Par de pesquisa e token",
  "invalidPassPhrase": "Verifique sua Senha ou Chave Privada novamente!",
  "needCreate": "Precisa criar ou importar a Carteira Solana primeiro",
  "areYouCreate": "Tem certeza de que deseja criar uma nova carteira?",
  "willBeStored": "Será armazenado na Carteira {{nameChainWallet}} ",
  "feeTransactionMust": "A taxa da transação deve ser de pelo menos {{num}} {{symbol}}",
  "chainNotSupported": "Cadeia ainda não foi apoiada",
  "nameChart": "{{symbol}} Gráfico",
  "areYouLogout": "Tem certeza de que deseja sair?",
  "vol24h": "Vol 24H",
  "volumeMarket": "Volume / Valor de Mercado",
  "resetFilters": "Reiniciar Filtro",
  "sureToSend": "em certeza que deseja enviar {{num}} {{symbol}} para {{address}} endereço?",
  "sumAddress": "{{num}} Endereço",
  "amountCannotZero": "amountCannotZero: 'Quantidade não pode ser zero",
  "multiSend": "Multi-Envio",
  "totalAddress": "Endereço Total",
  "addressEmpty": "O endereço não pode estar vazio",
  "amountEmpty": "A quantidade não pode estar vazia",
  "inputNotRequirements": "Entrada não atende aos requisitos",
  "gwei": "Gwei",
  "hi": "Oi",
  "forTransaction": "Para Transação",
  "approveConversion": "Aprovar Conversão",
  "sendFound": "Enviar Fundo",
  "waitForConfirm": "Aguarde por Confirmações",
  "rename": "Renomear",
  "questionRename": "Tem certeza que deseja renomear carteira",
  "questionImport": "Tem certeza de que deseja importar o endereço e o valor",
  "alreadySend": "Já foi enviado",
  "resendOTP": "Reenviar OTP com sucesso",
  "fortmatic": "Fortmatic",
  "coinbaseWallet": "Carteira Coinbase",
  "walletConnect": "Conectar Carteira",
  "metaMask": "MetaMask",
  "dapper": "Dapper",
  "lattice": "Lattice",
  "private": "Privada",
  "activeMultiChain": "Ativar Carteira Multi-Chain",
  "activeChain": "Ativar Carteira {{chain}} ",
  "removeWallet": "Remover Carteira {{name}} ",
  "noMatchingResult": "Nenhum resultado correspondente",
  "areYouSureSend": "Enviar {{num}} {{symbol}} <br/> {{address}}",
  "addressAmount": "endereço? montante, endereço? montante",
  "import": "Importar",
  "addressAndAmount": "Endereço e Quantidade",
  "gasPrice": "PREÇO GAS",
  "transactionData": "DADOS DE TRANSAÇÃO",
  "gasLimit": "LIMITE GAS",
  "nonce": "NONCE",
  "change24h": "% Change",
  "rankTop": "Ranque Top 100-200",
  "nameRank": "Nome",
  "hour24Trading": "24 Volume de Horas de Negociação ",
  "lowHight24h": "24H Menor / Maior",
  "allTimeLowHigh": "Todos os Tempos Menor / Maior",
  "unlimitedApproval": "Aprovação ilimitada",
  "estimateFee": "Taxa de Estimativa",
  "searchCoinOrPasteAnyToken": "Pesquise moeda ou cole qualquer token",
  "transactionDeadline": "Prazo de Transação",
  "owners": "Proprietários",
  "votingRate": "Taxa de Votação",
  "withdraw": "Retirar",
  "update": "Atualizar",
  "approved": "Aprovar",
  "waiting": "Espera",
  "totalFound": "Total Encontrado",
  "totalOwner": "Proprietários Total",
  "awaitingApprove": "Aguardando Aprovação",
  "voteRate": "Taxa de Votação",
  "owner": "Propriertário",
  "change": "Troca",
  "ownersAddress": "Endereço dos Proprietários",
  "votingPower": "Poder de Voto",
  "type": "Tipo",
  "date": "Data",
  "status": "Status",
  "process": "Processar",
  "transactionId": "transaction ID",
  "creator": "Criador",
  "wellcome": "Bem-vindo ao",
  "multisig": "Carteira Multi-assinatura",
  "createNew": "Criar Novo",
  "addOwner": "Adicionar Propriertário",
  "addVoteRate": "Adicionar Taxa de Voto",
  "multisigWalletName": "Nome Carteira Multi-assinatura",
  "c98Private": "Fundo Privado C98",
  "successSent": "Enviado com sucesso",
  "removeOwner": "Remover Propriertário",
  "newVoteRate": "Nova Taxa de Voto",
  "newVotePower": "Novo Poder de Voto",
  "poweredByCoin98": "Desenvolvido por Coin98 Mecanismo de Carteira",
  "lessThan": "Menor que",
  "noSpace": "Sem espaço",
  "characters": "caracteres",
  "createTokenError": "Criar Erro de Emissor de Token",
  "createTokenSuccess": "Emissor de Token Criado com Sucesso",
  "confirmCreateTokenIssue": "Tem certeza que deseja confirmar o Emissor do Token ?",
  "pleaseInput": "Por favor, insira",
  "invalidAddrWallet": "Endereço inválido",
  "wallet": "Carteira",
  "tokenName": "NOME DO TOKEN",
  "tokenSymbol": "SÍMBOLO DO TOKEN",
  "decimalPoint": "PONTOS DECIMAIS",
  "ownerAddress": "ENDEREÇO DO PROPRIETÁRIO",
  "tokenLogo": "LOGO DO TOKEN ",
  "selectChain": "selecione cadeia",
  "tokenMint": "TOKEN MINT",
  "tokenBurn": "TOKEN BURN",
  "powerByCoin98": "Desenvolvido por Coin98 Labs"
}