export default {
  "last7Days": "ПОСЛЕДНИЕ 7 ДНЕЙ",
  "fullyDiluted": "Полностью разбавленная рыночная капитализация",
  "liquidityProvider": "Комиссия поставщика ликвидности",
  "averagePrice": "Средняя цена",
  "priceImpact": "Влияние на цену",
  "minutes": "минут",
  "gasSetting": "Настройка газа",
  "searchNotFound": "Запрос не найден",
  "noWalletFound": "Нет кошелька",
  "tradeSuccess": "Операция исполнена",
  "confirmApprove": "Подтверждение одобрения",
  "claimSwap": "Подтверждение требования",
  "confirmSwap": "Подтверждение свопа",
  "txsFee": "Комиссия: {{сумма}} ~ {{суммаUSD}}",
  "pleaseWaitOrder": "Пожалуйста, подождите до выполнения Вашего заказа",
  "pleaseWaitApprove": "Пожалуйста, подождите до одобрения",
  "approveSuccess": "Одобрение успешно",
  "pair": "Соединить",
  "confirm": "Подтвердить",
  "terminal": "Терминал",
  "explorers": "Исследователи",
  "community": "Сообщество",
  "d1": "1 день",
  "m1": "1 месяц",
  "w1": "1 неделя",
  "y1": "1 год",
  "full": "Полный",
  "coin98Wallet": "Кошелек Coin98",
  "exchange": "Обмен",
  "invest": "Инвестировать",
  "dashboard": "Панель управления",
  "markets": "Рынки",
  "confirmation": "Подтверждение",
  "passphrase": "Кодовая фраза",
  "success": "Успешно!",
  "category": "категория",
  "platform": "Платформа",
  "createNewWalletSuccessful": "Создание нового кошелька успешно!",
  "successfully": "Успешно",
  "ok": "ОК",
  "error": "Что-то пошло не так!\nПожалуйста, повторите попытку позже",
  "create": "Создать",
  "restore": "Восстановить",
  "cancel": "Отменить",
  "receiveAddress": "Адрес получателя",
  "sending": "Отправляется",
  "manage": "Управлять",
  "rankMarket": "#Рейтинг {{рейтинг}}",
  "max": "МАКСИМУМ",
  "edited": "Изменено",
  "Error": "Что-то пошло не так!\nПожалуйста, повторите попытку позже",
  "search": "Поиск",
  "goBack": "Вернуться назад",
  "searchCurrency": "Валюта поиска",
  "lendingBorrowing": "Занять/одолжить",
  "walletNotFound": "Кошелек не найден",
  "addRestoreWallet": "Пожалуйста, сначала добавьте или восстановите кошелек",
  "wrongPass": "Недействительный пароль",
  "yieldFarming": "Прибыль от фермерства",
  "defiStation": "Станция DeFi",
  "analytics": "Аналитика",
  "nft": "NFT",
  "governance": "Управление",
  "coin98WalletMess": "Хранить цифровые активы",
  "terminalMess": "Универсальный набор инструментов",
  "daapMess": "Шлюз DeFi",
  "exchangeMess": "Торговая платформа",
  "crossChainMess": "Своп активами в нескольких цепочках",
  "dashboardMess": "Все под вашим контролем",
  "marketMess": "Следите за последними тенденциями",
  "lendingBorrowingMess": "Зарабатывайте проценты на активы",
  "yieldFarmingMess": "Увеличьте доходность своих активов",
  "defiStationMess": "Зарабатывай, пока спишь",
  "portfolioMess": "Отслеживайте эффективность активов",
  "stankingMess": "Заблокируйте активы, чтобы получать награды",
  "governanceMess": "Голосовать за предложения",
  "lunaDex": "Децентрализованный обмен, построенный на Solana и Serum",
  "connectWallet": "Подключить кошелек",
  "login": "Авторизоваться",
  "en": "Войти",
  "vi": "вьетнамский",
  "email": "Электронное письмо",
  "enterEmail": "Пожалуйста, введи Ваш email",
  "emailInvalid": "Недействительный email",
  "userName": "Имя пользователя",
  "yourUsername": "Ваш логин",
  "displayName": "Отображаемое имя",
  "yourDisplayName": "Ваше отображаемое имя",
  "swaps": "Свопы",
  "swap": "Своп",
  "totalValue": "Общая стоимость",
  "totalVolume": "Общий объем",
  "tokenAmount": "Количество токенов",
  "account": "Счет",
  "time": "Время",
  "infoAlert": "Это ваша информация",
  "infoSuccess": "Создание чего-нибудь успешно",
  "infoError": "Ошибка из-за ...",
  "approveToken": "Одобрить {{имяТокенКупить}}",
  "buyToken": "Купить {{имяТокенКупить}}",
  "loginSuccess": "Авторизация успешно",
  "password": "Пароль",
  "passInvalid": "Пароль должен состоять не менее чем из 6 цифр, включая цифру и букву.",
  "confirmPassword": "Подтвердить пароль",
  "passNotMatch": "Пароль не совпадает",
  "yourPassword": "Ваш пароль",
  "inputPassword": "Пожалуйста, введите пароль",
  "passRequired": "Пожалуйста, введите Ваш пароль",
  "emailVerificationsCode": "Ваш код подтверждения электронной почты",
  "referralCode": "Реферальный код",
  "referExistError": "ID не существует",
  "nameBeenTaken": "Ваше имя уже занято",
  "nameAlreadyTaken": "Это имя уже занято",
  "resetPass": "Сбросить новый пароль",
  "usernameRequired": "Требуется имя пользователя",
  "displaynameRequired": "Требуется отображаемое имя",
  "confirmPass": "Требуется подтверждение пароля",
  "confirmPassNotMatch": "Подтверждение пароля не совпадает",
  "youHaveBanned": "Вас забанили!",
  "fraudBehaviorDevice": "Вы не разрешили доступ к информации об устройстве\nИли ваш телефон не соответствует нашим стандартам безопасности ",
  "emailRequired": "Электронная почта обязательна",
  "manageWallet": "Управлять кошельками",
  "addWallet": "Добавить кошелек",
  "restoreWallet": "Восстановить кошелек",
  "connectOtherWallet": "Подключить другой кошелек",
  "send": "Отправить",
  "receive": "Получить",
  "website": "Веб-сайт",
  "smartContract": "Смарт-контракт",
  "allTimeLow": "Самый низкий за все время",
  "allTimeHigh": "Самый высокий за все время",
  "high24h": "24ч высокий",
  "low24h": "24ч низкий",
  "circulatingSupply": "Циркулирующая поставка",
  "maxSupply": "Максимальное предложение",
  "marketCap": "Рыночная капитализация",
  "col24h": "24-часовой объем",
  "feeErr": "Недостаточно вашего баланса или платы за газ",
  "allWallet": "Все кошельки",
  "multiChain": "Multi-Chain",
  "ether": "Ether",
  "solana": "Solana",
  "binanceSmart": "Binance Smart",
  "polkadot": "Polkadot",
  "kusama": "Kusama",
  "heco": "Heco",
  "mustAtLeastDot": "У вас должен быть хотя бы 1 DOT для отправки",
  "enterAmountToStartTransaction": "Введите сумму для начала транзакции",
  "amountErr": "Должно быть меньше или равно потраченной сумме",
  "walletName": "Имя кошелька",
  "walletKey": "Ключ от кошелька",
  "walletKeyPhrase": "Мнемоническая кодовая фраза",
  "walletNameExist": "Название кошелька уже существует",
  "copyDone": "Адрес {{значение}} скопирован",
  "onlySend": "Отправляйте только {{символ}} на этот адрес. Отправка любого другого актива на этот адрес приведет к потере актива",
  "amount": "Количество",
  "recipient": "Получатель",
  "walletAddress": "Адрес кошелька",
  "confirmInfo": "Подтвердить информацию",
  "noData": "Нет данных",
  "message": "Сообщение",
  "messageIsOptional": "Сообщение не обязательно",
  "inputRequired": "Пожалуйста, заполните это поле",
  "verifyEmail": "Подтвердить электронную почту",
  "comfirmation": "Подтверждение",
  "confirmDelete": "Вы уверены, что хотите удалить этот кошелек?",
  "passphraseOrPrivateKey": "Кодовая фраза или личный ключ",
  "verySlow": "Очень медленно",
  "slow": "Медленный",
  "fast": "Быстрый",
  "superFast": "Сверх быстро",
  "standard": "Стандарт",
  "gasWar": "Газовая война",
  "starWar": "Звездная война",
  "tryAgain": "Пожалуйста, попробуйте снова через несколько минут",
  "txsFail": "Транзакция не удалась",
  "whitePaper": "Белая бумага",
  "timeOutTxs": "Время ожидания транзакции истекло или транзакция не подтверждена, подождите и повторите попытку.",
  "minimum1Polkadot": "У получателя должно быть более 1 DOT",
  "invalidAddr": "Неверный адрес получателя",
  "createAccount": "Создать аккаунт",
  "createAccountSuccess": "Создание кошелька успешно",
  "areYouSureToCreateANewWallet": "Вы уверены, что хотите создать новый кошелек?",
  "createWallet": "Создать кошелек",
  "phoneRegister": "Номер телефона используется только для зарегистрированного аккаунта",
  "clickContinue": "Нажимая «Продолжить», вы соглашаетесь",
  "teamService": "Условия использования кошелька Coin98",
  "scanToLogin": "Отсканируйте, чтобы войти",
  "forgotPass": "Забыли Ваш пароль?",
  "reset": "Сброс",
  "continue": "Продолжить",
  "dintRecive": "Не получили проверочный код?",
  "resend": "Отправить снова",
  "restoreWalletSuccess": "Восстановление кошелька успешно!",
  "enjoy": "Наслаждайтесь",
  "register": "Зарегистрироваться",
  "sureNewWallet": "Вы уверены, что хотите создать новый кошелек?",
  "myWallet": "Мой кошелек",
  "understandChoose": "Я понимаю, что если я потеряю ключ восстановления, я не смогу получить доступ к своему кошельку",
  "done": "Готово",
  "manageContact": "Управление контактами",
  "hiddenToken": "Список скрытых токенов",
  "setActive": "Установить \"Активный\"",
  "copyAddress": "Копировать адрес",
  "showQr": "Показать QR-код",
  "showKey": "Показать ключевую информацию",
  "connectToWallet": "Соединить с кошельком",
  "chooseWallet": "Выберите Ваш кошелек",
  "whatIsWallet": "Что такое кошелек?",
  "totalBalance": "Итоговый баланс",
  "otpWrong": "Недействительный одноразовый код",
  "asset": "Актив",
  "symbol": "Символ",
  "price": "Цена",
  "balance": "Баланс",
  "value": "Стоимость",
  "market24": "24 часа",
  "address": "Адрес",
  "maxSlippage": "Максимальное проскальзывание",
  "termsOfService": "Условия использования",
  "volume": "Объем",
  "volume24": "Объем за 24 часа",
  "selectWallet": "Выберите кошелек",
  "selectedWallet": "Выберите кошелек",
  "addressIsCopy": "Адрес скопирован",
  "orderFunding": "Финансирование заказа",
  "orderVolume": "Объем заказа",
  "youSend": "ВЫ ОТПРАВЛЯЕТЕ",
  "youReceive": "ВЫ ПОЛУЧАЕТЕ",
  "all": "Все",
  "high": "Высокая",
  "createContact": "Создать контакт",
  "recommend": "Рекомендовать",
  "comingSoon": "Скоро появится",
  "connected": "Соединено",
  "installCoin98Wallet": "Установите кошелек Coin98 для управления кошельком",
  "coin98WalletNotInstalled": "Кошелек Coin98 не установлен",
  "connectCoin98Wallet": "Подключиться к кошельку Coin98",
  "BTCDominace": "Доминирование BTC",
  "ETHDominace": "Доминирование ETH",
  "rank": "Классифицировать",
  "onWatchList": "В списке просмотра {{имя}}",
  "token": "Токен",
  "day": "день",
  "month": "месяц",
  "week": "неделя",
  "year": "год",
  "custom": "настроить",
  "uniswapPrice": "Цена Uniswap",
  "low": "Низкий",
  "hight": "Высокий",
  "fullDiluted": "Полностью разбавленная рыночная капитализация",
  "volume24h": "Объем 24ч",
  "totalSupply": "Общее предложение",
  "viewDetail": "Посмотреть детали",
  "from": "От",
  "to": "к",
  "willReceive": "Вы получите ~",
  "fee": "Комиссия",
  "balanceTotal": "Итого по балансу",
  "route": "Маршрут",
  "step": "Шаг",
  "finish": "Закончить",
  "swapHistory": "История свопа",
  "coins": "Криптовалюты",
  "watchList": "Список просмотра",
  "contract": "Контракт",
  "priceChange": "Изменение цены",
  "tradingVolume": "Объем торгов",
  "marketCapRank": "Рейтинг рыночной капитализации",
  "atHight": "Самые высокие за все время существования",
  "atLow": "Самые низкие за все время существования",
  "sushiPrice": "Статистика цен",
  "showRows": "Показать строки",
  "filters": "Фильтр",
  "overview": "Обзор",
  "chart": "Диаграмма",
  "cryptoAsset": "Криптовалюты",
  "historicalData": "Исторические данные",
  "tradingView": "Торговый вид",
  "uniswapChart": "График Uniswap",
  "name": "название",
  "liquidity": "Ликвидность",
  "Volume": "Объем",
  "fees": "комиссия",
  "topPairs": "Лучшие пары",
  "searchPairToken": "Искать пару и токен",
  "invalidPassPhrase": "Пожалуйста, проверьте свою парольную фразу или личный ключ еще раз!",
  "needCreate": "Сначала необходимо создать или импортировать кошелек Solana Wallet",
  "areYouCreate": "Вы уверены, что хотите создать новый кошелек?",
  "willBeStored": "Будет храниться в кошельке {{имяЦепочкаКошелек}}",
  "feeTransactionMust": "Комиссия за транзакцию должна быть не менее {{число}} {{символ}}",
  "chainNotSupported": "Цепочка еще не поддерживается",
  "nameChart": "{{символ}} График",
  "areYouLogout": "Вы уверены, что хотите выйти из системы?",
  "vol24h": "24-часовой объем",
  "volumeMarket": "Объем / рыночная капитализация",
  "resetFilters": "Сбросить фильтр",
  "sureToSend": "Вы уверены, что отправляете {{число}} {{символ}} на {{адрес}} адрес?",
  "sumAddress": "{{число}} Адрес",
  "amountCannotZero": "Сумма не может быть равна нулю",
  "multiSend": "Мульти-отправка",
  "totalAddress": "Общий адрес",
  "addressEmpty": "Адрес не может быть пустым",
  "amountEmpty": "Сумма не может быть пустой",
  "inputNotRequirements": "Вход не соответствует требованиям",
  "gwei": "Gwei",
  "hi": "Привет",
  "forTransaction": "Для транзакции",
  "approveConversion": "Подтвердить конвертацию",
  "sendFound": "Отправить средства",
  "waitForConfirm": "Ждите подтверждений",
  "rename": "Переименовать",
  "questionRename": "Вы уверены, что хотите переименовать кошелек?",
  "questionImport": "Вы уверены, что хотите импортировать адрес и сумму",
  "alreadySend": "Уже отправлено",
  "resendOTP": "Отправка одноразового пароля успешно",
  "fortmatic": "Fortmatic",
  "coinbaseWallet": "Кошелек Coinbase",
  "walletConnect": "Кошелек Connect",
  "metaMask": "Метамаска",
  "dapper": "Dapper",
  "lattice": "Решетка",
  "private": "Частный",
  "activeMultiChain": "Активировать кошелек с несколькими цепочками",
  "activeChain": "Активировать {{цепочка}} кошелек",
  "removeWallet": "Удалить кошелек {{имя}}",
  "noMatchingResult": "Нет подходящего результата",
  "areYouSureSend": "Отправить {{число}} {{символ}} <br/> {{адрес}}",
  "addressAmount": "адрес?сумма,адрес?сумма",
  "import": "Импортировать",
  "addressAndAmount": "Адрес и сумма",
  "gasPrice": "ЦЕНА НА ГАЗ",
  "transactionData": "ДАННЫЕ О ТРАНЗАКЦИИ",
  "gasLimit": "ЛИМИТ НА ГАЗ",
  "nonce": "NONCE",
  "change24h": "% Изменение",
  "rankTop": "Рейтинг 100-200",
  "nameRank": "Имя",
  "hour24Trading": "24-часовой торговый объем",
  "lowHight24h": "24ч низкий / высокий",
  "allTimeLowHigh": "Минимум / максимум за все время",
  "unlimitedApproval": "Неограниченное одобрение",
  "estimateFee": "Примерная комиссия",
  "searchCoinOrPasteAnyToken": "Искать криптовалюту или вставить любой токен",
  "transactionDeadline": "Срок проведения транзакции",
  "owners": "Владельцы",
  "votingRate": "Уровень голосования",
  "withdraw": "Отменить",
  "update": "Обновлять",
  "approved": "Одобрено",
  "waiting": "Ожидание",
  "totalFound": "Всего найдено",
  "totalOwner": "Всего владельцев",
  "awaitingApprove": "В ожидании подтверждения",
  "voteRate": "Уровень голосование",
  "owner": "Владелец",
  "change": "Изменить",
  "ownersAddress": "Адрес владельцев",
  "votingPower": "Сила голосования",
  "type": "Тип",
  "date": "Дата",
  "status": "Статус",
  "process": "Процесс",
  "transactionId": "ID транзакции",
  "creator": "Создатель",
  "wellcome": "Добро пожаловать в",
  "multisig": "Кошелек Multisig",
  "createNew": "Создать новый",
  "addOwner": "Добавить владельца",
  "addVoteRate": "Добавить рейтинг голосования",
  "multisigWalletName": "Мультиподпись Имя кошелька",
  "c98Private": "C98 Частный фонд",
  "successSent": "Успешно отправлено",
  "removeOwner": "Удалить владельца",
  "newVoteRate": "Новый уровень голосования",
  "newVotePower": "Новая сила голоса",
  "poweredByCoin98": "Работает на движке кошелька Coin98",
  "lessThan": "Меньше, чем",
  "noSpace": "Нет места",
  "characters": "символы",
  "createTokenError": "Ошибка создания эмитента токена",
  "createTokenSuccess": "Создание эмитента токена успешно",
  "confirmCreateTokenIssue": "Вы уверены, что подтвердите эмитент токена?",
  "pleaseInput": "Пожалуйста, введите",
  "invalidAddrWallet": "Недействительный адрес",
  "wallet": "Кошелек",
  "tokenName": "ИМЯ ТОКЕНА",
  "tokenSymbol": "СИМВОЛ ТОКЕНА",
  "decimalPoint": "ДЕСЯТИЧНЫЕ ТОЧКИ",
  "ownerAddress": "АДРЕС ВЛАДЕЛЬЦА",
  "tokenLogo": "ЛОГОТИП ТОКЕНА",
  "selectChain": "выберите цепочку",
  "tokenMint": "ТОКЕН MINT",
  "tokenBurn": "ТОКЕН BURN",
  "powerByCoin98": "На платформе Coin98 Labs"
}