export default {
  "last7Days": "7 วันที่ผ่านมา",
  "fullyDiluted": "Fully Diluted Market Cap",
  "liquidityProvider": "Liquidity Provider Fee",
  "averagePrice": "ราคาเฉลี่ย",
  "priceImpact": "กระทบราคา",
  "minutes": "นาที",
  "gasSetting": "ตั้งค่า GAS",
  "searchNotFound": "ไม่พบการค้นหา",
  "noWalletFound": "ไม่พบกระเป๋า",
  "tradeSuccess": "การซื้อขายสำเร็จ",
  "confirmApprove": "ยืนยัน การอนุมัติ",
  "claimSwap": "ยืนยันการรับ",
  "confirmSwap": "ยืนยันการแลกเปลี่ยน",
  "txsFee": "ค่าธรรมเนียม: {{amount}} ~ {{amountUSD}}",
  "pleaseWaitOrder": "โปรดรอสักครู่ กำลังดำเนินการ",
  "pleaseWaitApprove": "โปรดรอสักครู่ กำลังรอการอนุมัติ",
  "approveSuccess": "ได้รับการอนุมัติ เรียบร้อยแล้ว",
  "pair": "คู่",
  "confirm": "ยืนยัน",
  "terminal": "เทอร์มินัล",
  "explorers": "สำรวจ",
  "community": "ชุมนุม",
  "d1": "1ว",
  "m1": "1ด",
  "w1": "1อ",
  "y1": "1ปี",
  "full": "เต็ม",
  "coin98Wallet": "กระเป๋า Coin98",
  "exchange": "ตลาดแลกเปลี่ยน",
  "invest": "ลงทุน",
  "dashboard": "แดชบอร์ด",
  "markets": "ตลาด",
  "confirmation": "ยืนยัน",
  "passphrase": "รหัสผ่าน",
  "success": "สำเร็จ!",
  "category": "หมวดหมู่",
  "platform": "แพลตฟอร์ม",
  "createNewWalletSuccessful": "สร้างกระเป๋าใหม่สำเร็จแล้ว!",
  "successfully": "สำเร็จแล้ว",
  "ok": "Ok",
  "error": "มีบางอย่างผิดพลาด!\n  โปรดลองอีกครั้ง",
  "create": "สร้าง",
  "restore": "กู้คืน",
  "cancel": "ยกเลิก",
  "receiveAddress": "รับที่อยู่",
  "sending": "กำลังส่ง",
  "manage": "จัดการ",
  "rankMarket": "#อันดับ {{rank}}",
  "max": "เต็ม",
  "edited": "แก้ไขแล้ว",
  "Error": "มีข้อผิดพลาด!",
  "search": "ค้นหา",
  "goBack": "ย้อนกลับ",
  "searchCurrency": "ค้นหา สกุลเงิน",
  "lendingBorrowing": "ปล่อยกู้/ยืม",
  "walletNotFound": "ไม่พบบัญชี",
  "addRestoreWallet": "โปรดเพิ่มกระเป๋าหรือกู้คืนก่อน",
  "wrongPass": "รหัสผ่านไม่ถูกต้อง",
  "yieldFarming": "ทำฟาร์ม",
  "defiStation": "DeFi สเตชั่น",
  "analytics": "วิเคราะห์",
  "nft": "NFT",
  "governance": "Governance",
  "coin98WalletMess": "จัดเก็บสินทรัพย์ดิจิทัล",
  "terminalMess": "เครื่องมือ All-In-One",
  "daapMess": "DeFi เกตเวย์",
  "exchangeMess": "แพลตฟอร์มการซื้อขาย",
  "crossChainMess": "แลกเปลี่ยนสินทรัพย์ข้าม Chains",
  "dashboardMess": "ทุกอย่างอยู่ภายใต้การควบคุมของคุณ",
  "marketMess": "ติดตามเทรนด์ล่าสุด",
  "lendingBorrowingMess": "รับดอกเบี้ยจากสินทรัพย์",
  "yieldFarmingMess": "ผลตอบแทนสูงสุดในสินทรัพย์ของคุณ",
  "defiStationMess": "มีรายได้ในขณะที่คุณนอนหลับ",
  "portfolioMess": "ติดตามผลการดำเนินงาน",
  "stankingMess": "ล็อคสินทรัพย์เพื่อรับรางวัล",
  "governanceMess": "โหวตข้อเสนอ",
  "lunaDex": "ตลาดซื้อขายแบบ Decentralized บน Solana และ Serum",
  "connectWallet": "เชื่อมต่อกระเป๋า",
  "login": "เข้าสู่ระบบ",
  "en": " อังกฤษ",
  "vi": " เวียดนาม",
  "email": "อีเมล",
  "enterEmail": "กรุณากรอกอีเมลของคุณ",
  "emailInvalid": "ที่อยู่อีเมลไม่ถูกต้อง",
  "userName": "ชื่อผู้ใช้",
  "yourUsername": "ชื่อผู้ใช้ ของคุณ",
  "displayName": "ชื่อที่แสดง",
  "yourDisplayName": "ชื่อที่แสดงของคุณ",
  "swaps": "แลกเปลี่ยน",
  "swap": "แลกเปลี่ยน",
  "totalValue": "มูลค่ารวม",
  "totalVolume": "ยอดการซื้อขายทั้งหมด",
  "tokenAmount": "จำนวนโทเค็น",
  "account": "บัญชี",
  "time": "เวลา",
  "infoAlert": "นี่คือข้อมูลของคุณ",
  "infoSuccess": "สร้างข้อมูลสำเร็จ",
  "infoError": "มีข้อผิดพลาดเนื่องจาก ...",
  "approveToken": "อนุมัติ {{nameTokenBuy}}",
  "buyToken": "ซื้อ {{nameTokenBuy}}",
  "loginSuccess": "เข้าสู่ระบบ สำเร็จ",
  "password": "รหัสผ่าน",
  "passInvalid": "รหัสผ่านต้องมีตัวเลขและตัวอักษรอย่างน้อย 6 ตัว",
  "confirmPassword": "ยืนยันรหัสผ่าน",
  "passNotMatch": "รหัสผ่านไม่ตรงกัน",
  "yourPassword": "รหัสผ่านของคุณ",
  "inputPassword": "กรุณาใส่รหัสผ่าน",
  "passRequired": "กรุณาใส่รหัสผ่านของคุณ",
  "emailVerificationsCode": "รหัสยืนยันอีเมลของคุณ",
  "referralCode": "รหัสผู้แนะนำ",
  "referExistError": "รหัสผู้แนะผิดพลาด",
  "nameBeenTaken": "ชื่อผู้ใช้ของคุณถูกใช้แล้ว",
  "nameAlreadyTaken": "ชื่อนี้ถูกใช้ไปแล้ว",
  "resetPass": "รีเซ็ตรหัสผ่านใหม่",
  "usernameRequired": "โปรดระบุชื่อผู้ใช้",
  "displaynameRequired": "โปรดระบุชื่อที่แสดง",
  "confirmPass": "โปรดยืนยันรหัสผ่าน",
  "confirmPassNotMatch": "รหัสผ่านไม่ตรงกัน",
  "youHaveBanned": "คุณถูกแบน!",
  "fraudBehaviorDevice": "คุณไม่ได้รับอนุญาตให้เข้าถึงข้อมูล\n  หรือโทรศัพท์ของคุณไม่เป็นไปตามมาตรฐานความปลอดภัยของเรา",
  "emailRequired": "โปรดกรอกอีเมล",
  "manageWallet": "จัดการกระเป๋า",
  "addWallet": "เพิ่มกระเป๋า",
  "restoreWallet": "กู้คืนกระเป๋า",
  "connectOtherWallet": "เชื่อมต่อกระเป๋าอื่นๆ",
  "send": "ส่ง",
  "receive": "รับ",
  "website": "เว็บไซต์",
  "smartContract": "สมาร์ทคอนแทรค",
  "allTimeLow": "จุดต่ำสุดที่เคยมีมา",
  "allTimeHigh": "จุดสูงสุดที่เคยมีมา",
  "high24h": "24ชม. สูงสุด",
  "low24h": "24ชม. ต่ำสุด",
  "circulatingSupply": "จำนวนเหรียญที่มีอยู่",
  "maxSupply": "จำนวนเหรียญทั้งหมด",
  "marketCap": "มูลค่าตลาด",
  "col24h": "24ชม. ปริมาณการซื้อขาย",
  "feeErr": "ยอดเงินหรือค่าธรรมเนียมแก๊สของคุณไม่เพียงพอ",
  "allWallet": "กระเป๋าทั้งหมด",
  "multiChain": "Multi-Chain",
  "ether": "Ether",
  "solana": "Solana",
  "binanceSmart": "Binance Smart",
  "polkadot": "Polkadot",
  "kusama": "Kusama",
  "heco": "Heco",
  "mustAtLeastDot": "คุณต้องมีอย่างน้อย 1 DOT เพื่อโอน",
  "enterAmountToStartTransaction": "ป้อนจำนวนเงินเพื่อเริ่มทำธุรกรรม",
  "amountErr": "ต้องน้อยกว่าหรือเท่ากับจำนวนเงินที่ใช้จ่ายได้",
  "walletName": "ชื่อกระเป๋า",
  "walletKey": "คีย์กระเป๋า",
  "walletKeyPhrase": "Mnenmonic Passphrase",
  "walletNameExist": "ชื่อกระเป๋านี้ถูกใช้ไปแล้ว",
  "copyDone": "ที่อยู่กระเป๋า {{value}} ถูกคัดลอกแล้ว",
  "onlySend": "ส่ง {{symbol}} ไปยังที่อยู่กระเป๋านี้เท่านั้น การส่งสินทรัพย์อื่นๆไปยังที่อยู่นี้จะทำให้สูญเสียสินทรัพย์",
  "amount": "จำนวน",
  "recipient": "ผู้รับ",
  "walletAddress": "ที่อยู่กระเป๋า",
  "confirmInfo": "ยืนยันข้อมูล",
  "noData": "ไม่มีข้อมูล",
  "message": "ข้อความ",
  "messageIsOptional": "ข้อความเป็นตัวเลือกเสริม",
  "inputRequired": "กรุณากรอกข้อมูลในช่องนี้",
  "verifyEmail": "ตรวจสอบอีเมล",
  "comfirmation": "ยืนยัน",
  "confirmDelete": "คุณแน่ใจหรือไม่ว่าจะลบกระเป๋าเงินนี้ออก?",
  "passphraseOrPrivateKey": "Passphrase หรือ Private Key",
  "verySlow": "ช้ามาก",
  "slow": "ช้า",
  "fast": "เร็ว",
  "superFast": "เร็วมาก",
  "standard": "มาตรฐาน",
  "gasWar": "Gas War",
  "starWar": "Star War",
  "tryAgain": "โปรดลองอีกครั้งในไม่กี่นาที",
  "txsFail": "การทำธุรกรรมล้มเหลว",
  "whitePaper": "Whitepaper",
  "timeOutTxs": "การทำธุรกรรมหมดเวลาหรือยังไม่ได้รับการยืนยัน โปรดรอสักครู่แล้วลองอีกครั้ง.",
  "minimum1Polkadot": "ที่อยู่กระเป๋าผู้รับต้องมีมากกว่า 1 DOT",
  "invalidAddr": "ที่อยู่ผู้รับไม่ถูกต้อง",
  "createAccount": "สร้างกระเป๋า",
  "createAccountSuccess": "สร้างกระเป๋าสำเร็จ",
  "areYouSureToCreateANewWallet": "คุณแน่ใจหรือไม่ว่าจะสร้างกระเป๋าใหม่?",
  "createWallet": "สร้างกระเป๋า",
  "phoneRegister": "หมายเลขโทรศัพท์ใช้สำหรับกระเป๋าที่ลงทะเบียนเท่านั้น",
  "clickContinue": "คลิก \"ดำเนินการต่อ\", เพื่อยอมรับข้อตกลง",
  "teamService": "เงื่อนไขการให้บริการกระเป๋าของ Coin98",
  "scanToLogin": "สแกนเพื่อเข้าสู่ระบบ",
  "forgotPass": "ลืมรหัสผ่านหรือไม่?",
  "reset": "รีเซ็ต",
  "continue": "ดำเนินการต่อ",
  "dintRecive": "ไม่ได้รับรหัสยืนยัน?",
  "resend": "ส่งอีกครั้ง",
  "restoreWalletSuccess": "กู้คืนกระเป๋าสำเร็จ!",
  "enjoy": "Enjoy",
  "register": "ลงทะเบียน",
  "sureNewWallet": "คุณแน่ใจหรือไม่ว่าจะสร้างกระเป๋าใหม่?",
  "myWallet": "กระเป๋าของฉัน",
  "understandChoose": "ฉันเข้าใจว่าหากฉันทำคีย์การกู้คืนหายฉันจะไม่สามารถเข้าถึงกระเป๋าของฉันได้",
  "done": "เสร็จแล้ว",
  "manageContact": "จัดการ คอนแทรค",
  "hiddenToken": "รายการโทเค็นที่ซ่อนอยู่",
  "setActive": "ตั้งค่าใช้งานอยู่",
  "copyAddress": "คัดลอกที่อยู่",
  "showQr": "แสดง QR Code",
  "showKey": "แสดงข้อมูล คีย์",
  "connectToWallet": "เชื่อมต่อกับกระเป๋า",
  "chooseWallet": "เลือกกระเป๋าของคุณ",
  "whatIsWallet": "อะไรคือกระเป๋า?",
  "totalBalance": "ยอดรวม",
  "otpWrong": "รหัส OTP ไม่ถูกต้อง",
  "asset": "สินทรัพย์",
  "symbol": "Symbol",
  "price": "ราคา",
  "balance": "คงเหลือ",
  "value": "มูลค่า",
  "market24": "24ชม",
  "address": "ที่อยู่",
  "maxSlippage": "Max Slippage",
  "termsOfService": "เงื่อนไขการให้บริการ",
  "volume": "Volume",
  "volume24": "24ชม. Volume",
  "selectWallet": "เลือกกระเป๋า",
  "selectedWallet": "เลือกกระเป๋าแล้ว",
  "addressIsCopy": "คัดลอกที่อยู่แล้ว",
  "orderFunding": "Order Funding",
  "orderVolume": "Order Volume",
  "youSend": "คุณส่ง",
  "youReceive": "คุณรับ",
  "all": "ทั้งหมด",
  "high": "สูง",
  "createContact": "สร้างคอนแทรค",
  "recommend": "แนะนำ",
  "comingSoon": "เร็ว ๆ นี้",
  "connected": "เชื่อมต่อแล้ว",
  "installCoin98Wallet": "ติดตั้งกระเป๋า Coin98 เพื่อจัดการกระเป๋า",
  "coin98WalletNotInstalled": "ยังไม่ได้ติดตั้งกระเป๋า Coin98",
  "connectCoin98Wallet": "เชื่อมต่อกับกระเป๋า Coin98",
  "BTCDominace": "การครอบงำของ BTC",
  "ETHDominace": "การครอบงำของ ETH",
  "rank": "อันดับ",
  "onWatchList": "บน {{num}} รายการเฝ้าดู",
  "token": "โทเค็น",
  "day": "วัน",
  "month": "เดือน",
  "week": "อาทิตย์",
  "year": "ปี",
  "custom": "กำหนดเอง",
  "uniswapPrice": "ราคา Uniswap",
  "low": "ต่ำ",
  "hight": "สูง",
  "fullDiluted": "Fully Diluted Market Cap",
  "volume24h": "Volume 24ชม",
  "totalSupply": "Supply ทั้งหมด",
  "viewDetail": "ดูรายละเอียด",
  "from": "จาก",
  "to": "ถึง",
  "willReceive": "คุณจะได้รับ ~ ",
  "fee": "ค่าธรรมเนียม",
  "balanceTotal": "ยอดรวม",
  "route": "เส้นทาง",
  "step": "ขั้นตอน",
  "finish": "เสร็จสิ้น",
  "swapHistory": "ประวัติการแลกเปลี่ยน",
  "coins": "เหรียญ",
  "watchList": "รายการเฝ้าดู",
  "contract": "คอนแทรค",
  "priceChange": "ราคาเปลี่ยนแปลง",
  "tradingVolume": "Volume การซื้อขาย",
  "marketCapRank": "อันดับ มูลค่าตลาด",
  "atHight": "จุดสูงสุดที่เคยมีมา",
  "atLow": "จุดต่ำสุดที่เคยมีมา",
  "sushiPrice": " สถิติราคา",
  "showRows": "แสดงแถว",
  "filters": "Filter",
  "overview": "ภาพรวม",
  "chart": "ชาร์ท",
  "cryptoAsset": "คริปโท",
  "historicalData": "ประวัติข้อมูล",
  "tradingView": "Trading View",
  "uniswapChart": "Uniswap Chart",
  "name": "ชื่อ",
  "liquidity": "สภาพคล่อง",
  "Volume": "Volume",
  "fees": "ค่าธรรมเนียม",
  "topPairs": "Top Pairs",
  "searchPairToken": "ค้นหาโทเค็นหรือคู่เหรียญ",
  "invalidPassPhrase": "โปรดตรวจสอบ Passphrase และ Private Key อีกครั้ง!",
  "needCreate": "จำเป็นต้องสร้างหรือนำเข้ากระเป๋า Solana ก่อน",
  "areYouCreate": "คุณแน่ใจหรือไม่ว่าจะสร้างกระเป๋าใหม่?",
  "willBeStored": "จะถูกเก็บไว้ในกระเป๋า {{nameChainWallet}}",
  "feeTransactionMust": "ธุรกรรมค่าธรรมเนียมต้องมีอย่างน้อย {{num}} {{symbol}}",
  "chainNotSupported": "ยังไม่ลองรับ Chain นี้",
  "nameChart": "{{symbol}} Chart",
  "areYouLogout": "คุณแน่ใจหรือไม่ว่าจะออกจากระบบ?",
  "vol24h": "24ชม. Vol",
  "volumeMarket": "Volume / Market Cap",
  "resetFilters": "รีเซ็ต Filter",
  "sureToSend": "คุณแน่ใจหรือไม่ว่าจะส่ง {{num}} {{symbol}} ไปถึง {{address}} ที่อยู่กระเป๋า?",
  "sumAddress": "{{num}} ที่อยู่กระเป๋า",
  "amountCannotZero": "จำนวนเงินต้องไม่เป็นศูนย์",
  "multiSend": "ส่งหลายรายการ",
  "totalAddress": "ที่อยู่ทั้งหมด",
  "addressEmpty": "โปรดระบุที่อยู่",
  "amountEmpty": "โปรดระบุจำนวนเงิน",
  "inputNotRequirements": "ไม่เป็นไปตามข้อกำหนด",
  "gwei": "Gwei",
  "hi": "Hi",
  "forTransaction": "สำหรับการทำธุรกรรม",
  "approveConversion": "อนุมัติการเปลี่ยนแปลง",
  "sendFound": "Send Fund",
  "waitForConfirm": "รอการยืนยัน",
  "rename": "เปลี่ยนชื่อ",
  "questionRename": "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนชื่อกระเป๋า",
  "questionImport": "แน่ใจหรือไม่ว่าต้องการนำเข้าที่อยู่และจำนวน",
  "alreadySend": "ส่งไปแล้ว",
  "resendOTP": "ส่ง OTP สำเร็จ",
  "fortmatic": "Fortmatic",
  "coinbaseWallet": "กระเป๋า Coinbase",
  "walletConnect": "Wallet Connect",
  "metaMask": "MetaMask",
  "dapper": "Dapper",
  "lattice": "Lattice",
  "private": "ส่วนตัว",
  "activeMultiChain": "เปิดใช้งานกระเป๋า Multi-Chain ",
  "activeChain": "เปิดใช้งานกระเป๋า {{chain}}",
  "removeWallet": "ลบ {{name}} กระเป๋า",
  "noMatchingResult": "ไม่พบผลลัพธ์ที่ตรงกัน",
  "areYouSureSend": "ส่ง {{num}} {{symbol}} <br/> {{address}}",
  "addressAmount": "กระเป๋า?จำนวน,กระเป๋า?จำนวน",
  "import": "นำเข้า",
  "addressAndAmount": "ที่อยู่และจำนวน",
  "gasPrice": "ราคา GAS",
  "transactionData": "ข้อมูลการทำธุรกรรม",
  "gasLimit": "GAS LIMIT",
  "nonce": "NONCE",
  "change24h": "% เปลี่ยนแปลง",
  "rankTop": "อันดับสูงสุด 100-200",
  "nameRank": "ชื่อ",
  "hour24Trading": "Volume การซื้อขายใน 24 ชั่วโมง",
  "lowHight24h": "24ชม. ต่ำ / สูง",
  "allTimeLowHigh": "ต่ำที่สุดที่เคยมีมา / สูง",
  "unlimitedApproval": "อนุมัติแบบ ไม่จำกัด",
  "estimateFee": "ค่าธรรมเนียมโดยประมาณ",
  "searchCoinOrPasteAnyToken": "ค้นหาเหรียญหรือโทเค็นอื่นๆ",
  "transactionDeadline": "Transaction Deadline",
  "owners": "เจ้าของ",
  "votingRate": "อัตราการโหวต",
  "withdraw": "ถอน",
  "update": "อัปเดต",
  "approved": "ได้รับการอนุมัติแล้ว",
  "waiting": "กำลังรอ",
  "totalFound": "ที่พบทั้งหมด",
  "totalOwner": "เจ้าของทั้งหมด",
  "awaitingApprove": "กำลังรอการอนุมัติ",
  "voteRate": "อัตราการโหวต",
  "owner": "เจ้าของ",
  "change": "เปลี่ยนแปลง",
  "ownersAddress": "ที่อยู่ของเจ้าของ",
  "votingPower": "อำนาจการโหวต",
  "type": "ประเภท",
  "date": "วันที่",
  "status": "สถานะ",
  "process": "Process",
  "transactionId": "transaction ID",
  "creator": "ผู้สร้าง",
  "wellcome": "ยินดีต้อนรับสู่",
  "multisig": "กระเป๋า Multisig",
  "createNew": "สร้างใหม่",
  "addOwner": "เพิ่มเจ้าของ",
  "addVoteRate": "เพิ่มอัตราการโหวต",
  "multisigWalletName": "Multisignature Wallet name",
  "c98Private": "C98 กองทุนส่วนบุคคล",
  "successSent": "ส่งเรียบร้อยแล้ว",
  "removeOwner": "ลบเจ้าของ",
  "newVoteRate": "อัตราการโหวตใหม่",
  "newVotePower": "พลังโหวตใหม่",
  "poweredByCoin98": "Powered by Coin98 Wallet Engine",
  "lessThan": "น้อยกว่า",
  "noSpace": "No space",
  "characters": "ตัวอักษร",
  "createTokenError": "สร้างโทเค็น Issuer ผิดพลาด",
  "createTokenSuccess": "สร้างโทเค็น Issuer สำเร็จ",
  "confirmCreateTokenIssue": "คุณแน่ใจหรือไม่ว่าจะยืนยัน Issuer โทเค็น?",
  "pleaseInput": "กรุณาใส่ข้อมูล",
  "invalidAddrWallet": "ที่อยู่กระเป๋าไม่ถูกต้อง",
  "wallet": "กระเป๋า",
  "tokenName": "ชื่อโทเค็น",
  "tokenSymbol": "อักษรย่อโทเค็น",
  "decimalPoint": "จำนวนจุดทศนิยม",
  "ownerAddress": "ที่อยู่ของเจ้าของ",
  "tokenLogo": "โลโก้ของโทเค็น",
  "selectChain": "เลือก Chain",
  "tokenMint": "สร้างโทเค็น",
  "tokenBurn": "เผาโทเค็น",
  "powerByCoin98": "Powered by Coin98 Labs"
}