export default {
  "last7Days": "SON 7 GUN",
  "fullyDiluted": "Seyreltilmiş Piyasa Değeri",
  "liquidityProvider": "Likidite Sağlayıcı Ücreti",
  "averagePrice": "Ortalama Fiyat",
  "priceImpact": "Fiyata Etki",
  "minutes": "dakika",
  "gasSetting": "Gas Ayarı",
  "searchNotFound": "Arama Bulunamadı",
  "noWalletFound": "Cüzdan Bulunamadı",
  "tradeSuccess": "Emir Başarılı",
  "confirmApprove": "Uygunluk Onayı",
  "claimSwap": "Talep Onayı",
  "confirmSwap": "Swap Onayı",
  "txsFee": "Ücret: {{amount}} ~ {{amountUSD}}",
  "pleaseWaitOrder": "Emrin tamamlanması için lütfen bekleyin",
  "pleaseWaitApprove": "Onayın tamamlanması için lütfen bekleyin",
  "approveSuccess": "İşlem Başarılı",
  "pair": "Parite",
  "confirm": "Onay",
  "terminal": "Terminal",
  "explorers": "Explorer",
  "community": "Topluluk",
  "d1": "1G",
  "m1": "1A",
  "w1": "1H",
  "y1": "1Y",
  "full": "Full",
  "coin98Wallet": "Coin98 Cüzdanı",
  "exchange": "Borsa",
  "invest": "Yatırım",
  "dashboard": "Gösterge Paneli",
  "markets": "Marketler",
  "confirmation": "Onay",
  "passphrase": "Passphrase",
  "success": "Başarılı!",
  "category": "Kategori",
  "platform": "Platform",
  "createNewWalletSuccessful": "Yeni Cüzdan Başarıyla Oluşturuldu!",
  "successfully": "Başarıyla",
  "ok": "Tamam",
  "error": "Bir şey ters gitti!\n  Lütfen daha sonra tekrar deneyin",
  "create": "Yarat",
  "restore": "Restore et",
  "cancel": "İptal",
  "receiveAddress": "Alıcı Adresi",
  "sending": "Gönderiliyor",
  "manage": "Yönet",
  "rankMarket": "#Sıralama {{rank}}",
  "max": "MAX",
  "edited": "Düzenlendi",
  "Error": "Hata!",
  "search": "Arama",
  "goBack": "Geri Dön",
  "searchCurrency": "Para Birimi Arama",
  "lendingBorrowing": "Ödünç Alma/Verme",
  "walletNotFound": "Cüzdan Bulunamadı",
  "addRestoreWallet": "Lütfen önce bir cüzdan ekleyin yada restore edin",
  "wrongPass": "Hatalı Şifre",
  "yieldFarming": "Getiri Çiftçiliği",
  "defiStation": "DeFi İstasyonu",
  "analytics": "Analitiklier",
  "nft": "NFT",
  "governance": "Yönetişim",
  "coin98WalletMess": "Dijital Varlıklarınızı Saklayın",
  "terminalMess": "Hepsi bir arada Alet Çantası",
  "daapMess": "DeFi Geçidi",
  "exchangeMess": "Takas Platformu",
  "crossChainMess": "Varlıklarınızı birden çok zincir arasında değiştirin",
  "dashboardMess": "Her şey sizin kontrolünüz altında",
  "marketMess": "En son trendleri takip edin",
  "lendingBorrowingMess": "Varlıklarınızdan getiri elde edin",
  "yieldFarmingMess": "Varlıklarınızın getirisini en üst düzeye çıkarın",
  "defiStationMess": "Uyurken bile para kazanın",
  "portfolioMess": "Varlıkların performansını izleyin",
  "stankingMess": "Lock assets to receive rewards",
  "governanceMess": "Ödüller için varlıklarınızı kilitleyin",
  "lunaDex": "Solana ve Serum üzerine kurulu merkeziyetsiz borsa ",
  "connectWallet": "Cüzdanınızı Bağlayın",
  "login": "Oturum aç",
  "en": " İngilizce",
  "vi": " Vietnamca",
  "email": "E-mail",
  "enterEmail": "Lütfen E-Mail Adresinizi Girin",
  "emailInvalid": "Geçersiz E-Mail Adresi",
  "userName": "Kullanıcı adı",
  "yourUsername": "Kullanıcı Adınız",
  "displayName": "Görünen İsim",
  "yourDisplayName": "Görünen İsminiz",
  "swaps": "Swaplar",
  "swap": "Swap",
  "totalValue": "Toplam Değer",
  "totalVolume": "Toplam Hacim",
  "tokenAmount": "Token Miktarı",
  "account": "Hesap",
  "time": "Zaman",
  "infoAlert": "Bilgileriniz",
  "infoSuccess": "Başarıyla Oluşturuldu",
  "infoError": "... yüzünden hata",
  "approveToken": "Onay {{nameTokenBuy}}",
  "buyToken": "Satın al {{nameTokenBuy}}",
  "loginSuccess": "Giriş Başarılı",
  "password": "Şifre",
  "passInvalid": "Şifreniz harf ve rakamlardan oluşmalı ve en az 6 karakter içermelidir.",
  "confirmPassword": "Şifreyi Onayla",
  "passNotMatch": "Şifre Eşleşmedi",
  "yourPassword": "Şifreniz",
  "inputPassword": "Lütfern Şifrenizi Giriniz",
  "passRequired": "Şifre girmeniz gerekmektedir",
  "emailVerificationsCode": "E-Mail Onay Kodunuz",
  "referralCode": "Referans Kodunuz",
  "referExistError": "Böyle bir ID bulunmuyor",
  "nameBeenTaken": "Kullanıcı adınız alınmış",
  "nameAlreadyTaken": "Bu isim alınmış",
  "resetPass": "Yeniden Parola Oluştur",
  "usernameRequired": "Kullanıcı Adınız Gerekmektedir",
  "displaynameRequired": "Görünen İsminiz Gerekmektedir",
  "confirmPass": "Şifre onayı gerekmektedir",
  "confirmPassNotMatch": "Şifre onayı eşleşmedi",
  "youHaveBanned": "Banlandınız!",
  "fraudBehaviorDevice": "Cihaz bilgilerine erişime izin vermediniz\n  yada telefonunuz gerekli güvenlik standartlarına haiz değil",
  "emailRequired": "E-mail gerekli",
  "manageWallet": "Cüzdan Yönetimi",
  "addWallet": "Cüzdan Ekle",
  "restoreWallet": "Cüzdanı Restore et",
  "connectOtherWallet": "Başka Cüzdana Bağlan",
  "send": "Gönder",
  "receive": "Al",
  "website": "Web sitesi",
  "smartContract": "Akıllı Kontrat",
  "allTimeLow": "Tüm Zamanların En Düşüğü",
  "allTimeHigh": "Tüm Zamanların En Yükseği",
  "high24h": "24S Yüksek Seviye",
  "low24h": "24S Düşük Seviye",
  "circulatingSupply": "Dolaşımdaki Arz",
  "maxSupply": "Maksimum Arz",
  "marketCap": "Piyasa Değeri",
  "col24h": "24S Hacim",
  "feeErr": "Bakiyeniz yada gas ücretiniz yetersiz",
  "allWallet": "Tüm Cüzdanlar",
  "multiChain": "Çoklu Zincir",
  "ether": "Ether",
  "solana": "Solana",
  "binanceSmart": "Binance Smart",
  "polkadot": "Polkadot",
  "kusama": "Kusama",
  "heco": "Heco",
  "mustAtLeastDot": "Gönderi için cüzdanda en az 1 DOT kalmalı",
  "enterAmountToStartTransaction": "İşlemi başlatmak için tutarı girin",
  "amountErr": "Harcanabilir tutardan daha az veya ona eşit varlığınız olmalıdır",
  "walletName": "Cüzdan Adı",
  "walletKey": "Cüzdan Anahtarı",
  "walletKeyPhrase": "Mnemonic Anahtar Kelime",
  "walletNameExist": "Cüzdan Adı Zaten Kullanımda",
  "copyDone": "Adres {{value}} Kopyalandı",
  "onlySend": "Bu ardese sadece {{symbol}} gönderiniz. Bu adrese başka herhangi bir varlık göndermek, varlık kaybına neden olur",
  "amount": "Tutar",
  "recipient": "Alıcı",
  "walletAddress": "Cüzdan Adresi",
  "confirmInfo": "Bilgiyi Onaylayın",
  "noData": "Veri Yok",
  "message": "Mesaj",
  "messageIsOptional": "Mesaj Opsiyoneldir",
  "inputRequired": "Lütfen bu bölümü doldurun",
  "verifyEmail": "E-Mailinizi Onaylayın",
  "comfirmation": "Doğrulama",
  "confirmDelete": "Bu cüzdanı silmek istediğinizden eminmisiniz?",
  "passphraseOrPrivateKey": "Anahtar Kelime Yada Özel Anahtar",
  "verySlow": "Çok Yavaş",
  "slow": "Yavaş",
  "fast": "Hızlı",
  "superFast": "Çok Hızlı",
  "standard": "Standart",
  "gasWar": "Gas Savaşı",
  "starWar": "Star Savaşı",
  "tryAgain": "Lütfen birkaç dakika içinde tekrar deneyin",
  "txsFail": "İşlem başarısız",
  "whitePaper": "Whitepaper",
  "timeOutTxs": "İşlem zaman aşımına uğradı veya onaylanmadı, lütfen biraz bekleyin ve tekrar deneyin.",
  "minimum1Polkadot": "Alıcı adresinin 1den fazla DOTa sahip olması gerekir",
  "invalidAddr": "Geçersiz alıcı adresi",
  "createAccount": "Hesap Yarat",
  "createAccountSuccess": "Hesap Yaratma Başarılı",
  "areYouSureToCreateANewWallet": "Yeni cüzdan yaratmak istediğinizden eminmisiniz?",
  "createWallet": "Cüzdan Yarat",
  "phoneRegister": "Telefon numarası yalnızca bir kayıtlı hesap için kullanılır",
  "clickContinue": "\"Devam et\" i tıklayarak şunları kabul edersiniz:",
  "teamService": "Coin98 Cüzdanı Hizmet Şartları",
  "scanToLogin": "Giriş için Tarayın",
  "forgotPass": "Parolanızı mı unuttunuz?",
  "reset": "Reset",
  "continue": "Devam",
  "dintRecive": "Doğrulama kodunu almadınız mı?",
  "resend": "Tekrar Gönder",
  "restoreWalletSuccess": "Cüzdan başarıyla restore edildi!",
  "enjoy": "Keyfini Çıkarın!",
  "register": "Kaydol",
  "sureNewWallet": "Yeni bir cüzdan oluşturmak istediğinizden emin misiniz?",
  "myWallet": "Cüzdanım",
  "understandChoose": "Kurtarma anahtarımı kaybedersem cüzdanıma erişemeyeceğimi biliyorum",
  "done": "Yapıldı",
  "manageContact": "Kişileri yönet",
  "hiddenToken": "Gizli Token Listesi",
  "setActive": "Etkin Olarak Ayarla",
  "copyAddress": "Adresi Kopyala",
  "showQr": "QR Kodunu Göster",
  "showKey": "Anahtar Bilgisini Göster",
  "connectToWallet": "Bir Cüzdana Bağlan",
  "chooseWallet": "Cüzdanınızı Seçin",
  "whatIsWallet": "Cüzdan Nedir?",
  "totalBalance": "Toplam Bakiye",
  "otpWrong": "Geçersiz OTP kodu",
  "asset": "Varlık",
  "symbol": "Sembol",
  "price": "Fiyat",
  "balance": "Bakiye",
  "value": "Değer",
  "market24": "24S",
  "address": "Adres",
  "maxSlippage": "Maks Slipaj",
  "termsOfService": "Kullanım Şartları",
  "volume": "Hacim",
  "volume24": "24S Hacim",
  "selectWallet": "Cüzdan Seçin",
  "selectedWallet": "Seçilen Cüzdan",
  "addressIsCopy": "Adres Kopyalandı",
  "orderFunding": "Emir Fonlaması",
  "orderVolume": "Emir Hacmi",
  "youSend": "Gönderdiniz",
  "youReceive": "Aldınız",
  "all": "Tüm",
  "high": "Yüksek",
  "createContact": "Kişi Oluştur",
  "recommend": "Tavsiye",
  "comingSoon": "Yakında Geliyor",
  "connected": "Bağlandı",
  "installCoin98Wallet": "Yönetim cüzdanı için Coin98 Walletı yükleyin",
  "coin98WalletNotInstalled": "Coin98 Cüzdanı yüklenmemiş",
  "connectCoin98Wallet": "Coin98 Cüzdanına Bağlanın",
  "BTCDominace": "BTC Dominans",
  "ETHDominace": "ETH Dominans",
  "rank": "Sıralama",
  "onWatchList": "{{num}} İzleme Listesinde",
  "token": "Token",
  "day": "gün",
  "month": "ay",
  "week": "hafta",
  "year": "yıl",
  "custom": "özel",
  "uniswapPrice": "Uniswap Fiyatı",
  "low": "düşük",
  "hight": "Yükseklik",
  "fullDiluted": "Tamamen Seyreltilmiş Piyasa Değeri",
  "volume24h": "24S Hacim",
  "totalSupply": "Toplam Arz",
  "viewDetail": "Detayları Göster",
  "from": "Buradan",
  "to": "Buraya",
  "willReceive": "Alacağınız ~ ",
  "fee": "Ücret",
  "balanceTotal": "Toplam Bakiye",
  "route": "Rota",
  "step": "Adım",
  "finish": "Bitir",
  "swapHistory": "Swap Geçmişi",
  "coins": "Coinler",
  "watchList": "İzleme Listesi",
  "contract": "Kontrat",
  "priceChange": "Fiyat Değişimi",
  "tradingVolume": "Alım-Stım Hacmi",
  "marketCapRank": "Market Sıralaması",
  "atHight": "Tüm Zamanların En Yüksek Seviyesi",
  "atLow": "Tüm Zamanların En Düşük Seviyesi",
  "sushiPrice": " Fiyat İstatistikleri",
  "showRows": "Satırları göster",
  "filters": "Filtrele",
  "overview": "Genel Bakış",
  "chart": "Grafik",
  "cryptoAsset": "Kriptolar",
  "historicalData": "Geçmiş Veri",
  "tradingView": "Trading View",
  "uniswapChart": "Uniswap Grafiği",
  "name": "İsim",
  "liquidity": "Likidite",
  "Volume": "Hacim",
  "fees": "ücret",
  "topPairs": "Popüler Çiftler",
  "searchPairToken": "Parite ve token araması",
  "invalidPassPhrase": "Lütfen Parolanızı veya Özel Anahtarınızı tekrar kontrol edin!",
  "needCreate": "Önce Solana Cüzdanını oluşturmanız veya içe aktarmanız gerekir",
  "areYouCreate": "Yeni bir cüzdan oluşturmak istediğinizden emin misiniz?",
  "willBeStored": "{{nameChainWallet}} cüzdanınızda saklanacak",
  "feeTransactionMust": "İşlem ücreti en az {{num}} {{symbol}} olmalıdır ",
  "chainNotSupported": "Zincir henüz desteklenmemektedir",
  "nameChart": "{{symbol}} Grafiği",
  "areYouLogout": "Çıkış yapmak istediğinize emin misiniz?",
  "vol24h": "24S Hacim",
  "volumeMarket": "Hacim / Market Değeri",
  "resetFilters": "Filtreyi Sıfırla",
  "sureToSend": "{{address}} Adresine {{num}} {{symbol}} göndermek istediğinize eminmisiniz",
  "sumAddress": "{{num}} Adresi",
  "amountCannotZero": "Değer sıfır olamaz",
  "multiSend": "Çoklu Gönder",
  "totalAddress": "Toplam Adres",
  "addressEmpty": "Adresler boş olamaz",
  "amountEmpty": "Değer boş olamaz",
  "inputNotRequirements": "Girdi, gereksinimleri karşılamıyor",
  "gwei": "Gwei",
  "hi": "Merhaba!",
  "forTransaction": "İşlem İçin",
  "approveConversion": "Dönüşümü Onayla",
  "sendFound": "Fon Gönder",
  "waitForConfirm": "Onayları Bekleyin",
  "rename": "Yeniden Adlandır",
  "questionRename": "Cüzdanı yeniden adlandırmak istediğinizden emin misiniz?",
  "questionImport": "Adres ve tutarı içe aktarmak istediğinizden emin misiniz?",
  "alreadySend": "Zaten Gönderildi",
  "resendOTP": "OTP başarıyla yeniden gönderildi",
  "fortmatic": "Fortmatic",
  "coinbaseWallet": "Coinbase Cüzdanı",
  "walletConnect": "Cüzdan Bağla",
  "metaMask": "MetaMask",
  "dapper": "Dapper",
  "lattice": "Lattice",
  "private": "Özel",
  "activeMultiChain": "Çok Zincirli Cüzdanı etkinleştirin",
  "activeChain": " {{chain}} cüzdanını aktive et",
  "removeWallet": " {{name}} cüzdanını kaldır",
  "noMatchingResult": "Eşleşen sonuç yok",
  "areYouSureSend": "Gönderi {{num}} {{symbol}} <br/> {{address}}",
  "addressAmount": "adres?tutar,adres?tutar",
  "import": "İçe Aktar",
  "addressAndAmount": "Adres ve Tutar",
  "gasPrice": "GAS fiyatı",
  "transactionData": "IŞLEM VERİLERİ",
  "gasLimit": "GAS LIMITI",
  "nonce": "OLMAYAN",
  "change24h": "% değişim",
  "rankTop": "Sıralama Top 100-200",
  "nameRank": "isim",
  "hour24Trading": "24 Saatlik İşlem Hacmi",
  "lowHight24h": "24S Düşük / Yüksek",
  "allTimeLowHigh": "Tüm Zamanların Düşük / Yüksek",
  "unlimitedApproval": "Sınırsız Onay",
  "estimateFee": "Tahmini Ücret",
  "searchCoinOrPasteAnyToken": "Coin arayın veya herhangi bir coin yapıştırın",
  "transactionDeadline": "İşlem Son Tarihi",
  "owners": "Kullanıcı",
  "votingRate": "Oylama Oranı",
  "withdraw": "Çekme",
  "update": "Update",
  "approved": "Onaylı",
  "waiting": "Bekleniyor",
  "totalFound": "Toplan Bulunan",
  "totalOwner": "Toplam Kullanıcı",
  "awaitingApprove": "Onay Bekleniyor",
  "voteRate": "Oy Oranı",
  "owner": "Sahibi",
  "change": "Değişim",
  "ownersAddress": "Sahibinin Adresi",
  "votingPower": "Oylama Gücü",
  "type": "Tip",
  "date": "Gün",
  "status": "Durum",
  "process": "İşlem",
  "transactionId": "İşlem IDsi",
  "creator": "Yaratıcı",
  "wellcome": "Hoşgeldiniz",
  "multisig": "Multisig Cüzdan",
  "createNew": "Yeni Yarat",
  "addOwner": "Kullanıcı Ekle",
  "addVoteRate": "Oylama Oranı Ekle",
  "multisigWalletName": "Multisignature Cüzdan Adı",
  "c98Private": "C98 Özel Fonu",
  "successSent": "Başarıyla Gönderildi",
  "removeOwner": "Kullanıcıyı Kaldır",
  "newVoteRate": "Yeni Oy Oranı",
  "newVotePower": "Yeni Oy Gücü",
  "poweredByCoin98": "Coin98 Wallet Engine tarafından desteklenmektedir",
  "lessThan": "Daha az",
  "noSpace": "Yer Yok",
  "characters": "karakterler",
  "createTokenError": "Token Üreticisi Oluşturma Hatası",
  "createTokenSuccess": "Token Üreticisi Oluşturma Başarılı",
  "confirmCreateTokenIssue": "Token Üreticisini onayladığınızdan emin misiniz??",
  "pleaseInput": "Lütfen Giriniz",
  "invalidAddrWallet": "Geçersiz Adres",
  "wallet": "Cüzdan",
  "tokenName": "TOKEN ADI",
  "tokenSymbol": "TOKEN SEMBOLÜ",
  "decimalPoint": "ONDALIĞI",
  "ownerAddress": "SAHİP ADRESİ",
  "tokenLogo": "TOKEN LOGOSU",
  "selectChain": "zincir seçin",
  "tokenMint": "TOKEN BAS",
  "tokenBurn": "TOKEN YAK",
  "powerByCoin98": "Coin98 Labs tarafından desteklenmektedir"
}