export default {
  "last7Days": "7 NGÀY",
  "fullyDiluted": "Vốn hoá thị trường pha loãng",
  "liquidityProvider": "Phí cung cấp thanh khoản",
  "averagePrice": "Giá trung bình",
  "priceImpact": "Tác động giá",
  "minutes": "phút",
  "gasSetting": "Cài đặt Gas",
  "searchNotFound": "Không tìm thấy",
  "noWalletFound": "Chưa kết nối ví",
  "tradeSuccess": "Đặt lệnh thành công",
  "confirmApprove": "Xác nhận duyệt giao dịch",
  "claimSwap": "Xác nhận giao dịch",
  "confirmSwap": "Xác nhận giao dịch",
  "txsFee": "Phí: {{amount}} ~ {{amountUSD}}",
  "pleaseWaitOrder": "Giao dịch đang được thực hiện, vui lòng đợi",
  "pleaseWaitApprove": "Vui lòng đợi giao dịch được duyệt",
  "approveSuccess": "Duyệt thành công",
  "pair": "Cặp",
  "confirm": "Xác nhận",
  "terminal": "Terminal",
  "explorers": "Explorers",
  "community": "Cộng đồng",
  "d1": "1D",
  "m1": "1M",
  "w1": "1W",
  "y1": "1Y",
  "full": "Đầy đủ",
  "coin98Wallet": "Coin98 Wallet",
  "exchange": "Giao dịch",
  "invest": "Đầu tư",
  "dashboard": "Bảng điều khiển",
  "markets": "Thị trường",
  "confirmation": "Xác nhận",
  "passphrase": "Passphrase",
  "success": "Thành công!",
  "category": "Hạng mục",
  "platform": "Nền tảng",
  "createNewWalletSuccessful": "Tạo ví mới thành công!",
  "successfully": "Thành công",
  "ok": "Ok",
  "error": "Đã xảy ra lỗi!\n  Vui lòng thử lại sau",
  "create": "Tạo mới",
  "restore": "Khôi phục",
  "cancel": "Hủy bỏ",
  "receiveAddress": "Ví nhận",
  "sending": "Đang gửi",
  "manage": "Quản lý",
  "rankMarket": "#Xếp hạng {{rank}}",
  "max": "MAX",
  "edited": "Đã sửa",
  "Error": "Lỗi!",
  "search": "Tìm kiếm",
  "goBack": "Trở lại",
  "searchCurrency": "Tìm tài sản mã hóa",
  "lendingBorrowing": "Vay/Cho vay",
  "walletNotFound": "Không tìm thấy ví",
  "addRestoreWallet": "Vui lòng thêm hoặc khôi phục ví trước",
  "wrongPass": "Mật khẩu không đúng",
  "yieldFarming": "Yield Farming",
  "defiStation": "DeFi Station",
  "analytics": "Phân tích",
  "nft": "NFT",
  "governance": "Quản trị",
  "coin98WalletMess": "Lưu trữ tài sản mã hóa",
  "terminalMess": "Bộ tổng hợp công cụ",
  "daapMess": "DeFi Gateway",
  "exchangeMess": "Nền tảng giao dịch",
  "crossChainMess": "Hoán đổi tài sản giữa các blockchain",
  "dashboardMess": "Mọi thứ trong tầm kiểm soát của bạn",
  "marketMess": "Cập nhật xu hướng mới",
  "lendingBorrowingMess": "Kiếm lợi nhuận trên tài sản",
  "yieldFarmingMess": "Tối đa hoá lợi suất trên tài sản",
  "defiStationMess": "Kiếm tiền thụ động",
  "portfolioMess": "Theo dõi hiệu suất tài sản",
  "stankingMess": "Khoá tài sản để nhận thưởng",
  "governanceMess": "Bỏ phiếu cho các đề xuất",
  "lunaDex": "Sàn phi tập trung trên Solana và Serum",
  "connectWallet": "Kết nối ví",
  "login": "Đăng nhập",
  "en": " Tiếng Anh",
  "vi": " Tiếng Việt",
  "email": "Email",
  "enterEmail": "Vui lòng nhập Email",
  "emailInvalid": "Email không hợp lệ",
  "userName": "Tên người dùng",
  "yourUsername": "Tên người dùng",
  "displayName": "Tên hiển thị",
  "yourDisplayName": "Tên hiển thị",
  "swaps": "Đổi",
  "swap": "Đổi",
  "totalValue": "Tổng giá trị",
  "totalVolume": "Tổng khối lượng",
  "tokenAmount": "Lượng token",
  "account": "Tài khoản",
  "time": "Thời gian",
  "infoAlert": "Đây là thông tin của bạn",
  "infoSuccess": "Khởi tạo thành công",
  "infoError": "Đã xảy ra lỗi vì ...",
  "approveToken": "Duyệt {{nameTokenBuy}}",
  "buyToken": "Mua {{nameTokenBuy}}",
  "loginSuccess": "Đăng nhập thành công",
  "password": "Mật khẩu",
  "passInvalid": "Mật khẩu cần có ít nhất 6 ký tự, bao gồm số và chữ",
  "confirmPassword": "Xác nhận mật khẩu",
  "passNotMatch": "Mật khẩu không khớp",
  "yourPassword": "Mật khẩu của bạn",
  "inputPassword": "Vui lòng nhập mật khẩu",
  "passRequired": "Mã xác thực email của bạn",
  "emailVerificationsCode": "Mã xác thực email của bạn",
  "referralCode": "Mã giới thiệu",
  "referExistError": "ID không tồn tại",
  "nameBeenTaken": "Tên người dùng đã tồn tại",
  "nameAlreadyTaken": "Tên này đã được sử dụng",
  "resetPass": "Cài mật khẩu mới",
  "usernameRequired": "Yêu cầu tên người dùng",
  "displaynameRequired": "Yêu cầu tên hiển thị",
  "confirmPass": "Yêu cầu xác nhận mật khẩu",
  "confirmPassNotMatch": "Mật khẩu xác nhận chưa đúng",
  "youHaveBanned": "Bạn đã bị cấm!",
  "fraudBehaviorDevice": "Bạn chưa cấp quyền tiếp cận thông tin trên thiết bị\n  hoặc điện thoại của bạn không đáp ứng tiêu chuẩn an toàn của chúng tôi",
  "emailRequired": "Yêu cầu Email",
  "manageWallet": "Quản lý ví",
  "addWallet": "Thêm ví",
  "restoreWallet": "Khôi phục ví",
  "connectOtherWallet": "Kết nối ví khác",
  "send": "Gửi",
  "receive": "Nhận",
  "website": "Website",
  "smartContract": "Smart Contract",
  "allTimeLow": "Thấp nhất mọi thời điểm",
  "allTimeHigh": "Cao nhất mọi thời điểm",
  "high24h": "Cao trong 24h",
  "low24h": "Thấp trong 24h",
  "circulatingSupply": "Cung lưu hành",
  "maxSupply": "Cung tối đa",
  "marketCap": "Vốn hóa",
  "col24h": "KL 24h",
  "feeErr": "Bạn không đủ số dư hoặc phí giao dịch",
  "allWallet": "Tất cả các ví",
  "multiChain": "Multi-Chain",
  "ether": "Ether",
  "solana": "Solana",
  "binanceSmart": "Binance Smart",
  "polkadot": "Polkadot",
  "kusama": "Kusama",
  "heco": "Heco",
  "mustAtLeastDot": "Ví của bạn cần để lại ít nhất 1 DOT để thực hiện lệnh gửi",
  "enterAmountToStartTransaction": "Nhập số lượng để giao dịch",
  "amountErr": "Cần nhỏ hơn hoặc bằng số lượng được phép giao dịch",
  "walletName": "Tên ví",
  "walletKey": "Key của Ví",
  "walletKeyPhrase": "Mnenmonic Passphrase",
  "walletNameExist": "Tên ví đã tồn tại",
  "copyDone": "Địa chỉ {{value}} đã được sao chép",
  "onlySend": "Chỉ được gửi {{symbol}} đến địa chỉ này. Nếu gửi nhầm token khác đến địa chỉ này, bạn có thể sẽ bị tài sản.",
  "amount": "Số lượng",
  "recipient": "Ví nhận",
  "walletAddress": "Địa chỉ",
  "confirmInfo": "Xác nhận thông tin",
  "noData": "Không có dữ liệu",
  "message": "Lời nhắn",
  "messageIsOptional": "Mục này không bắt buộc",
  "inputRequired": "Vui lòng điền thông tin",
  "verifyEmail": "Xác thực Email",
  "comfirmation": "Xác nhận",
  "confirmDelete": "Bạn chắc chắn muốn gỡ ví này?",
  "passphraseOrPrivateKey": "Passphrase hoặc Private Key",
  "verySlow": "Rất chậm",
  "slow": "Chậm",
  "fast": "Nhanh",
  "superFast": "Siêu nhanh",
  "standard": "Tiêu chuẩn",
  "gasWar": "Gas War",
  "starWar": "Star War",
  "tryAgain": "Vui lòng thử lại sau ít phút",
  "txsFail": "Giao dịch không thành công",
  "whitePaper": "Whitepaper",
  "timeOutTxs": "Giao dịch hết thời gian chờ hoặc chưa được xác nhận, vui lòng thử lại sau giây lát.",
  "minimum1Polkadot": "Địa chỉ nhận cần có sẵn ít nhất 1 DOT",
  "invalidAddr": "Địa chỉ nhận không hợp lệ",
  "createAccount": "Tạo tài khoản",
  "createAccountSuccess": "Tạo tài khoản thành công",
  "areYouSureToCreateANewWallet": "Bạn chắc chắn muốn tạo ví mới?",
  "createWallet": "Tạo tài khoản",
  "phoneRegister": "SĐT chỉ được dùng cho tài khoản đã đăng ký",
  "clickContinue": "Bằng cách nhấp vào \"Tiếp tục\", bạn đồng ý tuân theo",
  "teamService": "Điều Khoản Dịch Vụ của Coin98 Wallet",
  "scanToLogin": "Scan để đăng nhập",
  "forgotPass": "Bạn đã quên mật khẩu?",
  "reset": "Cài lại",
  "continue": "Tiếp tục",
  "dintRecive": "Bạn chưa nhận được mã xác thực?",
  "resend": "Gửi lại",
  "restoreWalletSuccess": "Khôi phục ví thành công!",
  "enjoy": "Trải nghiệm ngay",
  "register": "Đăng ký",
  "sureNewWallet": "Bạn chắc chắn muốm tạo ví mới?",
  "myWallet": "Ví của tôi",
  "understandChoose": "Tôi hiểu rõ nếu đánh mất khóa khôi phục, tôi sẽ không thể truy cập được vào ví của mình",
  "done": "Hoàn thành",
  "manageContact": "Quản lý danh bạ",
  "hiddenToken": "DS Token Ẩn",
  "setActive": "Kích hoạt",
  "copyAddress": "Chép địa chỉ",
  "showQr": "Hiển thị mã QR",
  "showKey": "Hiển thị Key",
  "connectToWallet": "Kết nối ví",
  "chooseWallet": "Chọn ví",
  "whatIsWallet": "Ví là gì?",
  "totalBalance": "Tổng số dư",
  "otpWrong": "Mã OTP không hợp lệ",
  "asset": "Tài sản",
  "symbol": "Biểu tượng",
  "price": "Giá",
  "balance": "Số dư",
  "value": "Giá trị",
  "market24": "24h thị trường",
  "address": "Địa chỉ",
  "maxSlippage": "Trượt giá tối đa",
  "termsOfService": "Điều khoản dịch vụ",
  "volume": "Khối lượng",
  "volume24": "KL 24h",
  "selectWallet": "Chọn ví",
  "selectedWallet": "Ví đã được chọn",
  "addressIsCopy": "Địa chỉ đã được sao chép",
  "orderFunding": "Quỹ lệnh",
  "orderVolume": "Khối lượng lệnh",
  "youSend": "Bạn gửi",
  "youReceive": "Bạn nhận",
  "all": "Tất cả",
  "high": "Cao",
  "createContact": "Tạo danh bạ",
  "recommend": "Đề xuất",
  "comingSoon": "Sắp ra mắt",
  "connected": "Đã kết nối",
  "installCoin98Wallet": "Cài đặt Coin98 Wallet để quản lý ví",
  "coin98WalletNotInstalled": "Bạn chưa cài đặt Coin98 Wallet",
  "connectCoin98Wallet": "Kết nối với Coin98 Wallet",
  "BTCDominace": "BTC Dominance",
  "ETHDominace": "ETH Dominance",
  "rank": "Hạng",
  "onWatchList": "{{num}} trên DS theo dõi",
  "token": "Token",
  "day": "ngày",
  "month": "tháng",
  "week": "tuần",
  "year": "năm",
  "custom": "tuỳ chỉnh",
  "uniswapPrice": "Giá Uniswap",
  "low": "Thấp",
  "hight": "Cao",
  "fullDiluted": "Vốn hóa pha loãng hoàn toàn",
  "volume24h": "KL 24h",
  "totalSupply": "Tổng cung",
  "viewDetail": "Chi tiết",
  "from": "Từ",
  "to": "đến",
  "willReceive": "Bạn sẽ nhận được ~ ",
  "fee": "Phí",
  "balanceTotal": "Tổng số dư",
  "route": "Route",
  "step": "Bước",
  "finish": "Kết thúc",
  "swapHistory": "Lịch sử giao dịch",
  "coins": "Coins",
  "watchList": "DS theo dõi",
  "contract": "Hợp đồng",
  "priceChange": "Thay đổi giá",
  "tradingVolume": "KL giao dịch",
  "marketCapRank": "Xếp hạng vốn hóa",
  "atHight": "Cao nhất mọi thời điểm",
  "atLow": "Thấp nhất mọi thời điểm",
  "sushiPrice": " Thống kê giá",
  "showRows": "Hiển thị dòng",
  "filters": "Lọc",
  "overview": "Tổng quan",
  "chart": "Biểu đồ",
  "cryptoAsset": "Tài sản mã hoá",
  "historicalData": "Dữ liệu lịch sử",
  "tradingView": "Trading View",
  "uniswapChart": "Biểu đồ Uniswap",
  "name": "tên",
  "liquidity": "Thanh khoản",
  "Volume": "KL",
  "fees": "phí",
  "topPairs": "Top Cặp",
  "searchPairToken": "Tìm cặp và token",
  "invalidPassPhrase": "Bạn vui lòng kiểm tra lại Passphrase hoặc Private Key!",
  "needCreate": "Bạn cần tạo hoặc khôi phục ví Solana trước",
  "areYouCreate": "Bạn chắc chắn muốn tạo ví mới?",
  "willBeStored": "sẽ được lưu trữ trong ví {{nameChainWallet}}",
  "feeTransactionMust": "Phí giao dịch tối thiểu là {{num}} {{symbol}}",
  "chainNotSupported": "chain chưa được hỗ trợ",
  "nameChart": "{{symbol}} biểu đồ",
  "areYouLogout": "Bạn chắc chắn muốn thoát?",
  "vol24h": "KL 24h",
  "volumeMarket": "Khối lượng / Vốn hóa",
  "resetFilters": "Cài lại bộ lọc",
  "sureToSend": "Bạn chắc chắn muốn chuyển {{num}} {{symbol}} đến địa chỉ {{address}}?",
  "sumAddress": "{{num}} Địa chỉ",
  "amountCannotZero": "Số lượng phải lớn hơn 0",
  "multiSend": "Multi-Send",
  "totalAddress": "Tổng ví",
  "addressEmpty": "Địa chỉ không được để trống",
  "amountEmpty": "Số lượng không được để trống",
  "inputNotRequirements": "Thông tin không đáp ứng yêu cầu",
  "gwei": "Gwei",
  "hi": "Xin chào",
  "forTransaction": "Cho giao dịch",
  "approveConversion": "Xét duyệt chuyển đổi",
  "sendFound": "Gửi tiền",
  "waitForConfirm": "Chờ xác nhận",
  "rename": "Đổi tên",
  "questionRename": "Bạn có chắc muốn đổi tên ví?",
  "questionImport": "Bạn có chắc muốn nhập địa chỉ và số lượng?",
  "alreadySend": "Đã gửi",
  "resendOTP": "Gửi lại OTP thành công",
  "fortmatic": "Fortmatic",
  "coinbaseWallet": "Coinbase Wallet",
  "walletConnect": "Wallet Connect",
  "metaMask": "MetaMask",
  "dapper": "Dapper",
  "lattice": "Lattice",
  "private": "Private",
  "activeMultiChain": "Kích hoạt ví Multi-Chain",
  "activeChain": "Kích hoạt ví {{chain}}",
  "removeWallet": "Xoá ví {{name}}",
  "noMatchingResult": "Không tìm thấy",
  "areYouSureSend": "Gửi {{num}} {{symbol}} <br/> {{address}}",
  "addressAmount": "địa chỉ?số lượng,địa chỉ?số lượng",
  "import": "Nhập",
  "addressAndAmount": "Địa chỉ và số lượng",
  "gasPrice": "Giá GAS",
  "transactionData": "DỮ LIỆU GIAO DỊCH",
  "gasLimit": "GIỚI HẠN GAS",
  "nonce": "NONCE",
  "change24h": "% Thay đổi",
  "rankTop": "Hạng 100-200",
  "nameRank": "Tên",
  "hour24Trading": "KL giao dịch 24H",
  "lowHight24h": "24h Thấp / Cao",
  "allTimeLowHigh": "Thấp/Cao nhất mọi thời điểm",
  "unlimitedApproval": "Duyệt không giới hạn",
  "estimateFee": "Phí tạm tính",
  "searchCoinOrPasteAnyToken": "Tìm kiếm coin hoặc dán bất kỳ token",
  "transactionDeadline": "Hạn chót giao dịch",
  "owners": "Chủ sở hữu",
  "votingRate": "Tỷ lệ bỏ phiếu",
  "withdraw": "Rút",
  "update": "Cập nhật",
  "approved": "Đã duyệt",
  "waiting": "Đợi",
  "totalFound": "Tổng tìm thấy",
  "totalOwner": "Tổng chủ sở hữu",
  "awaitingApprove": "Chờ duyệt",
  "voteRate": "Tỷ lệ bỏ phiếu",
  "owner": "Chủ sở hữu",
  "change": "Thay đổi",
  "ownersAddress": "Địa chỉ chủ sở hữu",
  "votingPower": "Quyền hạn voting",
  "type": "Loại",
  "date": "Ngày",
  "status": "Trạng thái",
  "process": "Tiến độ",
  "transactionId": "ID giao dịch",
  "creator": "Người tạo",
  "wellcome": "Chào mừng đến",
  "multisig": "Ví đa chữ ký",
  "createNew": "Tạo mới",
  "addOwner": "Thêm chủ sở hữu",
  "addVoteRate": "Thêm tỷ lệ bỏ phiếu",
  "multisigWalletName": "Tên ví đa chữ ký",
  "c98Private": "C98 Private Fund",
  "successSent": "Đã gửi thành công",
  "removeOwner": "Xoá chủ sở hữu",
  "newVoteRate": "Tỷ lệ bỏ phiếu mới",
  "newVotePower": "Quyền hạn bỏ phiếu mới",
  "poweredByCoin98": "Được hỗ trợ bởi Coin98 Wallet Engine",
  "lessThan": "Ít hơn",
  "noSpace": "Không dấu cách",
  "characters": "ký tự",
  "createTokenError": "Lỗi tạo bên phát hành token",
  "createTokenSuccess": "Tạo bên phát hành token thành công",
  "confirmCreateTokenIssue": "Bạn có chắc xác nhận nhà phát hành token?",
  "pleaseInput": "Vui lòng nhập",
  "invalidAddrWallet": "Địa chỉ không đúng",
  "wallet": "ví",
  "tokenName": "TÊN TOKEN",
  "tokenSymbol": "BIỂU TƯỢNG TOKEN",
  "decimalPoint": "DECIMAL POINTS",
  "ownerAddress": "ĐỊA CHỈ CHỦ SỞ HỮU",
  "tokenLogo": "TOKEN LOGO",
  "selectChain": "chọn chain",
  "tokenMint": "TOKEN MINT",
  "tokenBurn": "TOKEN BURN",
  "powerByCoin98": "Được cung cấp bởi Coin98 Labs"
}